// This file is auto-generated by UnityConstantsGenerator.

// ReSharper disable once CheckNamespace
namespace UnityConstants
{
    /// <summary>
    /// Convenience class for UNITY Tags
    /// </summary>
    public static class Tags
    {
        public const string Untagged = "Untagged";
        public const string Respawn = "Respawn";
        public const string Finish = "Finish";
        public const string EditorOnly = "EditorOnly";
        public const string MainCamera = "MainCamera";
        public const string Player = "Player";
        public const string GameController = "GameController";
        public const string Xaxis = "Xaxis";
        public const string Goal = "Goal";
        public const string Ball = "Ball";
        public const string PelaajaAlue1 = "PelaajaAlue-1";
        public const string PelaajaAlue2 = "PelaajaAlue-2";
        public const string PelaajaAlue3 = "PelaajaAlue-3";
        public const string PelaajaAlue4 = "PelaajaAlue-4";
        public const string PalloPeliAlue = "PalloPeliAlue";
        public const string ErikoisTiili = "ErikoisTiili";
        public const string Pelaaja1 = "Pelaaja-1";
        public const string Pelaaja2 = "Pelaaja-2";
        public const string Pelaaja3 = "Pelaaja-3";
        public const string Pelaaja4 = "Pelaaja-4";
        public const string TopSide = "TopSide";
        public const string BotSide = "BotSide";
        public const string RedTeam = "RedTeam";
        public const string BlueTeam = "BlueTeam";
    }

    /// <summary>
    /// Convenience class for UNITY SortingLayers
    /// </summary>
    public static class SortingLayers
    {
        /// <summary>
        /// ID of sorting layer 'Default'.
        /// </summary>
        public const int Default = 0;
    }

    /// <summary>
    /// Convenience class for UNITY Layers
    /// </summary>
    public static class Layers
    {
        // Index of layer
        public const int Default = 0;
        public const int TransparentFX = 1;
        public const int IgnoreRaycast = 2;
        public const int Water = 4;
        public const int UI = 5;
        public const int Shield = 8;
        public const int Ball = 9;
        public const int Head = 10;
        public const int Wall = 11;
        public const int Player = 12;
        public const int Arena = 13;
        public const int Brick = 14;

        // Bitmask of layer
        public const int TransparentFXMask = 1 << 1;
        public const int IgnoreRaycastMask = 1 << 2;
        public const int WaterMask = 1 << 4;
        public const int UIMask = 1 << 5;
        public const int ShieldMask = 1 << 8;
        public const int BallMask = 1 << 9;
        public const int HeadMask = 1 << 10;
        public const int WallMask = 1 << 11;
        public const int PlayerMask = 1 << 12;
        public const int ArenaMask = 1 << 13;
        public const int BrickMask = 1 << 14;
    }
}