Battle: Battle.QSimulation.Game.BattleQConfig Class Reference
Battle.QSimulation.Game.BattleQConfig Class Reference
Static Public Member Functions
static BattleArenaQSpec GetArenaSpec (Frame f)
static BattleSoulWallQSpec GetSoulWallSpec (Frame f)
static BattleProjectileQSpec GetProjectileSpec (Frame f)
static BattleDiamondQSpec GetDiamondSpec (Frame f)
static BattlePlayerQSpec GetPlayerSpec (Frame f)
static BattlePlayerBotQSpec GetPlayerBotSpec (Frame f)
Public Attributes
AssetRef< BattleArenaQSpec > BattleArenaSpec
AssetRef< BattleSoulWallQSpec > BattleSoulWallSpec
AssetRef< BattleProjectileQSpec > BattleProjectileSpec
AssetRef< BattleDiamondQSpec > BattleDiamondSpec
AssetRef< BattlePlayerQSpec > BattlePlayerSpec
AssetRef< BattlePlayerBotQSpec > BattlePlayerBotSpec
Member Function Documentation
GetArenaSpec()
BattleArenaQSpec Battle.QSimulation.Game.BattleQConfig.GetArenaSpec (Frame f) inline static
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.CreateMap(), and Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
GetDiamondSpec()
BattleDiamondQSpec Battle.QSimulation.Game.BattleQConfig.GetDiamondSpec (Frame f) inline static
Referenced by Battle.QSimulation.Diamond.BattleDiamondQSystem.OnProjectileHitSoulWall(), and Battle.QSimulation.Diamond.BattleDiamondQSystem.Update().
GetPlayerBotSpec()
BattlePlayerBotQSpec Battle.QSimulation.Game.BattleQConfig.GetPlayerBotSpec (Frame f) inline static
Referenced by Battle.QSimulation.Player.BattlePlayerBotController.GetBotCharacters(), and Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput().
GetPlayerSpec()
BattlePlayerQSpec Battle.QSimulation.Game.BattleQConfig.GetPlayerSpec (Frame f) inline static
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerCharacter(), Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerShield(), and Battle.QSimulation.Player.BattlePlayerMovementController.UpdateMovement().
GetProjectileSpec()
BattleProjectileQSpec Battle.QSimulation.Game.BattleQConfig.GetProjectileSpec (Frame f) inline static
Referenced by Battle.QSimulation.Projectile.BattleProjectileQSystem.Launch(), and Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem.Update().
GetSoulWallSpec()
BattleSoulWallQSpec Battle.QSimulation.Game.BattleQConfig.GetSoulWallSpec (Frame f) inline static
Referenced by Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateAbilitySoulWallTest(), and Battle.QSimulation.Game.BattleGameControlQSystem.CreateMap().
Member Data Documentation
BattleArenaSpec
AssetRef<BattleArenaQSpec> Battle.QSimulation.Game.BattleQConfig.BattleArenaSpec
BattleDiamondSpec
AssetRef<BattleDiamondQSpec> Battle.QSimulation.Game.BattleQConfig.BattleDiamondSpec
BattlePlayerBotSpec
AssetRef<BattlePlayerBotQSpec> Battle.QSimulation.Game.BattleQConfig.BattlePlayerBotSpec
BattlePlayerSpec
AssetRef<BattlePlayerQSpec> Battle.QSimulation.Game.BattleQConfig.BattlePlayerSpec
BattleProjectileSpec
AssetRef<BattleProjectileQSpec> Battle.QSimulation.Game.BattleQConfig.BattleProjectileSpec
BattleSoulWallSpec
AssetRef<BattleSoulWallQSpec> Battle.QSimulation.Game.BattleQConfig.BattleSoulWallSpec
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleQConfig.cs