Battle: Quantum.Statics Class Reference
Quantum.Statics Class Reference
Static Public Member Functions
static void EnsureNotStrippedGen ()
Static Public Attributes
static FrameSerializer.Delegate SerializeBattlePlayerHitboxColliderTemplate
static FrameSerializer.Delegate SerializeEntityRef
static FrameSerializer.Delegate SerializeBattlePlayerCharacterState
static FrameSerializer.Delegate SerializeQBoolean
static FrameSerializer.Delegate SerializeBattlePlayerPlayState
static FrameSerializer.Delegate SerializePlayerRef
static FrameSerializer.Delegate SerializeFrameTimer
static FrameSerializer.Delegate SerializeBattleProjectileCollisionFlags
static FrameSerializer.Delegate SerializeQString64
static FrameSerializer.Delegate SerializeInput
Static Private Member Functions
static partial void InitStaticDelegatesGen ()
static partial void RegisterSimulationTypesGen (TypeRegistry typeRegistry)
static partial void InitComponentTypeIdGen ()
Member Function Documentation
EnsureNotStrippedGen()
void Quantum.Statics.EnsureNotStrippedGen () inline static
InitComponentTypeIdGen()
partial void Quantum.Statics.InitComponentTypeIdGen () inline static private
References Quantum.BattlePlayerDataTemplateQComponent.OnRemoved(), Quantum.BattleArenaBorderQComponent.Serialize(), Quantum.BattleCollisionTriggerQComponent.Serialize(), Quantum.BattleDiamondCounterQSingleton.Serialize(), Quantum.BattleDiamondDataQComponent.Serialize(), Quantum.BattleGameSessionQSingleton.Serialize(), Quantum.BattleGoalQComponent.Serialize(), Quantum.BattlePlayerClassDesensitizerDataQComponent.Serialize(), Quantum.BattlePlayerClassProjectorDataQComponent.Serialize(), Quantum.BattlePlayerDataQComponent.Serialize(), Quantum.BattlePlayerDataTemplateQComponent.Serialize(), Quantum.BattlePlayerHitboxQComponent.Serialize(), Quantum.BattlePlayerManagerDataQSingleton.Serialize(), Quantum.BattleProjectileQComponent.Serialize(), Quantum.BattleProjectileSpawnerQComponent.Serialize(), and Quantum.BattleSoulWallQComponent.Serialize().
InitStaticDelegatesGen()
partial void Quantum.Statics.InitStaticDelegatesGen () inline static private
References Quantum.BattlePlayerHitboxColliderTemplate.Serialize(), Quantum.QString64.Serialize(), SerializeBattlePlayerCharacterState, SerializeBattlePlayerHitboxColliderTemplate, SerializeBattlePlayerPlayState, SerializeBattleProjectileCollisionFlags, SerializeEntityRef, SerializeFrameTimer, SerializeInput, SerializePlayerRef, SerializeQBoolean, and SerializeQString64.
RegisterSimulationTypesGen()
partial void Quantum.Statics.RegisterSimulationTypesGen (TypeRegistry typeRegistry) inline static private
References Quantum._globals_.SIZE, Quantum.BattleArenaBorderQComponent.SIZE, Quantum.BattleCollisionTriggerQComponent.SIZE, Quantum.BattleDiamondCounterQSingleton.SIZE, Quantum.BattleDiamondDataQComponent.SIZE, Quantum.BattleGameSessionQSingleton.SIZE, Quantum.BattleGoalQComponent.SIZE, Quantum.BattleGridPosition.SIZE, Quantum.BattlePlayerClassDesensitizerDataQComponent.SIZE, Quantum.BattlePlayerClassProjectorDataQComponent.SIZE, Quantum.BattlePlayerDataQComponent.SIZE, Quantum.BattlePlayerDataTemplateQComponent.SIZE, Quantum.BattlePlayerHitboxColliderTemplate.SIZE, Quantum.BattlePlayerHitboxQComponent.SIZE, Quantum.BattlePlayerHitboxTemplate.SIZE, Quantum.BattlePlayerManagerDataQSingleton.SIZE, Quantum.BattlePlayerStats.SIZE, Quantum.BattleProjectileQComponent.SIZE, Quantum.BattleProjectileSpawnerQComponent.SIZE, Quantum.BattleSoulWallQComponent.SIZE, Quantum.BattleSoulWallTemplate.SIZE, Quantum.BattleWaitForPlayersData.SIZE, Quantum.BitSet128.SIZE, Quantum.BitSet2048.SIZE, Quantum.BitSet256.SIZE, Quantum.BitSet4096.SIZE, Quantum.BitSet512.SIZE, Quantum.BitSet6.SIZE, Quantum.Input.SIZE, Quantum.QString512.SIZE, and Quantum.QString64.SIZE.
Member Data Documentation
SerializeBattlePlayerCharacterState
FrameSerializer.Delegate Quantum.Statics.SerializeBattlePlayerCharacterState static
Referenced by InitStaticDelegatesGen(), and Quantum.BattlePlayerManagerDataQSingleton.Serialize().
SerializeBattlePlayerHitboxColliderTemplate
FrameSerializer.Delegate Quantum.Statics.SerializeBattlePlayerHitboxColliderTemplate static
Referenced by InitStaticDelegatesGen(), and Quantum.BattlePlayerHitboxTemplate.Serialize().
SerializeBattlePlayerPlayState
FrameSerializer.Delegate Quantum.Statics.SerializeBattlePlayerPlayState static
Referenced by InitStaticDelegatesGen(), and Quantum.BattlePlayerManagerDataQSingleton.Serialize().
SerializeBattleProjectileCollisionFlags
FrameSerializer.Delegate Quantum.Statics.SerializeBattleProjectileCollisionFlags static
Referenced by InitStaticDelegatesGen(), and Quantum.BattleProjectileQComponent.Serialize().
SerializeEntityRef
FrameSerializer.Delegate Quantum.Statics.SerializeEntityRef static
Referenced by InitStaticDelegatesGen(), and Quantum.BattlePlayerManagerDataQSingleton.Serialize().
SerializeFrameTimer
FrameSerializer.Delegate Quantum.Statics.SerializeFrameTimer static
Referenced by InitStaticDelegatesGen(), and Quantum.BattlePlayerManagerDataQSingleton.Serialize().
SerializeInput
FrameSerializer.Delegate Quantum.Statics.SerializeInput static
Referenced by InitStaticDelegatesGen(), and Quantum._globals_.SerializeCodeGen().
SerializePlayerRef
FrameSerializer.Delegate Quantum.Statics.SerializePlayerRef static
Referenced by InitStaticDelegatesGen(), and Quantum.BattlePlayerManagerDataQSingleton.Serialize().
SerializeQBoolean
FrameSerializer.Delegate Quantum.Statics.SerializeQBoolean static
Referenced by InitStaticDelegatesGen(), and Quantum.BattlePlayerManagerDataQSingleton.Serialize().
SerializeQString64
FrameSerializer.Delegate Quantum.Statics.SerializeQString64 static
Referenced by InitStaticDelegatesGen(), and Quantum.BattleWaitForPlayersData.Serialize().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs