Battle: Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype Class Reference
Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattlePlayerDataTemplateQComponent result, in PrototypeMaterializationContext context=default)
Public Attributes
Int32 GridExtendTop
Int32 GridExtendBottom
Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype HitboxShield
Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype HitboxCharacter
QBoolean DisableRotation
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattlePlayerDataTemplateQComponent result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.Materialize (Frame frame, ref Quantum.BattlePlayerDataTemplateQComponent result, in PrototypeMaterializationContext context = default) inline
References Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype.Materialize(), and MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.MaterializeUser (Frame frame, ref Quantum.BattlePlayerDataTemplateQComponent result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
DisableRotation
QBoolean Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.DisableRotation
GridExtendBottom
Int32 Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.GridExtendBottom
GridExtendTop
Int32 Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.GridExtendTop
HitboxCharacter
Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.HitboxCharacter
HitboxShield
Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.HitboxShield
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs