Battle: Battle.QSimulation.Player.BattlePlayerBotController Class Reference
Battle.QSimulation.Player.BattlePlayerBotController Class Reference
Handles the bot logic and implements helper methods for handling bots.
Static Public Member Functions
static BattleCharacterBase[] GetBotCharacters (Frame f)
Helper method to get characters for a bot.
static void GetBotInput (Frame f, bool isInPlay, BattlePlayerDataQComponent *playerData, Input *outBotInput)
Handles bot AI by predicting the projectile and generating the input for a bot.
Detailed Description
Handles the bot logic and implements helper methods for handling bots.
{Player Overview}
{Player Simulation Code Overview}
Bot AI is handled by generating input in GetBotInput that can be processed by the player like any other Input. Bot behavior and other spec settings are defined in BattlePlayerBotQSpec.
Member Function Documentation
GetBotCharacters()
BattleCharacterBase[] Battle.QSimulation.Player.BattlePlayerBotController.GetBotCharacters (Frame f) inline static
Helper method to get characters for a bot.
Characters are retrieved from BattlePlayerBotQSpec.
Parameters
f Current simulation frame.
Returns
Array of characters for a bot.
References Quantum.Constants.BATTLE_PLAYER_CHARACTER_COUNT, Battle.QSimulation.Player.BattlePlayerBotQSpec.BotCharacter, and Battle.QSimulation.Game.BattleQConfig.GetPlayerBotSpec().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers().
GetBotInput()
void Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput (Frame f, bool isInPlay, BattlePlayerDataQComponent * playerData, Input * outBotInput) inline static
Handles bot AI by predicting the projectile and generating the input for a bot.
Bot behavior spec settings is defined in BattlePlayerBotQSpec.
Parameters
f Current simulation frame.
isInPlay Bool to check if bot is in play.
playerData Pointer to player's BattlePlayerDataQComponent.
outBotInput Pointer to where bot's Quantum Input will be written.
References Quantum.BattleGridPosition.Col, Battle.QSimulation.Game.BattleGridManager.Columns, Battle.QSimulation.Game.BattleQConfig.GetPlayerBotSpec(), Quantum.BattlePlayerDataQComponent.GridExtendBottom, Quantum.BattlePlayerDataQComponent.GridExtendTop, Battle.QSimulation.Player.BattlePlayerBotQSpec.Inaccuracy, Battle.QSimulation.Player.BattlePlayerBotQSpec.LookAheadTimeSec, Battle.QSimulation.Player.BattlePlayerBotQSpec.MissClickChance, Quantum.BattlePlayerDataQComponent.MovementCooldownSec, Battle.QSimulation.Player.BattlePlayerBotQSpec.MovementCooldownSecMax, Battle.QSimulation.Player.BattlePlayerBotQSpec.MovementCooldownSecMin, Quantum.BattleGridPosition.Row, Battle.QSimulation.Game.BattleGridManager.TeamAlphaFieldEnd, Battle.QSimulation.Game.BattleGridManager.TeamAlphaFieldStart, Battle.QSimulation.Game.BattleGridManager.TeamBetaFieldEnd, Battle.QSimulation.Game.BattleGridManager.TeamBetaFieldStart, Quantum.BattlePlayerDataQComponent.TeamNumber, and Battle.QSimulation.Game.BattleGridManager.WorldPositionToGridPosition().
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.GetInput().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerBotController.cs