Battle: Quantum.Prototypes.BattlePlayerDataQComponentPrototype Class Reference
Quantum.Prototypes.BattlePlayerDataQComponentPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattlePlayerDataQComponent result, in PrototypeMaterializationContext context=default)
Public Attributes
PlayerRef PlayerRef
Quantum.QEnum32< BattlePlayerSlot > Slot
Quantum.QEnum32< BattleTeamNumber > TeamNumber
Int32 CharacterId
Quantum.QEnum32< BattlePlayerCharacterClass > CharacterClass
Quantum.Prototypes.BattlePlayerStatsPrototype Stats
Int32 GridExtendTop
Int32 GridExtendBottom
QBoolean HasTargetPosition
FPVector2 TargetPosition
FP RotationBase
FP RotationOffset
FP CurrentHp
FP CurrentDefence
MapEntityId HitboxShieldEntity
MapEntityId HitboxCharacterEntity
QBoolean DisableRotation
Quantum.Prototypes.FrameTimerPrototype DamageCooldown
FP MovementCooldownSec
Quantum.Prototypes.FrameTimerPrototype AbilityCooldownSec
Quantum.Prototypes.FrameTimerPrototype AbilityActivateBufferSec
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattlePlayerDataQComponentPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattlePlayerDataQComponentPrototype.Materialize (Frame frame, ref Quantum.BattlePlayerDataQComponent result, in PrototypeMaterializationContext context = default) inline
References Quantum.Prototypes.BattlePlayerStatsPrototype.Materialize().
Referenced by AddToEntity().
Member Data Documentation
AbilityActivateBufferSec
Quantum.Prototypes.FrameTimerPrototype Quantum.Prototypes.BattlePlayerDataQComponentPrototype.AbilityActivateBufferSec
AbilityCooldownSec
Quantum.Prototypes.FrameTimerPrototype Quantum.Prototypes.BattlePlayerDataQComponentPrototype.AbilityCooldownSec
CharacterClass
Quantum.QEnum32<BattlePlayerCharacterClass> Quantum.Prototypes.BattlePlayerDataQComponentPrototype.CharacterClass
CharacterId
Int32 Quantum.Prototypes.BattlePlayerDataQComponentPrototype.CharacterId
CurrentDefence
FP Quantum.Prototypes.BattlePlayerDataQComponentPrototype.CurrentDefence
CurrentHp
FP Quantum.Prototypes.BattlePlayerDataQComponentPrototype.CurrentHp
DamageCooldown
Quantum.Prototypes.FrameTimerPrototype Quantum.Prototypes.BattlePlayerDataQComponentPrototype.DamageCooldown
DisableRotation
QBoolean Quantum.Prototypes.BattlePlayerDataQComponentPrototype.DisableRotation
GridExtendBottom
Int32 Quantum.Prototypes.BattlePlayerDataQComponentPrototype.GridExtendBottom
GridExtendTop
Int32 Quantum.Prototypes.BattlePlayerDataQComponentPrototype.GridExtendTop
HasTargetPosition
QBoolean Quantum.Prototypes.BattlePlayerDataQComponentPrototype.HasTargetPosition
HitboxCharacterEntity
MapEntityId Quantum.Prototypes.BattlePlayerDataQComponentPrototype.HitboxCharacterEntity
HitboxShieldEntity
MapEntityId Quantum.Prototypes.BattlePlayerDataQComponentPrototype.HitboxShieldEntity
MovementCooldownSec
FP Quantum.Prototypes.BattlePlayerDataQComponentPrototype.MovementCooldownSec
PlayerRef
PlayerRef Quantum.Prototypes.BattlePlayerDataQComponentPrototype.PlayerRef
RotationBase
FP Quantum.Prototypes.BattlePlayerDataQComponentPrototype.RotationBase
RotationOffset
FP Quantum.Prototypes.BattlePlayerDataQComponentPrototype.RotationOffset
Slot
Quantum.QEnum32<BattlePlayerSlot> Quantum.Prototypes.BattlePlayerDataQComponentPrototype.Slot
Stats
Quantum.Prototypes.BattlePlayerStatsPrototype Quantum.Prototypes.BattlePlayerDataQComponentPrototype.Stats
TargetPosition
FPVector2 Quantum.Prototypes.BattlePlayerDataQComponentPrototype.TargetPosition
TeamNumber
Quantum.QEnum32<BattleTeamNumber> Quantum.Prototypes.BattlePlayerDataQComponentPrototype.TeamNumber
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs