Battle: Quantum.Prototypes.BattleGridPositionPrototype Class Reference
Quantum.Prototypes.BattleGridPositionPrototype Class Reference
Public Member Functions
void Materialize (Frame frame, ref Quantum.BattleGridPosition result, in PrototypeMaterializationContext context=default)
Public Attributes
Int32 Row
Int32 Col
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleGridPosition result, in PrototypeMaterializationContext context)
Member Function Documentation
Materialize()
void Quantum.Prototypes.BattleGridPositionPrototype.Materialize (Frame frame, ref Quantum.BattleGridPosition result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by Quantum.Prototypes.BattleSoulWallTemplatePrototype.Materialize(), and Quantum.Prototypes.InputPrototype.Materialize().
MaterializeUser()
partial void Quantum.Prototypes.BattleGridPositionPrototype.MaterializeUser (Frame frame, ref Quantum.BattleGridPosition result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
Col
Int32 Quantum.Prototypes.BattleGridPositionPrototype.Col
Row
Int32 Quantum.Prototypes.BattleGridPositionPrototype.Row
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs