Battle: Quantum.Prototypes.BattleDiamondCounterQSingletonPrototype Class Reference
Quantum.Prototypes.BattleDiamondCounterQSingletonPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattleDiamondCounterQSingleton result, in PrototypeMaterializationContext context=default)
Public Attributes
Int32 AlphaDiamonds
Int32 BetaDiamonds
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleDiamondCounterQSingleton result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattleDiamondCounterQSingletonPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattleDiamondCounterQSingletonPrototype.Materialize (Frame frame, ref Quantum.BattleDiamondCounterQSingleton result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattleDiamondCounterQSingletonPrototype.MaterializeUser (Frame frame, ref Quantum.BattleDiamondCounterQSingleton result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
AlphaDiamonds
Int32 Quantum.Prototypes.BattleDiamondCounterQSingletonPrototype.AlphaDiamonds
BetaDiamonds
Int32 Quantum.Prototypes.BattleDiamondCounterQSingletonPrototype.BetaDiamonds
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs