Battle: Battle.View.UI.BattleUiDebugOverlayHandler Class Reference
Battle.View.UI.BattleUiDebugOverlayHandler Class Reference
DebugOverlay UI Handler (Unity MonoBehaviour script🡵).
Handles displaying the debug info.
Controlled by BattleDebugOverlay.
Classes
struct Entry
Private struct used internally to hold references to the Name and Value TMP_Text components for entries.
Public Member Functions
void SetShow (bool show)
Sets the UI element visibility.
void AddEntries (string[] names)
Method for adding multiple new entries.
void SetEntries (int entryNumber, string[] textArray)
Method for setting multiple existing entries.
Properties
bool IsVisible [get]
Is the UI element visible or not.
Private Member Functions
void UpdateLayout ()
Method for updating entries' layout.
void CalculateNameColumnLayout ()
Private helper method for calculating how wide the name column should be.
Stored in _nameColumnWidth.
void CalculateValueColumnLayout ()
Private helper method for calculating how wide the value column should be.
Stored in _valueColumnWidth.
Private Attributes
float _nameColumnWidth
Width of the name column.
float _valueColumnWidth
Width of the value column.
readonly List< Entry > _entries = new List<Entry>()
List of the entries.
SerializeField variables
SerializeFields🡵 are serialized variables exposed to the Unity editor.
GameObject _view
[SerializeField] Reference to the GameObject which can be used to hide or show the overlay.
GameObject _entryTemplate
[SerializeField] Reference to the GameObject which is used as template when instantiating entries.
Transform _entryParent
[SerializeField] Reference to the Transform which the entries are parented to.
float _entryHeight
[SerializeField] The entry height.
float _entryMargin
[SerializeField] The entry margin.
float _entryFontSize
[SerializeField] The entry font size.
Detailed Description
DebugOverlay UI Handler (Unity MonoBehaviour script🡵).
Handles displaying the debug info.
Controlled by BattleDebugOverlay.
Member Function Documentation
AddEntries()
void Battle.View.UI.BattleUiDebugOverlayHandler.AddEntries (string[] names) inline
Method for adding multiple new entries.
Creates as many entries as there are elements in the names array.
After adding entries calls CalculateNameColumnLayout and UpdateLayout.
Parameters
names An array of strings used to give name to entries.
References _entries, _entryFontSize, _entryParent, _entryTemplate, CalculateNameColumnLayout(), and UpdateLayout().
CalculateNameColumnLayout()
void Battle.View.UI.BattleUiDebugOverlayHandler.CalculateNameColumnLayout () inline private
Private helper method for calculating how wide the name column should be.
Stored in _nameColumnWidth.
References _entries, _entryMargin, _nameColumnWidth, and Battle.View.UI.BattleUiDebugOverlayHandler.Entry.Name.
Referenced by AddEntries().
CalculateValueColumnLayout()
void Battle.View.UI.BattleUiDebugOverlayHandler.CalculateValueColumnLayout () inline private
Private helper method for calculating how wide the value column should be.
Stored in _valueColumnWidth.
References _entries, _entryMargin, _valueColumnWidth, and Battle.View.UI.BattleUiDebugOverlayHandler.Entry.Value.
Referenced by SetEntries().
SetEntries()
void Battle.View.UI.BattleUiDebugOverlayHandler.SetEntries (int entryNumber, string[] textArray) inline
Method for setting multiple existing entries.
Sets multiple entries from entryNumber to entrynumber + length of the textArray.
After setting entries calls CalculateValueColumnLayout and UpdateLayout.
Parameters
entryNumber Entry number used to identify the first entry.
textArray An array of strings used to give text to entries.
References _entries, CalculateValueColumnLayout(), and UpdateLayout().
SetShow()
void Battle.View.UI.BattleUiDebugOverlayHandler.SetShow (bool show) inline
Sets the UI element visibility.
Parameters
show If the UI element should be visible or not.
References _view.
UpdateLayout()
void Battle.View.UI.BattleUiDebugOverlayHandler.UpdateLayout () inline private
Method for updating entries' layout.
Positions and scales entries.
Uses _nameColumnWidth and _valueColumnWidth which are set by CalculateNameColumnLayout and CalculateValueColumnLayout.
References _entries, _entryHeight, _nameColumnWidth, and _valueColumnWidth.
Referenced by AddEntries(), and SetEntries().
Member Data Documentation
_entries
readonly List<Entry> Battle.View.UI.BattleUiDebugOverlayHandler._entries = new List<Entry>() private
List of the entries.
Referenced by AddEntries(), CalculateNameColumnLayout(), CalculateValueColumnLayout(), SetEntries(), and UpdateLayout().
_entryFontSize
float Battle.View.UI.BattleUiDebugOverlayHandler._entryFontSize private
[SerializeField] The entry font size.
SerializeFields
Referenced by AddEntries().
_entryHeight
float Battle.View.UI.BattleUiDebugOverlayHandler._entryHeight private
[SerializeField] The entry height.
SerializeFields
Referenced by UpdateLayout().
_entryMargin
float Battle.View.UI.BattleUiDebugOverlayHandler._entryMargin private
[SerializeField] The entry margin.
SerializeFields
Referenced by CalculateNameColumnLayout(), and CalculateValueColumnLayout().
_entryParent
Transform Battle.View.UI.BattleUiDebugOverlayHandler._entryParent private
[SerializeField] Reference to the Transform which the entries are parented to.
SerializeFields
Referenced by AddEntries().
_entryTemplate
GameObject Battle.View.UI.BattleUiDebugOverlayHandler._entryTemplate private
[SerializeField] Reference to the GameObject which is used as template when instantiating entries.
SerializeFields
Referenced by AddEntries().
_nameColumnWidth
float Battle.View.UI.BattleUiDebugOverlayHandler._nameColumnWidth private
Width of the name column.
Used by UpdateLayout.
Referenced by CalculateNameColumnLayout(), and UpdateLayout().
_valueColumnWidth
float Battle.View.UI.BattleUiDebugOverlayHandler._valueColumnWidth private
Width of the value column.
Used by UpdateLayout.
Referenced by CalculateValueColumnLayout(), and UpdateLayout().
_view
GameObject Battle.View.UI.BattleUiDebugOverlayHandler._view private
[SerializeField] Reference to the GameObject which can be used to hide or show the overlay.
SerializeFields
Referenced by SetShow().
Property Documentation
IsVisible
bool Battle.View.UI.BattleUiDebugOverlayHandler.IsVisible get
Is the UI element visible or not.
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/View/Battle/Scripts/UI/Handler/BattleUiDebugOverlayHandler.cs