Battle: Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem Class Reference
Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem Class Reference
ProjectileSpawner Quantum System游못 [Systems]
Handles spawning the projectile at the beginning of the game.
Classes
struct Filter
Filter for filtering entities with ProjectileSpawner component.
Public Member Functions
override void OnInit (Frame f)
Quantum System OnInit method游못 gets called when the system is initialized.
Initializes the projectile spawner component on a new entity, adding the SpawnerSystem.qtn component to ProjectileSpawnerSystem to ensure that the filter works
override void Update (Frame f, ref Filter filter)
Quantum system update method游못 gets called every frame.
Spawns a projectile if it's not already spawned and game is in 'Playing' state.
Private Member Functions
void SpawnProjectile (Frame f, AssetRef< EntityPrototype > childPrototype)
Creates a projectile entity using the specified prototype and initializes its components.
Private Attributes
BattleDebugLogger _debugLogger
This classes BattleDebugLogger instance.
Detailed Description
ProjectileSpawner Quantum System游못 [Systems]
Handles spawning the projectile at the beginning of the game.
An invisible entity with BattleProjectileSpawnerQComponent is created when system is initiated, which is then used to spawn the projectile when BattleGameState is changed to "Playing".
Member Function Documentation
OnInit()
override void Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem.OnInit (Frame f) inline
Quantum System OnInit method游못 gets called when the system is initialized.
Initializes the projectile spawner component on a new entity, adding the SpawnerSystem.qtn component to ProjectileSpawnerSystem to ensure that the filter works
Warning
This method should only be called by Quantum.
Parameters
f Current simulation frame.
References _debugLogger, Battle.QSimulation.BattleDebugLogger.Create(), and Quantum.BattleProjectileSpawnerQComponent.HasSpawned.
SpawnProjectile()
void Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem.SpawnProjectile (Frame f, AssetRef< EntityPrototype > childPrototype) inline private
Creates a projectile entity using the specified prototype and initializes its components.
Parameters
f Current simulation frame.
childPrototype Reference to the projectile prototype asset.
References Quantum.BattleProjectileQComponent.EmotionBase, Quantum.BattleProjectileQComponent.EmotionCurrent, and Quantum.BattleProjectileQComponent.Radius.
Referenced by Update().
Update()
override void Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem.Update (Frame f, ref Filter filter) inline
Quantum system update method游못 gets called every frame.
Spawns a projectile if it's not already spawned and game is in 'Playing' state.
Warning
This method should only be called by Quantum.
Parameters
f Current simulation frame.
filter Reference to Quantum Filter游못.
References _debugLogger, Battle.QSimulation.Game.BattleQConfig.GetProjectileSpec(), Battle.QSimulation.Projectile.BattleProjectileQSpec.ProjectilePrototype, SpawnProjectile(), and Quantum.BattleGameSessionQSingleton.State.
Member Data Documentation
_debugLogger
BattleDebugLogger Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem._debugLogger private
This classes BattleDebugLogger instance.
Referenced by OnInit(), and Update().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Projectile/BattleProjectileSpawnerQSystem.cs