Battle: Quantum.Prototypes.BattleArenaBorderQComponentPrototype Class Reference
Quantum.Prototypes.BattleArenaBorderQComponentPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattleArenaBorderQComponent result, in PrototypeMaterializationContext context=default)
Public Attributes
FPVector2 Normal
FP CollisionMinOffset
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleArenaBorderQComponent result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattleArenaBorderQComponentPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattleArenaBorderQComponentPrototype.Materialize (Frame frame, ref Quantum.BattleArenaBorderQComponent result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattleArenaBorderQComponentPrototype.MaterializeUser (Frame frame, ref Quantum.BattleArenaBorderQComponent result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
CollisionMinOffset
FP Quantum.Prototypes.BattleArenaBorderQComponentPrototype.CollisionMinOffset
Normal
FPVector2 Quantum.Prototypes.BattleArenaBorderQComponentPrototype.Normal
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs