Battle: Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype Class Reference
Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype Class Reference
Public Member Functions
void Materialize (Frame frame, ref Quantum.BattlePlayerHitboxTemplate result, in PrototypeMaterializationContext context=default)
Public Attributes
Quantum.Prototypes.BattlePlayerHitboxColliderTemplatePrototype[] ColliderTemplateList = {}
Quantum.QEnum32< BattlePlayerCollisionType > CollisionType
FP NormalAngleDeg
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattlePlayerHitboxTemplate result, in PrototypeMaterializationContext context)
Member Function Documentation
Materialize()
void Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype.Materialize (Frame frame, ref Quantum.BattlePlayerHitboxTemplate result, in PrototypeMaterializationContext context = default) inline
References ColliderTemplateList, and MaterializeUser().
Referenced by Quantum.Prototypes.BattlePlayerDataTemplateQComponentPrototype.Materialize().
MaterializeUser()
partial void Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype.MaterializeUser (Frame frame, ref Quantum.BattlePlayerHitboxTemplate result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
ColliderTemplateList
Quantum.Prototypes.BattlePlayerHitboxColliderTemplatePrototype [] Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype.ColliderTemplateList = {}
Referenced by Materialize().
CollisionType
Quantum.QEnum32<BattlePlayerCollisionType> Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype.CollisionType
NormalAngleDeg
FP Quantum.Prototypes.BattlePlayerHitboxTemplatePrototype.NormalAngleDeg
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs