Battle: Quantum.Prototypes.GameSessionPrototype Class Reference
Quantum.Prototypes.GameSessionPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.GameSession result, in PrototypeMaterializationContext context=default)
Public Attributes
Quantum.QEnum32< GameState > state
FP TimeUntilStart
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.GameSession result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.GameSessionPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.GameSessionPrototype.Materialize (Frame frame, ref Quantum.GameSession result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.GameSessionPrototype.MaterializeUser (Frame frame, ref Quantum.GameSession result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
state
Quantum.QEnum32<GameState> Quantum.Prototypes.GameSessionPrototype.state
TimeUntilStart
FP Quantum.Prototypes.GameSessionPrototype.TimeUntilStart
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs