Battle: Quantum.Prototypes.BattleCollisionTriggerQComponentPrototype Class Reference
Quantum.Prototypes.BattleCollisionTriggerQComponentPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattleCollisionTriggerQComponent result, in PrototypeMaterializationContext context=default)
Public Attributes
Quantum.QEnum32< BattleCollisionTriggerType > Type
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleCollisionTriggerQComponent result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattleCollisionTriggerQComponentPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattleCollisionTriggerQComponentPrototype.Materialize (Frame frame, ref Quantum.BattleCollisionTriggerQComponent result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattleCollisionTriggerQComponentPrototype.MaterializeUser (Frame frame, ref Quantum.BattleCollisionTriggerQComponent result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
Type
Quantum.QEnum32<BattleCollisionTriggerType> Quantum.Prototypes.BattleCollisionTriggerQComponentPrototype.Type
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs