Battle: Battle.QSimulation.BattleDebugLogger Class Reference
Battle.QSimulation.BattleDebugLogger Class Reference
Provides custom debug logging methods for use in Battle to apply consistant formatting to all Log messages.
Public Types
enum LogType { Log , Warning , Error }
Enum used to define log message types.
enum LogTarget { UnityConsole , OnScreenConsole }
Enum used to define where to display log messages.
Public Member Functions
Log Methods
Public Log methods that can only be used with a BattleDebugLogger instance.
See Log Methods Overview for more info.
void Log (string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message .
Uses the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
void Log (Frame f, string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message .
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
void LogFormat (string format, params object[] args)
Logs a formatted message based on the given format and args
Uses the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(source)] (formatted message).
void LogFormat (string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args
Uses the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
void LogFormat (Frame f, string format, params object[] args)
Logs a formatted message based on the given format and args
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (formatted message).
void LogFormat (Frame f, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
void Warning (string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message as a Warning.
Uses the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
void Warning (Frame f, string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message as a Warning.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
void WarningFormat (string format, params object[] args)
Logs a formatted message based on the given format and args as a Warning.
Uses the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message).
void WarningFormat (string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as a Warning.
Uses the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
void WarningFormat (Frame f, string format, params object[] args)
Logs a formatted message based on the given format and args as a Warning.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message).
void WarningFormat (Frame f, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as a Warning.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
void Error (string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Logs the given message as an Error.
Uses the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
void Error (Frame f, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Logs the given message as an Error.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
void ErrorFormat (string format, params object[] args)
Logs a formatted message based on the given format and args as an Error.
Uses the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message).
void ErrorFormat (string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as an Error.
Uses the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
void ErrorFormat (Frame f, string format, params object[] args)
Logs a formatted message based on the given format and args as an Error.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message).
void ErrorFormat (Frame f, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as an Error.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Assert Methods
Public Assert methods that can only be used with a BattleDebugLogger instance.
See Assert Methods Overview for more info.
void DevAssert (bool condition, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that condition is true during debugging and logs an Error(string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssert (Frame f, bool condition, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that condition is true during debugging and logs an Error(Frame, string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssert (Func< bool > assertCode, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that assertCode returns true during debugging and logs an Error(string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssert (Frame f, Func< bool > assertCode, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that assertCode returns true during debugging and logs an Error(Frame, string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (bool condition, string format, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (bool condition, string format, LogTarget logTarget, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (Frame f, bool condition, string format, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (Frame f, bool condition, string format, LogTarget logTarget, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (Func< bool > assertCode, string format, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (Func< bool > assertCode, string format, LogTarget logTarget, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (Frame f, Func< bool > assertCode, string format, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
void DevAssertFormat (Frame f, Func< bool > assertCode, string format, LogTarget logTarget, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Public Member Functions
static void InitOnScreenConsoleLink (Action< LogType, string, string > addLogToOnScreenConsoleFnRef)
Establishes link between BattleUiDebugConsoleHandler.
Create Methods
Methods for creating a BattleDebugLogger instance.
static BattleDebugLogger Create< T > ()
Creates a BattleDebugLogger instance using the given type T as a source.
static BattleDebugLogger Create (System.Type source)
Creates a BattleDebugLogger instance using the specified type source as a source.
static BattleDebugLogger Create (string source)
Creates a BattleDebugLogger instance using the specified string source as a source.
Static Log Methods
Static Log methods that can be used without a BattleDebugLogger instance.
See Log Methods Overview for more info.
static void Log (string source, string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message using the given source when formatting the Log message.
Output Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
static void Log (Frame f, string source, string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message using the given Quantum frame f and source when formatting the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
static void LogFormat (string source, string format, params object[] args)
Logs a formatted message based on the given format and args using the given source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message).
static void LogFormat (string source, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args using the given source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
static void LogFormat (Frame f, string source, string format, params object[] args)
Logs a formatted message based on the given format and args using the given Quantum frame f and source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message).
static void LogFormat (Frame f, string source, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args using the given Quantum frame f and source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
static void Warning (string source, string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message as a Warning using the given source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
static void Warning (Frame f, string source, string message, LogTarget logTarget=LogTarget.UnityConsole)
Logs the given message as a Warning using the given Quantum frame f and source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
static void WarningFormat (string source, string format, params object[] args)
Logs a formatted message based on the given format and args as a Warning using the given source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message).
static void WarningFormat (string source, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as a Warning using the given source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
static void WarningFormat (Frame f, string source, string format, params object[] args)
Logs a formatted message based on the given format and args as a Warning using the given Quantum frame f and source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message).
static void WarningFormat (Frame f, string source, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as a Warning using the given Quantum frame f and source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
static void Error (string source, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Logs the given message as an Error using the given source when formatting the Error Log message.
Output Error Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
static void Error (Frame f, string source, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Logs the given message as an Error using the given Quantum frame f and source when formatting the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
static void ErrorFormat (string source, string format, params object[] args)
Logs a formatted message based on the given format and args as an Error using the given source when formatting the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message).
static void ErrorFormat (string source, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as an Error using the given source when formatting the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
static void ErrorFormat (Frame f, string source, string format, params object[] args)
Logs a formatted message based on the given format and args as an Error using the given Quantum frame f and source when formatting the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message).
static void ErrorFormat (Frame f, string source, string format, LogTarget logTarget, params object[] args)
Logs a formatted message based on the given format and args as an Error using the given Quantum frame f and source when formatting the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Static Assert Methods
Static Assert Methods that can be used without a BattleDebugLogger instance.
See Assert Methods Overview for more info.
static void DevAssert (string source, bool condition, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that condition is true during debugging and logs an Error(string, string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssert (Frame f, string source, bool condition, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that condition is true during debugging and logs an Error(Frame, string, string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssert (string source, Func< bool > assertCode, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that assertCode returns true during debugging and logs an Error(string, string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssert (Frame f, string source, Func< bool > assertCode, string message, LogTarget logTarget=LogTarget.UnityConsole|LogTarget.OnScreenConsole)
Asserts that assertCode returns true during debugging and logs an Error(Frame, string, string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (string source, bool condition, string format, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(string, string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (string source, bool condition, string format, LogTarget logTarget, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(string, string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (Frame f, string source, bool condition, string format, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (Frame f, string source, bool condition, string format, LogTarget logTarget, params object[] args)
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (string source, Func< bool > assertCode, string format, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (string source, Func< bool > assertCode, string format, LogTarget logTarget, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (Frame f, string source, Func< bool > assertCode, string format, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
static void DevAssertFormat (Frame f, string source, Func< bool > assertCode, string format, LogTarget logTarget, params object[] args)
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Private Member Functions
BattleDebugLogger (string source)
Private constructor method called when any of the Create methods are called.
Creates the Log message formats used when calling Log methods based on constant templates.
Private Attributes
readonly string _instanceFormatUnity
Saved Log message format, set when creating a BattleDebugLogger instance.
readonly string _instanceFormatUnityNoFrame
Saved no Quantum frame Log message format, set when creating a BattleDebugLogger instance.
readonly string _instanceSourceFormatOnScreen
Saved on-screen Log message format, set when creating a BattleDebugLogger instance.
readonly string _instanceSourceFormatOnScreenNoFrame
Saved no Quantum frame on-screen Log message format, set when creating a BattleDebugLogger instance.
Static Private Attributes
const string StaticFormatUnity = "[Battle] [{0:D6}] [{1}] {2}"
Constant format for Log messages when called through static methods.
const string StaticFormatUnityNoFrame = "[Battle] [{0}] {1}"
Constant format for Log messages when called through static methods with no Quantum frame given.
const string InstanceFormatUnityTemplate = "[Battle] [{{0:D6}}] [{0}] {{1}}"
Constant format template for Log messages used to create the message format when creating a BattleDebugLogger instance.
const string InstanceFormatUnityNoFrameTemplate = "[Battle] [{0}] {{0}}"
Constant format template for Log messages used to create the no Quantum frame message format when creating a BattleDebugLogger instance.
const string StaticSourceFormatOnScreen = "[{0:D6}] [{1}]"
Constant format for on-screen Log messages when called through static methods.
const string StaticSourceFormatOnScreenNoFrame = "[{0}]"
Constant format for on-screen Log messages when called through static methods with no Quantum frame given.
const string InstanceSourceFormatOnScreenTemplate = "[{{0:D6}}] [{0}]"
Constant format template for on-screen Log messages used to create the message format when creating a BattleDebugLogger instance.
const string InstanceSourceFormatOnScreenNoFrameTemplate = "[{0}]"
Constant format template for on-screen Log messages used to create the no Quantum frame message format when creating a BattleDebugLogger instance.
static Action< LogType, string, string > s_addLogToOnScreenConsoleFnRef
Function reference to BattleUiDebugConsoleHandler.AddLog.
Detailed Description
Provides custom debug logging methods for use in Battle to apply consistant formatting to all Log messages.
Log Methods Overview
Log message format:
Unity console messages are formatted as such:
[Battle] [(Source)] (Log message)
Or with the Quantum frame:
[Battle] [(Quantum frame number)] [(Source)] (Log message)
On-screen console messages are formatted as such:
[(Source)] (Log message)
Or with the Quantum frame:
[(Quantum frame number)] [(Source)] (Log message)
The Quantum frame number is always presented as 6 digits:
[001234]
Log methods:
The Log method name structure consists of first the Log type, optionally followed by "Format".
(Log type)(Format?)
Methods have both a static and non-static version for use in different contexts.
Other classes can choose to either create an instance of this, or opt to use static method calls.
Log method types:
Log Logs a regular Log message in console.
Warning Logs a Warning Log message in console.
Error Logs an Error Log message in console.
Log method arguments:
f Quantum frame for use in message formatting.
source Source text for use in message formatting.
message / format The message or message format for the formatted message that is Logged.
logTarget Target output console for log messages.
Static and Instance methods:
All Static Log methods take source as an argument.
Instance methods use the source given when creating the instance.
See Create Methods
Passing Quantum frame:
All Log methods have two versions:
One that takes a Quantum frame as an argument.
One that doesn't.
If the Quantum frame is available it can be printed in the log message.
Formatted Log messages:
Methods that have the "Format" suffix in the method name take a format string in place of the message followed by an arbitrary amount of arguments for formatting.
The format string and arguments are formatted same as when using System.String.Format.
Log Target
Methods that takes the LogTarget as an argument have the option to choose which console output will be used.
Default output console for logs of type Log and Warning will be Unity console and logs of type Error will be logged to both.
With LogTarget you can choose to manually use on-screen console with all log types.
Examples:
BattleDebugLogger.Log(f, nameof(ExampleClass), "Example message");
BattleDebugLogger.WarningFormat(nameof(ExampleClass), "Example format {0}", value);
BattleDebugLogger debugLogger = BattleDebugLogger.Create<ExampleClass>();
debugLogger.ErrorFormat(f, "Example format {0} {1}", value1, value2);
debugLogger.Log("Example message");
debugLogger.Log("Example message", BattleDebugLogger.LogTarget.OnScreenConsole);
All Static Log Methods
All Instance Log Methods
Assert Methods Overview
Like Log methods, there are both a static and non-static version for use in different contexts.
Like Log methods, there's also assert format methods.
Assert methods take same arguments as Log methods but have additional condition or assertCode argument which is before message or format.
Assert methods that take in condition arguments simply assert that condition is true otherwise logs an error.
Assert methods that take in assertCode arguments runs the assertion code and asserts that it returns true otherwise logs an error.
Assert methods are only compiled and assertion code is ran when DEBUG_ASSERT is defined.
See Log Methods Overview
Examples:
BattleDebugLogger.DevAssert(nameof(ExampleClass), exampleValue > -1, "Example message");
BattleDebugLogger debugLogger = BattleDebugLogger.Create<ExampleClass>();
debugLogger.DevAssert(f, exampleValue > -1, "Example message");
debugLogger.DevAssert(() =>
{
    for (int i = 0; i < exampleArray.Length; i++)
    {
        if (exampleArray[i] < 0) return false;
    }
    return true;
}, "Example message");
All Static Assert Methods
All Instance Assert Methods
Member Enumeration Documentation
LogTarget
enum Battle.QSimulation.BattleDebugLogger.LogTarget
Enum used to define where to display log messages.
Enumerator
UnityConsole
Logs messages to Unity console.
OnScreenConsole
Logs messages to on-screen console.
LogType
enum Battle.QSimulation.BattleDebugLogger.LogType
Enum used to define log message types.
Enumerator
Log
Log message of type Log.
Warning
Log message of type Warning.
Error
Log message of type Error.
Constructor & Destructor Documentation
BattleDebugLogger()
Battle.QSimulation.BattleDebugLogger.BattleDebugLogger (string source) inline private
Private constructor method called when any of the Create methods are called.
Creates the Log message formats used when calling Log methods based on constant templates.
See Create Methods
Parameters
source The name of the source used when creating the Log message formats.
References _instanceFormatUnity, _instanceFormatUnityNoFrame, _instanceSourceFormatOnScreen, _instanceSourceFormatOnScreenNoFrame, InstanceFormatUnityNoFrameTemplate, InstanceFormatUnityTemplate, InstanceSourceFormatOnScreenNoFrameTemplate, and InstanceSourceFormatOnScreenTemplate.
Referenced by Create(), Create(), and Create< T >().
Member Function Documentation
Create() [1/2]
BattleDebugLogger Battle.QSimulation.BattleDebugLogger.Create (string source) inline static
Creates a BattleDebugLogger instance using the specified string source as a source.
Create Methods
Parameters
source The name of the source used when creating the instance.
Returns
The created BattleDebugLogger instance.
References BattleDebugLogger().
Create() [2/2]
BattleDebugLogger Battle.QSimulation.BattleDebugLogger.Create (System.Type source) inline static
Creates a BattleDebugLogger instance using the specified type source as a source.
Create Methods
Parameters
source The type used as source when creating the instance.
Returns
The created BattleDebugLogger instance.
References BattleDebugLogger().
Referenced by Battle.View.Game.BattleGameViewController.Awake(), Battle.View.UI.BattleUiGiveUpButtonHandler.Awake(), Battle.QSimulation.Game.BattleCollisionQSystem.Init(), Battle.QSimulation.Goal.BattleGoalQSystem.Init(), Battle.QSimulation.Player.BattlePlayerClassManager.Init(), Battle.QSimulation.Player.BattlePlayerManager.Init(), Battle.QSimulation.Player.BattlePlayerMovementController.Init(), Battle.QSimulation.Player.BattlePlayerQSystem.Init(), Battle.QSimulation.Projectile.BattleProjectileQSystem.Init(), Battle.QSimulation.SoulWall.BattleSoulWallQSystem.Init(), Battle.View.SoulWall.BattleSoulWallViewController.OnActivate(), Battle.View.Player.BattlePlayerInput.OnEnable(), Battle.QSimulation.Game.BattleGameControlQSystem.OnInit(), Battle.QSimulation.Projectile.BattleProjectileSpawnerQSystem.OnInit(), and Battle.View.Player.BattlePlayerViewController.PreInitSetup().
Create< T >()
BattleDebugLogger Battle.QSimulation.BattleDebugLogger.Create< T > () inline static
Creates a BattleDebugLogger instance using the given type T as a source.
Create Methods
Template Parameters
T The type used as source when creating the instance.
Returns
The created BattleDebugLogger instance.
References BattleDebugLogger().
DevAssert() [1/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (bool condition, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline
Asserts that condition is true during debugging and logs an Error(string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
When assertion fails, logs an error using Error(string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
condition Condition must be true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssert() [2/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (Frame f, bool condition, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline
Asserts that condition is true during debugging and logs an Error(Frame, string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
When assertion fails, logs an error using Error(Frame, string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssert() [3/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (Frame f, Func< bool > assertCode, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline
Asserts that assertCode returns true during debugging and logs an Error(Frame, string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using Error(Frame, string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssert() [4/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (Frame f, string source, bool condition, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline static
Asserts that condition is true during debugging and logs an Error(Frame, string, string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
When assertion fails, logs an error using Error(Frame, string, string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Warning Log message.
condition Condition must be true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssert() [5/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (Frame f, string source, Func< bool > assertCode, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline static
Asserts that assertCode returns true during debugging and logs an Error(Frame, string, string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using Error(Frame, string, string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Warning Log message.
assertCode Assertion code must return true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssert() [6/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (Func< bool > assertCode, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline
Asserts that assertCode returns true during debugging and logs an Error(string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using Error(string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
assertCode Assertion code must return true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssert() [7/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (string source, bool condition, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline static
Asserts that condition is true during debugging and logs an Error(string, string, LogTarget) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
When assertion fails, logs an error using Error(string, string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssert() [8/8]
void Battle.QSimulation.BattleDebugLogger.DevAssert (string source, Func< bool > assertCode, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline static
Asserts that assertCode returns true during debugging and logs an Error(string, string, LogTarget) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using Error(string, string, LogTarget) method.
See Assert Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
message The message that is Logged.
logTarget The target output console.
References Error().
DevAssertFormat() [1/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (bool condition, string format, LogTarget logTarget, params object[] args) inline
Asserts that condition is true during debugging and logs an ErrorFormat(string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
When assertion fails, logs an error using ErrorFormat(string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [2/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (bool condition, string format, params object[] args) inline
Asserts that condition is true during debugging and logs an ErrorFormat(string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
When assertion fails, logs an error using ErrorFormat(string, object[]) method.
See Assert Methods Overview for more info.
Parameters
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [3/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, bool condition, string format, LogTarget logTarget, params object[] args) inline
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
When assertion fails, logs an error using ErrorFormat(Frame, string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [4/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, bool condition, string format, params object[] args) inline
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
When assertion fails, logs an error using ErrorFormat(Frame, string, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [5/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, Func< bool > assertCode, string format, LogTarget logTarget, params object[] args) inline
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(Frame, string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [6/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, Func< bool > assertCode, string format, params object[] args) inline
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(Frame, string, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [7/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, string source, bool condition, string format, LogTarget logTarget, params object[] args) inline static
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
When assertion fails, logs an error using ErrorFormat(Frame, string, string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [8/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, string source, bool condition, string format, params object[] args) inline static
Asserts that condition is true during debugging and logs an ErrorFormat(Frame, string, string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
When assertion fails, logs an error using ErrorFormat(Frame, string, string, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [9/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, string source, Func< bool > assertCode, string format, LogTarget logTarget, params object[] args) inline static
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(Frame, string, string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [10/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Frame f, string source, Func< bool > assertCode, string format, params object[] args) inline static
Asserts that assertCode returns true during debugging and logs an ErrorFormat(Frame, string, string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(Frame, string, string, object[]) method.
See Assert Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [11/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Func< bool > assertCode, string format, LogTarget logTarget, params object[] args) inline
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [12/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (Func< bool > assertCode, string format, params object[] args) inline
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(string, object[]) method.
See Assert Methods Overview for more info.
Parameters
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [13/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (string source, bool condition, string format, LogTarget logTarget, params object[] args) inline static
Asserts that condition is true during debugging and logs an ErrorFormat(string, string, LogTarget, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
When assertion fails, logs an error using ErrorFormat(string, string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [14/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (string source, bool condition, string format, params object[] args) inline static
Asserts that condition is true during debugging and logs an ErrorFormat(string, string, object[]) log message if it is false.
This method is only compiled when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
When assertion fails, logs an error using ErrorFormat(string, string, object[]) method.
See Assert Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
condition Condition must be true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [15/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (string source, Func< bool > assertCode, string format, LogTarget logTarget, params object[] args) inline static
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, string, LogTarget, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(string, string, LogTarget, object[]) method.
See Assert Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
logTarget The target output console.
args The arguments for formatting the message string.
References ErrorFormat().
DevAssertFormat() [16/16]
void Battle.QSimulation.BattleDebugLogger.DevAssertFormat (string source, Func< bool > assertCode, string format, params object[] args) inline static
Asserts that assertCode returns true during debugging and logs an ErrorFormat(string, string, object[]) log message if it is false.
This method is only compiled and assertion code is ran when DEBUG_ASSERT_ENABLED_OVERRIDE or UNITY_EDITOR is defined.
Static Assert Methods
Runs assertion code which can be any complicated check.
When assertion code fails, logs an error using ErrorFormat(string, string, object[]) method.
See Assert Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
assertCode Assertion code must return true, otherwise logs an error.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References ErrorFormat().
Error() [1/4]
void Battle.QSimulation.BattleDebugLogger.Error (Frame f, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline
Logs the given message as an Error.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
message The message that is Logged.
logTarget The target output console.
References _instanceFormatUnity, _instanceSourceFormatOnScreen, and s_addLogToOnScreenConsoleFnRef.
Error() [2/4]
void Battle.QSimulation.BattleDebugLogger.Error (Frame f, string source, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline static
Logs the given message as an Error using the given Quantum frame f and source when formatting the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Warning Log message.
message The message that is Logged.
logTarget The target output console.
References s_addLogToOnScreenConsoleFnRef, StaticFormatUnity, and StaticSourceFormatOnScreen.
Error() [3/4]
void Battle.QSimulation.BattleDebugLogger.Error (string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline
Logs the given message as an Error.
Uses the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
message The message that is Logged.
logTarget The target output console.
References _instanceFormatUnityNoFrame, _instanceSourceFormatOnScreenNoFrame, and s_addLogToOnScreenConsoleFnRef.
Error() [4/4]
void Battle.QSimulation.BattleDebugLogger.Error (string source, string message, LogTarget logTarget = LogTarget::UnityConsole | LogTarget::OnScreenConsole) inline static
Logs the given message as an Error using the given source when formatting the Error Log message.
Output Error Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
message The message that is Logged.
logTarget The target output console.
References s_addLogToOnScreenConsoleFnRef, StaticFormatUnityNoFrame, and StaticSourceFormatOnScreenNoFrame.
Referenced by DevAssert(), DevAssert(), DevAssert(), DevAssert(), DevAssert(), DevAssert(), DevAssert(), DevAssert(), ErrorFormat(), ErrorFormat(), ErrorFormat(), ErrorFormat(), ErrorFormat(), ErrorFormat(), ErrorFormat(), and ErrorFormat().
ErrorFormat() [1/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (Frame f, string format, LogTarget logTarget, params object[] args) inline
Logs a formatted message based on the given format and args as an Error.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Error().
ErrorFormat() [2/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (Frame f, string format, params object[] args) inline
Logs a formatted message based on the given format and args as an Error.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message).
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Error().
ErrorFormat() [3/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (Frame f, string source, string format, LogTarget logTarget, params object[] args) inline static
Logs a formatted message based on the given format and args as an Error using the given Quantum frame f and source when formatting the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Error Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Error().
ErrorFormat() [4/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (Frame f, string source, string format, params object[] args) inline static
Logs a formatted message based on the given format and args as an Error using the given Quantum frame f and source when formatting the Error Log message.
Output Error Log message: [Battle] [(frame number)] [(source)] (formatted message).
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Error Log message.
source The name of the source used when formatting the Error Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Error().
ErrorFormat() [5/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (string format, LogTarget logTarget, params object[] args) inline
Logs a formatted message based on the given format and args as an Error.
Uses the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Error().
ErrorFormat() [6/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (string format, params object[] args) inline
Logs a formatted message based on the given format and args as an Error.
Uses the source given when creating a BattleDebugLogger instance to format the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message).
Log Methods
See Log Methods Overview for more info.
Parameters
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Error().
ErrorFormat() [7/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (string source, string format, LogTarget logTarget, params object[] args) inline static
Logs a formatted message based on the given format and args as an Error using the given source when formatting the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Error().
ErrorFormat() [8/8]
void Battle.QSimulation.BattleDebugLogger.ErrorFormat (string source, string format, params object[] args) inline static
Logs a formatted message based on the given format and args as an Error using the given source when formatting the Error Log message.
Output Error Log message: [Battle] [(source)] (formatted message).
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Error Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Error().
Referenced by DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), DevAssertFormat(), and Battle.QSimulation.Player.BattlePlayerClassBase< T >.GetClassData().
InitOnScreenConsoleLink()
void Battle.QSimulation.BattleDebugLogger.InitOnScreenConsoleLink (Action< LogType, string, string > addLogToOnScreenConsoleFnRef) inline static
Establishes link between BattleUiDebugConsoleHandler.
Parameters
addLogToOnScreenConsoleFnRef BattleUiDebugConsoleHandler.AddLog function reference.
References s_addLogToOnScreenConsoleFnRef.
Referenced by Battle.View.UI.BattleUiDebugConsoleHandler.Awake().
Log() [1/4]
void Battle.QSimulation.BattleDebugLogger.Log (Frame f, string message, LogTarget logTarget = LogTarget::UnityConsole) inline
Logs the given message .
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Log message.
message The message that is Logged.
logTarget The target output console.
References _instanceFormatUnity, _instanceSourceFormatOnScreen, and s_addLogToOnScreenConsoleFnRef.
Log() [2/4]
void Battle.QSimulation.BattleDebugLogger.Log (Frame f, string source, string message, LogTarget logTarget = LogTarget::UnityConsole) inline static
Logs the given message using the given Quantum frame f and source when formatting the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Log message.
source The name of the source used when formatting the Log message.
message The message that is Logged.
logTarget The target output console.
References s_addLogToOnScreenConsoleFnRef, StaticFormatUnity, and StaticSourceFormatOnScreen.
Log() [3/4]
void Battle.QSimulation.BattleDebugLogger.Log (string message, LogTarget logTarget = LogTarget::UnityConsole) inline
Logs the given message .
Uses the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
message The message that is Logged.
logTarget The target output console.
References _instanceFormatUnityNoFrame, _instanceSourceFormatOnScreenNoFrame, and s_addLogToOnScreenConsoleFnRef.
Log() [4/4]
void Battle.QSimulation.BattleDebugLogger.Log (string source, string message, LogTarget logTarget = LogTarget::UnityConsole) inline static
Logs the given message using the given source when formatting the Log message.
Output Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Log message.
message The message that is Logged.
logTarget The target output console.
References s_addLogToOnScreenConsoleFnRef, StaticFormatUnityNoFrame, and StaticSourceFormatOnScreenNoFrame.
Referenced by LogFormat(), LogFormat(), LogFormat(), LogFormat(), LogFormat(), LogFormat(), LogFormat(), and LogFormat().
LogFormat() [1/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (Frame f, string format, LogTarget logTarget, params object[] args) inline
Logs a formatted message based on the given format and args
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Log().
LogFormat() [2/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (Frame f, string format, params object[] args) inline
Logs a formatted message based on the given format and args
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(frame number)] [(source)] (formatted message).
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Log().
LogFormat() [3/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (Frame f, string source, string format, LogTarget logTarget, params object[] args) inline static
Logs a formatted message based on the given format and args using the given Quantum frame f and source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Log message.
source The name of the source used when formatting the Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Log().
LogFormat() [4/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (Frame f, string source, string format, params object[] args) inline static
Logs a formatted message based on the given format and args using the given Quantum frame f and source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message).
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Log message.
source The name of the source used when formatting the Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Log().
LogFormat() [5/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (string format, LogTarget logTarget, params object[] args) inline
Logs a formatted message based on the given format and args
Uses the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Log().
LogFormat() [6/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (string format, params object[] args) inline
Logs a formatted message based on the given format and args
Uses the source given when creating a BattleDebugLogger instance to format the Log message.
Output Log message: [Battle] [(source)] (formatted message).
Log Methods
See Log Methods Overview for more info.
Parameters
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Log().
LogFormat() [7/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (string source, string format, LogTarget logTarget, params object[] args) inline static
Logs a formatted message based on the given format and args using the given source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Log().
LogFormat() [8/8]
void Battle.QSimulation.BattleDebugLogger.LogFormat (string source, string format, params object[] args) inline static
Logs a formatted message based on the given format and args using the given source when formatting the Log message.
Output Log message: [Battle] [(source)] (formatted message).
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Log().
Referenced by Battle.View.SoulWall.BattleSoulWallViewController.OnActivate().
Warning() [1/4]
void Battle.QSimulation.BattleDebugLogger.Warning (Frame f, string message, LogTarget logTarget = LogTarget::UnityConsole) inline
Logs the given message as a Warning.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Warning Log message.
message The message that is Logged.
logTarget The target output console.
References _instanceFormatUnity, _instanceSourceFormatOnScreen, and s_addLogToOnScreenConsoleFnRef.
Warning() [2/4]
void Battle.QSimulation.BattleDebugLogger.Warning (Frame f, string source, string message, LogTarget logTarget = LogTarget::UnityConsole) inline static
Logs the given message as a Warning using the given Quantum frame f and source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Warning Log message.
source The name of the source used when formatting the Warning Log message.
message The message that is Logged.
logTarget The target output console.
References s_addLogToOnScreenConsoleFnRef, StaticFormatUnity, and StaticSourceFormatOnScreen.
Warning() [3/4]
void Battle.QSimulation.BattleDebugLogger.Warning (string message, LogTarget logTarget = LogTarget::UnityConsole) inline
Logs the given message as a Warning.
Uses the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
message The message that is Logged.
logTarget The target output console.
References _instanceFormatUnityNoFrame, _instanceSourceFormatOnScreenNoFrame, and s_addLogToOnScreenConsoleFnRef.
Warning() [4/4]
void Battle.QSimulation.BattleDebugLogger.Warning (string source, string message, LogTarget logTarget = LogTarget::UnityConsole) inline static
Logs the given message as a Warning using the given source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(source)] (message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Warning Log message.
message The message that is Logged.
logTarget The target output console.
References s_addLogToOnScreenConsoleFnRef, StaticFormatUnityNoFrame, and StaticSourceFormatOnScreenNoFrame.
Referenced by WarningFormat(), WarningFormat(), WarningFormat(), WarningFormat(), WarningFormat(), WarningFormat(), WarningFormat(), and WarningFormat().
WarningFormat() [1/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (Frame f, string format, LogTarget logTarget, params object[] args) inline
Logs a formatted message based on the given format and args as a Warning.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Warning Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Warning().
WarningFormat() [2/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (Frame f, string format, params object[] args) inline
Logs a formatted message based on the given format and args as a Warning.
Uses the given Quantum frame f and the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message).
Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Warning Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Warning().
WarningFormat() [3/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (Frame f, string source, string format, LogTarget logTarget, params object[] args) inline static
Logs a formatted message based on the given format and args as a Warning using the given Quantum frame f and source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Warning Log message.
source The name of the source used when formatting the Warning Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Warning().
WarningFormat() [4/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (Frame f, string source, string format, params object[] args) inline static
Logs a formatted message based on the given format and args as a Warning using the given Quantum frame f and source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(frame number)] [(source)] (formatted message).
Static Log Methods
See Log Methods Overview for more info.
Parameters
f The Quantum frame used when formatting the Warning Log message.
source The name of the source used when formatting the Warning Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Warning().
WarningFormat() [5/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (string format, LogTarget logTarget, params object[] args) inline
Logs a formatted message based on the given format and args as a Warning.
Uses the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Log Methods
See Log Methods Overview for more info.
Parameters
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Warning().
WarningFormat() [6/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (string format, params object[] args) inline
Logs a formatted message based on the given format and args as a Warning.
Uses the source given when creating a BattleDebugLogger instance to format the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message).
Log Methods
See Log Methods Overview for more info.
Parameters
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Warning().
WarningFormat() [7/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (string source, string format, LogTarget logTarget, params object[] args) inline static
Logs a formatted message based on the given format and args as a Warning using the given source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message)
Output console can be chosen by using logTarget .
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Warning Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
logTarget The target output console.
References Warning().
WarningFormat() [8/8]
void Battle.QSimulation.BattleDebugLogger.WarningFormat (string source, string format, params object[] args) inline static
Logs a formatted message based on the given format and args as a Warning using the given source when formatting the Warning Log message.
Output Warning Log message: [Battle] [(source)] (formatted message).
Static Log Methods
See Log Methods Overview for more info.
Parameters
source The name of the source used when formatting the Warning Log message.
format The message string to be Logged after formatting.
args The arguments for formatting the message string.
References Warning().
Member Data Documentation
_instanceFormatUnity
readonly string Battle.QSimulation.BattleDebugLogger._instanceFormatUnity private
Saved Log message format, set when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger(), Error(), Log(), and Warning().
_instanceFormatUnityNoFrame
readonly string Battle.QSimulation.BattleDebugLogger._instanceFormatUnityNoFrame private
Saved no Quantum frame Log message format, set when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger(), Error(), Log(), and Warning().
_instanceSourceFormatOnScreen
readonly string Battle.QSimulation.BattleDebugLogger._instanceSourceFormatOnScreen private
Saved on-screen Log message format, set when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger(), Error(), Log(), and Warning().
_instanceSourceFormatOnScreenNoFrame
readonly string Battle.QSimulation.BattleDebugLogger._instanceSourceFormatOnScreenNoFrame private
Saved no Quantum frame on-screen Log message format, set when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger(), Error(), Log(), and Warning().
InstanceFormatUnityNoFrameTemplate
const string Battle.QSimulation.BattleDebugLogger.InstanceFormatUnityNoFrameTemplate = "[Battle] [{0}] {{0}}" static private
Constant format template for Log messages used to create the no Quantum frame message format when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger().
InstanceFormatUnityTemplate
const string Battle.QSimulation.BattleDebugLogger.InstanceFormatUnityTemplate = "[Battle] [{{0:D6}}] [{0}] {{1}}" static private
Constant format template for Log messages used to create the message format when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger().
InstanceSourceFormatOnScreenNoFrameTemplate
const string Battle.QSimulation.BattleDebugLogger.InstanceSourceFormatOnScreenNoFrameTemplate = "[{0}]" static private
Constant format template for on-screen Log messages used to create the no Quantum frame message format when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger().
InstanceSourceFormatOnScreenTemplate
const string Battle.QSimulation.BattleDebugLogger.InstanceSourceFormatOnScreenTemplate = "[{{0:D6}}] [{0}]" static private
Constant format template for on-screen Log messages used to create the message format when creating a BattleDebugLogger instance.
Referenced by BattleDebugLogger().
s_addLogToOnScreenConsoleFnRef
Action<LogType, string, string> Battle.QSimulation.BattleDebugLogger.s_addLogToOnScreenConsoleFnRef static private
Function reference to BattleUiDebugConsoleHandler.AddLog.
Referenced by Error(), Error(), Error(), Error(), InitOnScreenConsoleLink(), Log(), Log(), Log(), Log(), Warning(), Warning(), Warning(), and Warning().
StaticFormatUnity
const string Battle.QSimulation.BattleDebugLogger.StaticFormatUnity = "[Battle] [{0:D6}] [{1}] {2}" static private
Constant format for Log messages when called through static methods.
Referenced by Error(), Log(), and Warning().
StaticFormatUnityNoFrame
const string Battle.QSimulation.BattleDebugLogger.StaticFormatUnityNoFrame = "[Battle] [{0}] {1}" static private
Constant format for Log messages when called through static methods with no Quantum frame given.
Referenced by Error(), Log(), and Warning().
StaticSourceFormatOnScreen
const string Battle.QSimulation.BattleDebugLogger.StaticSourceFormatOnScreen = "[{0:D6}] [{1}]" static private
Constant format for on-screen Log messages when called through static methods.
Referenced by Error(), Log(), and Warning().
StaticSourceFormatOnScreenNoFrame
const string Battle.QSimulation.BattleDebugLogger.StaticSourceFormatOnScreenNoFrame = "[{0}]" static private
Constant format for on-screen Log messages when called through static methods with no Quantum frame given.
Referenced by Error(), Log(), and Warning().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/BattleDebugLogger.cs