Battle: Battle.QSimulation.Projectile.BattleProjectileQSystem Class Reference
Battle.QSimulation.Projectile.BattleProjectileQSystem Class Reference
Projectile Quantum System游못 [Systems]
Handles projectile logic, including projectile's movements and reactions to collisionsignals.
Classes
struct Filter
Filter for filtering projectile entities.
Public Types
enum SpeedChange { None , Increment , Reset }
Defines how the projectile's speed should be updated.
Public Member Functions
override void Update (Frame f, ref Filter filter)
Quantum System Update method游못 gets called every frame.
Launches the projectile if it hasn't been launched yet, moves it if not held, updates its speed potential over time, and resets collision flags for the next frame.
Sets properties based on the Projectile spec.
unsafe void BattleOnGameOver (Frame f, BattleTeamNumber winningTeam)
Quantum System Signal method游못 that gets called when ISignalBattleOnGameOver is sent.
Sets the projectile to held state and teleports it out of the arena.
Static Public Member Functions
static bool IsCollisionFlagSet (Frame f, BattleProjectileQComponent *projectile, BattleProjectileCollisionFlags flag)
Checks if a specific collision flag is currently set for the projectile.
static void SetCollisionFlag (Frame f, BattleProjectileQComponent *projectile, BattleProjectileCollisionFlags flag)
Sets a specific collision flag for the current frame.
static void SetHeld (Frame f, BattleProjectileQComponent *projectile, bool isHeld)
Sets whether the projectile is currently held.
static void SetEmotion (Frame f, BattleProjectileQComponent *projectile, BattleEmotionState emotion)
Sets the emotion state of the projectile and triggers the corresponding event.
static void SetAttack (Frame f, BattleProjectileQComponent *projectile, FP attack)
Sets the attack value of the projectile and updates its glow strength.
static void UpdateVelocity (Frame f, BattleProjectileQComponent *projectile, FPVector2 direction, SpeedChange speedChange, bool passed=false)
Sets the direction of the projectile and adjusting its speed depending on the specified SpeedChange behavior.
static void HandleIntersection (Frame f, BattleProjectileQComponent *projectile, EntityRef projectileEntity, EntityRef otherEntity, FPVector2 normal, FP collisionMinOffset)
Handles the intersection of a projectile with another entity and corrects its position if necessary.
static void Init ()
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
static void OnProjectileCollision (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, void *data, BattleCollisionTriggerType collisionTriggerType)
Called by BattleCollisionQSystem. Handles the collision based on the specified collision trigger type, handling the collision differently based on what the projectile has hit.
The projectile will either reflect off of the arena border, set its emotion and bounce off a soul wall, or run checks on what it should do if it hits a player shield.
Ultimately sends the projectile in a new direction if it is appropriate to do so.
Static Private Member Functions
static EntityRef GetProjectileEntity (Frame f)
Private helper method to get projectile entity.
static void Launch (Frame f, BattleProjectileQComponent *projectile)
Launches the projectile from an unlaunched state, setting its initial values.
static bool ProjectileHitPlayerShield (Frame f, BattleProjectileQComponent *projectile, BattleCollisionQSystem.PlayerShieldCollisionData *shieldCollisionData, out FPVector2 normal)
This method checks if the shield hitbox and projectile are in states where they should collide.
Also sets the projectile to the love emotion state if the condition for that is met.
Static Private Attributes
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
Detailed Description
Projectile Quantum System游못 [Systems]
Handles projectile logic, including projectile's movements and reactions to collisionsignals.
This system:
Launches projectile when battle starts and updates its movements.
Handles projectile's collisionflags to ensure projectile doesn't hit more than one SoulWall segment at a time.
Contains logic for handling the projectile colliding with different entities.
Member Enumeration Documentation
SpeedChange
enum Battle.QSimulation.Projectile.BattleProjectileQSystem.SpeedChange
Defines how the projectile's speed should be updated.
Enumerator
None
Increment
Reset
Member Function Documentation
BattleOnGameOver()
unsafe void Battle.QSimulation.Projectile.BattleProjectileQSystem.BattleOnGameOver (Frame f, BattleTeamNumber winningTeam) inline
Quantum System Signal method游못 that gets called when ISignalBattleOnGameOver is sent.
Sets the projectile to held state and teleports it out of the arena.
Warning
This method should only be called via Quantum signal.
Parameters
f Current simulation frame.
winningTeam The BattleTeamNumber of the team that won.
Implements Quantum.ISignalBattleOnGameOver.
References GetProjectileEntity(), and SetHeld().
GetProjectileEntity()
EntityRef Battle.QSimulation.Projectile.BattleProjectileQSystem.GetProjectileEntity (Frame f) inline static private
Private helper method to get projectile entity.
Parameters
f Current simulation frame.
Returns
Returns projectile entity.
Referenced by BattleOnGameOver().
HandleIntersection()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.HandleIntersection (Frame f, BattleProjectileQComponent * projectile, EntityRef projectileEntity, EntityRef otherEntity, FPVector2 normal, FP collisionMinOffset) inline static
Handles the intersection of a projectile with another entity and corrects its position if necessary.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
projectileEntity The entity representing the projectile.
otherEntity The entity the projectile is intersecting with.
normal The collision normal of the intersection.
collisionMinOffset Minimum allowed offset to prevent the projectile from going inside the other entity.
References Quantum.BattleProjectileQComponent.Radius.
Referenced by OnProjectileCollision(), Battle.QSimulation.Player.BattlePlayerClassConfluent.OnProjectileHitPlayerShield(), and Battle.QSimulation.Player.BattlePlayerClassProjector.OnProjectileHitPlayerShield().
Init()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.Init () inline static
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
References Battle.QSimulation.BattleDebugLogger.Create(), and s_debugLogger.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
IsCollisionFlagSet()
bool Battle.QSimulation.Projectile.BattleProjectileQSystem.IsCollisionFlagSet (Frame f, BattleProjectileQComponent * projectile, BattleProjectileCollisionFlags flag) static
Checks if a specific collision flag is currently set for the projectile.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
flag Collision flag to check.
Returns
True if the flag is set; otherwise, false.
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
Launch()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.Launch (Frame f, BattleProjectileQComponent * projectile) inline static private
Launches the projectile from an unlaunched state, setting its initial values.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
References Battle.QSimulation.Projectile.BattleProjectileQSpec.AttackMax, Quantum.BattleProjectileQComponent.AttackMax, Quantum.BattleProjectileQComponent.CollisionFlags, Quantum.BattleProjectileQComponent.Direction, Battle.QSimulation.Game.BattleParameters.GetProjectileInitialEmotion(), Battle.QSimulation.Game.BattleQConfig.GetProjectileSpec(), Quantum.BattleProjectileQComponent.IsLaunched, Battle.QSimulation.Projectile.BattleProjectileQSpec.ProjectileInitialSpeed, s_debugLogger, SetAttack(), SetEmotion(), SetHeld(), Quantum.BattleProjectileQComponent.Speed, Quantum.BattleProjectileQComponent.SpeedBase, Battle.QSimulation.Projectile.BattleProjectileQSpec.SpeedIncrement, Quantum.BattleProjectileQComponent.SpeedIncrement, Battle.QSimulation.Projectile.BattleProjectileQSpec.SpeedMax, and Quantum.BattleProjectileQComponent.SpeedMax.
Referenced by Update().
OnProjectileCollision()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.OnProjectileCollision (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, void * data, BattleCollisionTriggerType collisionTriggerType) inline static
Called by BattleCollisionQSystem. Handles the collision based on the specified collision trigger type, handling the collision differently based on what the projectile has hit.
The projectile will either reflect off of the arena border, set its emotion and bounce off a soul wall, or run checks on what it should do if it hits a player shield.
Ultimately sends the projectile in a new direction if it is appropriate to do so.
Parameters
f Current simulation frame.
projectileCollisionData Collision data related to the projectile.
data Collision data related to the other entity.
collisionTriggerType The collision type of the collision, informing what the projectile has hit.
References Quantum.BattleArenaBorderQComponent.CollisionMinOffset, Quantum.BattlePlayerHitboxQComponent.CollisionMinOffset, Quantum.BattleSoulWallQComponent.CollisionMinOffset, Quantum.BattlePlayerHitboxQComponent.CollisionType, Quantum.BattleProjectileQComponent.Direction, Quantum.BattleProjectileQComponent.EmotionBase, Quantum.BattleProjectileQComponent.EmotionCurrent, HandleIntersection(), Quantum.BattleArenaBorderQComponent.Normal, Quantum.BattlePlayerHitboxQComponent.Normal, Quantum.BattleSoulWallQComponent.Normal, ProjectileHitPlayerShield(), SetCollisionFlag(), SetEmotion(), and UpdateVelocity().
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
ProjectileHitPlayerShield()
bool Battle.QSimulation.Projectile.BattleProjectileQSystem.ProjectileHitPlayerShield (Frame f, BattleProjectileQComponent * projectile, BattleCollisionQSystem.PlayerShieldCollisionData * shieldCollisionData, out FPVector2 normal) inline static private
This method checks if the shield hitbox and projectile are in states where they should collide.
Also sets the projectile to the love emotion state if the condition for that is met.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
shieldCollisionData Collision data related to the shield.
normal The direction in which the projectile should be sent.
References Quantum.BattleGridPosition.Col, Quantum.BattleProjectileQComponent.EmotionCurrent, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.PlayState, s_debugLogger, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SelectedCharacterEntity, SetEmotion(), Quantum.BattlePlayerDataQComponent.Slot, Quantum.TeamAlpha, Quantum.BattlePlayerDataQComponent.TeamNumber, and Battle.QSimulation.Game.BattleGridManager.WorldPositionToGridPosition().
Referenced by OnProjectileCollision().
SetAttack()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.SetAttack (Frame f, BattleProjectileQComponent * projectile, FP attack) inline static
Sets the attack value of the projectile and updates its glow strength.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
attack The new attack value to assign to the projectile.
References Quantum.BattleProjectileQComponent.Attack, and Quantum.BattleProjectileQComponent.AttackMax.
Referenced by Launch(), and Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerShield().
SetCollisionFlag()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.SetCollisionFlag (Frame f, BattleProjectileQComponent * projectile, BattleProjectileCollisionFlags flag) inline static
Sets a specific collision flag for the current frame.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
flag Collision flag to set.
References Quantum.BattleProjectileQComponent.CollisionFlags.
Referenced by OnProjectileCollision(), Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerCharacter(), Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerShield(), and Battle.QSimulation.SoulWall.BattleSoulWallQSystem.OnProjectileHitSoulWall().
SetEmotion()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.SetEmotion (Frame f, BattleProjectileQComponent * projectile, BattleEmotionState emotion) inline static
Sets the emotion state of the projectile and triggers the corresponding event.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
emotion The new emotion state to assign to the projectile.
References Quantum.BattleProjectileQComponent.EmotionBase, and Quantum.BattleProjectileQComponent.EmotionCurrent.
Referenced by Launch(), OnProjectileCollision(), and ProjectileHitPlayerShield().
SetHeld()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.SetHeld (Frame f, BattleProjectileQComponent * projectile, bool isHeld) inline static
Sets whether the projectile is currently held.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
isHeld True/False : held / not held.
References Quantum.BattleProjectileQComponent.IsHeld.
Referenced by BattleOnGameOver(), Launch(), Battle.QSimulation.Player.BattlePlayerClassProjector.OnProjectileHitPlayerShield(), and Battle.QSimulation.Player.BattlePlayerClassProjector.OnUpdate().
Update()
override void Battle.QSimulation.Projectile.BattleProjectileQSystem.Update (Frame f, ref Filter filter) inline
Quantum System Update method游못 gets called every frame.
Launches the projectile if it hasn't been launched yet, moves it if not held, updates its speed potential over time, and resets collision flags for the next frame.
Sets properties based on the Projectile spec.
Warning
This method should only be called by Quantum.
Parameters
f Current simulation frame.
filter Reference to Quantum Filter游못.
References Quantum.BattleProjectileQComponent.CollisionFlags, Quantum.BattleProjectileQComponent.Direction, Quantum.BattleProjectileQComponent.IsHeld, Quantum.BattleProjectileQComponent.IsLaunched, Launch(), Quantum.BattleProjectileQComponent.Position, and Quantum.BattleProjectileQComponent.Speed.
UpdateVelocity()
void Battle.QSimulation.Projectile.BattleProjectileQSystem.UpdateVelocity (Frame f, BattleProjectileQComponent * projectile, FPVector2 direction, SpeedChange speedChange, bool passed = false) inline static
Sets the direction of the projectile and adjusting its speed depending on the specified SpeedChange behavior.
Parameters
f Current simulation frame.
projectile Pointer to the projectile component.
direction The new direction for the projectile.
speedChange Determines how the projectile's speed should be updated.
passed Checking if player has passed the projectile.
References Quantum.BattleProjectileQComponent.Direction, Quantum.BattleProjectileQComponent.IsPassed, Quantum.BattleProjectileQComponent.Speed, Quantum.BattleProjectileQComponent.SpeedBase, Quantum.BattleProjectileQComponent.SpeedIncrement, and Quantum.BattleProjectileQComponent.SpeedMax.
Referenced by OnProjectileCollision(), Battle.QSimulation.Player.BattlePlayerClassConfluent.OnProjectileHitPlayerShield(), Battle.QSimulation.Player.BattlePlayerClassProjector.OnProjectileHitPlayerShield(), and Battle.QSimulation.Player.BattlePlayerClassProjector.OnUpdate().
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.QSimulation.Projectile.BattleProjectileQSystem.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by Init(), Launch(), and ProjectileHitPlayerShield().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Projectile/BattleProjectileQSystem.cs