Battle: Quantum.Prototypes.GridPositionPrototype Class Reference
Quantum.Prototypes.GridPositionPrototype Class Reference
Public Member Functions
void Materialize (Frame frame, ref Quantum.GridPosition result, in PrototypeMaterializationContext context=default)
Public Attributes
Int32 Row
Int32 Col
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.GridPosition result, in PrototypeMaterializationContext context)
Member Function Documentation
Materialize()
void Quantum.Prototypes.GridPositionPrototype.Materialize (Frame frame, ref Quantum.GridPosition result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by Quantum.Prototypes.InputPrototype.Materialize().
MaterializeUser()
partial void Quantum.Prototypes.GridPositionPrototype.MaterializeUser (Frame frame, ref Quantum.GridPosition result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
Col
Int32 Quantum.Prototypes.GridPositionPrototype.Col
Row
Int32 Quantum.Prototypes.GridPositionPrototype.Row
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs