Battle: Quantum.Prototypes.PlayerDataTemplatePrototype Class Reference
Quantum.Prototypes.PlayerDataTemplatePrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.PlayerDataTemplate result, in PrototypeMaterializationContext context=default)
Public Attributes
Quantum.Prototypes.PlayerHitboxTemplatePrototype[] HitboxListShield = {}
Quantum.Prototypes.PlayerHitboxTemplatePrototype[] HitboxListCharacter = {}
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.PlayerDataTemplate result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.PlayerDataTemplatePrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.PlayerDataTemplatePrototype.Materialize (Frame frame, ref Quantum.PlayerDataTemplate result, in PrototypeMaterializationContext context = default) inline
References HitboxListCharacter, HitboxListShield, and MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.PlayerDataTemplatePrototype.MaterializeUser (Frame frame, ref Quantum.PlayerDataTemplate result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
HitboxListCharacter
Quantum.Prototypes.PlayerHitboxTemplatePrototype [] Quantum.Prototypes.PlayerDataTemplatePrototype.HitboxListCharacter = {}
Referenced by Materialize().
HitboxListShield
Quantum.Prototypes.PlayerHitboxTemplatePrototype [] Quantum.Prototypes.PlayerDataTemplatePrototype.HitboxListShield = {}
Referenced by Materialize().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs