Battle: Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement Class Reference
Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement Class Reference
Multi orientation BattleUiMovableElement.
Handles setting the Battle Ui multi orientation element position and orientation and flipping it.
Public Types
enum OrientationType { None = -1 , Horizontal = 0 , Vertical = 1 }
Multi orientation element's possible orientations.
Public Member Functions
GameObject GetActiveGameObject ()
Get the currently active orientation GameObject游못.
override void SetData (BattleUiMovableElementData data)
Set BattleUiMovableElementData to this Ui multi orientation element.
override BattleUiMovableElementData GetData ()
Get the data from this Ui multi orientation element.
Properties
OrientationType Orientation [get]
Public getter for _orientation.
GameObject HorizontalConfiguration [get]
Public getter for _horizontalConfiguration.
GameObject VerticalConfiguration [get]
Public getter for _verticalConfiguration.
bool IsFlippedHorizontally [get]
Public getter for _isFlippedHorizontally.
bool IsFlippedVertically [get]
Public getter for _isFlippedVertically.
float HorizontalAspectRatio [get]
Public getter for _horizontalAspectRatio.
float VerticalAspectRatio [get]
Public getter for _verticalAspectRatio.
bool IsHorizontal [get]
Is the multi orientation element currently horizontal.
Properties inherited from Altzone.Scripts.BattleUiShared.BattleUiMovableElement
RectTransform RectTransformComponent [get]
Public getter for _rectTransform.
BattleUiElementType UiElementType [get, private set]
Battle Ui element's BattleUiElementType.
Private Member Functions
void SetOrientation (BattleUiMovableElementData data)
Set orientation from BattleUiMovableData.
void FlipChildrenHorizontally (Transform parent)
Flip children's anchors horizontally from side to the other side, in the x axis.
void FlipChildrenVertically (Transform parent)
Flip children's anchors vertically from side to the other side, in the y axis.
float GetFlippedAnchor (float anchorValue)
Calculates a flipped anchor value for the given anchor value.
Private Attributes
OrientationType _orientation = OrientationType.Horizontal
Multi orientation element's current orientation.
bool _isFlippedHorizontally = false
Is multi orientation element flipped horizontally.
bool _isFlippedVertically = false
Is multi orientation element flipped vertically.
SerializeField variables
SerializeFields游못 are serialized variables exposed to the Unity editor.
GameObject _horizontalConfiguration
[SerializeField] Reference to the horizontal orientation's parent GameObject游못.
float _horizontalAspectRatio
[SerializeField] Multi orientation element's aspect ratio for horizontal orientation.
GameObject _verticalConfiguration
[SerializeField] Reference to the vertical orientation's parent GameObject游못.
float _verticalAspectRatio
[SerializeField] Multi orientation element's aspect ratio for vertical orientation.
Additional Inherited Members
Protected Member Functions inherited from Altzone.Scripts.BattleUiShared.BattleUiMovableElement
void Awake ()
Private Awake游못 method which initializes _rectTransform, _images and _texts.
void SetTransparency ()
Sets Battle Ui element's transparency.
Protected Attributes inherited from Altzone.Scripts.BattleUiShared.BattleUiMovableElement
RectTransform _rectTransform
Reference to the Battle Ui element's RectTransform游못 component.
List< Image > _images
List of Battle Ui element's Image游못 component references.
List< TMP_Text > _texts
List of Battle Ui element's TMP_Text游못 component references.
int _currentTransparency = 0
Battle Ui element's current transparency.
Detailed Description
Multi orientation BattleUiMovableElement.
Handles setting the Battle Ui multi orientation element position and orientation and flipping it.
Member Enumeration Documentation
OrientationType
enum Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.OrientationType
Multi orientation element's possible orientations.
Enumerator
None
Horizontal
Vertical
Member Function Documentation
FlipChildrenHorizontally()
void Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.FlipChildrenHorizontally (Transform parent) inline private
Flip children's anchors horizontally from side to the other side, in the x axis.
Parameters
parent The parent Transform游못.
References FlipChildrenHorizontally(), and GetFlippedAnchor().
Referenced by FlipChildrenHorizontally(), and SetOrientation().
FlipChildrenVertically()
void Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.FlipChildrenVertically (Transform parent) inline private
Flip children's anchors vertically from side to the other side, in the y axis.
Parameters
parent The parent Transform游못.
References FlipChildrenVertically(), and GetFlippedAnchor().
Referenced by FlipChildrenVertically(), and SetOrientation().
GetActiveGameObject()
GameObject Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.GetActiveGameObject () inline
Get the currently active orientation GameObject游못.
Returns
Horizontal or vertical orientation GameObject游못.
References _horizontalConfiguration, _verticalConfiguration, and IsHorizontal.
Referenced by Battle.View.UI.BattleUiPlayerInfoHandler.SetInfo().
GetData()
override BattleUiMovableElementData Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.GetData () inline virtual
Get the data from this Ui multi orientation element.
Returns
Returns BattleUiMovableElementData serializable object. Null if couldn't get valid data.
Reimplemented from Altzone.Scripts.BattleUiShared.BattleUiMovableElement.
References Altzone.Scripts.BattleUiShared.BattleUiMovableElement._currentTransparency, _orientation, Altzone.Scripts.BattleUiShared.BattleUiMovableElement._rectTransform, IsFlippedHorizontally, IsFlippedVertically, and Altzone.Scripts.BattleUiShared.BattleUiMovableElement.UiElementType.
GetFlippedAnchor()
float Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.GetFlippedAnchor (float anchorValue) inline private
Calculates a flipped anchor value for the given anchor value.
Parameters
anchorValue The anchor value to be flipped.
Returns
Flipped anchor as float.
Referenced by FlipChildrenHorizontally(), and FlipChildrenVertically().
SetData()
override void Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.SetData (BattleUiMovableElementData data) inline virtual
Set BattleUiMovableElementData to this Ui multi orientation element.
Parameters
data The data which to set to this Ui element.
Reimplemented from Altzone.Scripts.BattleUiShared.BattleUiMovableElement.
References SetOrientation().
Referenced by Battle.View.UI.BattleUiPlayerInfoHandler.SetInfo().
SetOrientation()
void Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.SetOrientation (BattleUiMovableElementData data) inline private
Set orientation from BattleUiMovableData.
Parameters
data The BattleUiMovableData which contains the new orientation.
References _horizontalConfiguration, _isFlippedHorizontally, _isFlippedVertically, _orientation, _verticalConfiguration, FlipChildrenHorizontally(), FlipChildrenVertically(), Altzone.Scripts.BattleUiShared.BattleUiMovableElementData.IsFlippedHorizontally, Altzone.Scripts.BattleUiShared.BattleUiMovableElementData.IsFlippedVertically, IsHorizontal, and Altzone.Scripts.BattleUiShared.BattleUiMovableElementData.Orientation.
Referenced by SetData().
Member Data Documentation
_horizontalAspectRatio
float Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement._horizontalAspectRatio private
[SerializeField] Multi orientation element's aspect ratio for horizontal orientation.
BattleUiMultiOrientationElement-SerializeFields
_horizontalConfiguration
GameObject Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement._horizontalConfiguration private
[SerializeField] Reference to the horizontal orientation's parent GameObject游못.
BattleUiMultiOrientationElement-SerializeFields
Referenced by GetActiveGameObject(), and SetOrientation().
_isFlippedHorizontally
bool Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement._isFlippedHorizontally = false private
Is multi orientation element flipped horizontally.
Referenced by SetOrientation().
_isFlippedVertically
bool Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement._isFlippedVertically = false private
Is multi orientation element flipped vertically.
Referenced by SetOrientation().
_orientation
OrientationType Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement._orientation = OrientationType.Horizontal private
Multi orientation element's current orientation.
Referenced by GetData(), and SetOrientation().
_verticalAspectRatio
float Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement._verticalAspectRatio private
[SerializeField] Multi orientation element's aspect ratio for vertical orientation.
BattleUiMultiOrientationElement-SerializeFields
_verticalConfiguration
GameObject Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement._verticalConfiguration private
[SerializeField] Reference to the vertical orientation's parent GameObject游못.
BattleUiMultiOrientationElement-SerializeFields
Referenced by GetActiveGameObject(), and SetOrientation().
Property Documentation
HorizontalAspectRatio
float Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.HorizontalAspectRatio get
Public getter for _horizontalAspectRatio.
Multi orientation element's aspect ratio for horizontal orientation.
HorizontalConfiguration
GameObject Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.HorizontalConfiguration get
Public getter for _horizontalConfiguration.
Reference to the horizontal orientation's parent GameObject游못.
IsFlippedHorizontally
bool Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.IsFlippedHorizontally get
Public getter for _isFlippedHorizontally.
Is multi orientation element flipped horizontally.
Referenced by GetData().
IsFlippedVertically
bool Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.IsFlippedVertically get
Public getter for _isFlippedVertically.
Is multi orientation element flipped vertically.
Referenced by GetData().
IsHorizontal
bool Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.IsHorizontal get
Is the multi orientation element currently horizontal.
Referenced by GetActiveGameObject(), and SetOrientation().
Orientation
OrientationType Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.Orientation get
Public getter for _orientation.
Multi orientation element's current orientation.
VerticalAspectRatio
float Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.VerticalAspectRatio get
Public getter for _verticalAspectRatio.
Multi orientation element's aspect ratio for vertical orientation.
VerticalConfiguration
GameObject Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.VerticalConfiguration get
Public getter for _verticalConfiguration.
Reference to the vertical orientation's parent GameObject游못.
The documentation for this class was generated from the following file:
Altzone/Assets/Altzone/Scripts/BattleUiShared/BattleUiMultiOrientationElement.cs