Battle: Battle.QSimulation.Game.BattleGameControlQSystem Class Reference
Battle.QSimulation.Game.BattleGameControlQSystem Class Reference
Game control Quantum System游못 [Systems]
Controls the overall game flow in Quantum simulation.
Public Member Functions
override void OnInit (Frame f)
Quantum System OnInit method gets called when the system is initialized.
Initializes the arena, player system, and sets the game session as initialized.
void OnPlayerAdded (Frame f, PlayerRef playerRef, bool firstTime)
Quantum System Signal method游못 that gets called when ISignalOnPlayerAdded is sent.
Called when a player is added for the first time. Registers the player in BattlePlayerManager.
void OnPlayerDisconnected (Frame f, PlayerRef playerRef)
override void Update (Frame f)
Quantum System Update method gets called every frame.
Controls state transitions of the game session per frame. Manages countdowns and progression to 'Playing'.
Static Public Member Functions
static void OnGameOver (Frame f, BattleTeamNumber winningTeam)
Called when the game ends. Updates the game session state and calls the BattleViewGameOver Event and BattleOnGameOver Signal.
Static Private Member Functions
static void CreateMap (Frame f)
Sets up the game map during the 'CreateMap' game state. That includes SoulWalls and players. Other parts of the map don't need setup.
Private Attributes
BattleDebugLogger _debugLogger
This classes BattleDebugLogger instance.
Detailed Description
Game control Quantum System游못 [Systems]
Controls the overall game flow in Quantum simulation.
Initializes BattleGridManager and BattlePlayerManager.
Registers players to BattlePlayerManager when they connect.
Controls game state transitions from initialization to active gameplay.
Member Function Documentation
CreateMap()
void Battle.QSimulation.Game.BattleGameControlQSystem.CreateMap (Frame f) inline static private
Sets up the game map during the 'CreateMap' game state. That includes SoulWalls and players. Other parts of the map don't need setup.
Parameters
f Current simulation frame.
References Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateSoulWalls(), Battle.QSimulation.Game.BattleQConfig.GetArenaSpec(), Battle.QSimulation.Game.BattleQConfig.GetSoulWallSpec(), and Battle.QSimulation.Player.BattlePlayerQSystem.SpawnPlayers().
Referenced by Update().
OnGameOver()
void Battle.QSimulation.Game.BattleGameControlQSystem.OnGameOver (Frame f, BattleTeamNumber winningTeam) inline static
Called when the game ends. Updates the game session state and calls the BattleViewGameOver Event and BattleOnGameOver Signal.
Parameters
f Current simulation frame.
winningTeam The team that won the match.
References Quantum.BattleGameSessionQSingleton.GameTimeSec, and Quantum.BattleGameSessionQSingleton.State.
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.HandleGiveUpLogic(), and Battle.QSimulation.Goal.BattleGoalQSystem.OnProjectileHitGoal().
OnInit()
override void Battle.QSimulation.Game.BattleGameControlQSystem.OnInit (Frame f) inline
Quantum System OnInit method gets called when the system is initialized.
Initializes the arena, player system, and sets the game session as initialized.
Warning
This method should only be called by Quantum.
Parameters
f Current simulation frame.
References _debugLogger, Battle.QSimulation.BattleDebugLogger.Create(), Quantum.BattleGameSessionQSingleton.GameInitialized, Quantum.BattleGameSessionQSingleton.GameTimeSec, Battle.QSimulation.Game.BattleQConfig.GetArenaSpec(), Battle.QSimulation.Game.BattleCollisionQSystem.Init(), Battle.QSimulation.Game.BattleGridManager.Init(), Battle.QSimulation.Goal.BattleGoalQSystem.Init(), Battle.QSimulation.Player.BattlePlayerClassManager.Init(), Battle.QSimulation.Player.BattlePlayerManager.Init(), Battle.QSimulation.Player.BattlePlayerMovementController.Init(), Battle.QSimulation.Player.BattlePlayerQSystem.Init(), Battle.QSimulation.Projectile.BattleProjectileQSystem.Init(), and Battle.QSimulation.SoulWall.BattleSoulWallQSystem.Init().
OnPlayerAdded()
void Battle.QSimulation.Game.BattleGameControlQSystem.OnPlayerAdded (Frame f, PlayerRef playerRef, bool firstTime) inline
Quantum System Signal method游못 that gets called when ISignalOnPlayerAdded is sent.
Called when a player is added for the first time. Registers the player in BattlePlayerManager.
Warning
This method should only be called via Quantum signal.
Parameters
f Current simulation frame.
playerRef Reference to the player.
firstTime True if this is the first join.
References Battle.QSimulation.Player.BattlePlayerManager.RegisterPlayer().
OnPlayerDisconnected()
void Battle.QSimulation.Game.BattleGameControlQSystem.OnPlayerDisconnected (Frame f, PlayerRef playerRef) inline
References Battle.QSimulation.Player.BattlePlayerManager.MarkAbandoned(), and Quantum.BattleGameSessionQSingleton.State.
Update()
override void Battle.QSimulation.Game.BattleGameControlQSystem.Update (Frame f) inline
Quantum System Update method gets called every frame.
Controls state transitions of the game session per frame. Manages countdowns and progression to 'Playing'.
Warning
This method should only be called by Quantum.
Parameters
f Current simulation frame.
References CreateMap(), Quantum.BattleGameSessionQSingleton.GameInitialized, Quantum.BattleGameSessionQSingleton.GameTimeSec, Battle.QSimulation.Game.BattleParameters.GetPlayerNames(), Battle.QSimulation.Player.BattlePlayerManager.IsAllPlayersRegistered(), Quantum.BattleGameSessionQSingleton.LoadDelaySec, Quantum.BattleWaitForPlayersData.PlayerNames, Quantum.BattleGameSessionQSingleton.State, and Quantum.BattleGameSessionQSingleton.TimeUntilStartSec.
Member Data Documentation
_debugLogger
BattleDebugLogger Battle.QSimulation.Game.BattleGameControlQSystem._debugLogger private
This classes BattleDebugLogger instance.
Referenced by OnInit().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleGameControlQSystem.cs