Battle: Quantum.Prototypes.ProjectileSpawnerPrototype Class Reference
Quantum.Prototypes.ProjectileSpawnerPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.ProjectileSpawner result, in PrototypeMaterializationContext context=default)
Public Attributes
QBoolean HasSpawned
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.ProjectileSpawner result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.ProjectileSpawnerPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.ProjectileSpawnerPrototype.Materialize (Frame frame, ref Quantum.ProjectileSpawner result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.ProjectileSpawnerPrototype.MaterializeUser (Frame frame, ref Quantum.ProjectileSpawner result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
HasSpawned
QBoolean Quantum.Prototypes.ProjectileSpawnerPrototype.HasSpawned
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs