Battle: Quantum.Prototypes.BattlePlayerStatsPrototype Class Reference
Quantum.Prototypes.BattlePlayerStatsPrototype Class Reference
Public Member Functions
void Materialize (Frame frame, ref Quantum.BattlePlayerStats result, in PrototypeMaterializationContext context=default)
Public Attributes
FP Hp
FP Speed
FP CharacterSize
FP Attack
FP Defence
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattlePlayerStats result, in PrototypeMaterializationContext context)
Member Function Documentation
Materialize()
void Quantum.Prototypes.BattlePlayerStatsPrototype.Materialize (Frame frame, ref Quantum.BattlePlayerStats result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by Quantum.Prototypes.BattlePlayerDataQComponentPrototype.Materialize().
MaterializeUser()
partial void Quantum.Prototypes.BattlePlayerStatsPrototype.MaterializeUser (Frame frame, ref Quantum.BattlePlayerStats result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
Attack
FP Quantum.Prototypes.BattlePlayerStatsPrototype.Attack
CharacterSize
FP Quantum.Prototypes.BattlePlayerStatsPrototype.CharacterSize
Defence
FP Quantum.Prototypes.BattlePlayerStatsPrototype.Defence
Hp
FP Quantum.Prototypes.BattlePlayerStatsPrototype.Hp
Speed
FP Quantum.Prototypes.BattlePlayerStatsPrototype.Speed
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs