Battle: Quantum.PlayerMovementSystem Class Reference
Quantum.PlayerMovementSystem Class Reference
Classes
struct Filter
Public Member Functions
override void Update (Frame f, ref Filter filter)
Static Public Member Functions
static void MoveTowards (Frame f, PlayerData *playerData, Transform2D *transform, FPVector2 position, FP maxDelta)
static void Rotate (Frame f, PlayerData *playerData, Transform2D *transform, FP radians)
static void Teleport (Frame f, PlayerData *playerData, Transform2D *transform, FPVector2 position, FP rotation)
Private Member Functions
void UpdatePlayerMovement (Frame f, ref Filter filter, Input *input)
Static Private Member Functions
static void MoveTowardsNoHitboxUpdate (Frame f, Transform2D *transform, FPVector2 position, FP maxDelta)
static void RotateNoHitboxUpdate (Frame f, Transform2D *transform, FP radians)
static void TeleportNoHitboxUpdate (Frame f, Transform2D *transform, FPVector2 position, FP rotation)
static FPVector2 CalculateHitboxPosition (FPVector2 position, FP rotation, FPVector2 offset)
static void MoveHitbox (Frame f, PlayerData *playerData, Transform2D *transform)
static void TeleportHitbox (Frame f, PlayerData *playerData, Transform2D *transform)
Member Function Documentation
CalculateHitboxPosition()
static FPVector2 Quantum.PlayerMovementSystem.CalculateHitboxPosition (FPVector2 position, FP rotation, FPVector2 offset) static private
Referenced by MoveHitbox(), and TeleportHitbox().
MoveHitbox()
static void Quantum.PlayerMovementSystem.MoveHitbox (Frame f, PlayerData * playerData, Transform2D * transform) inline static private
References CalculateHitboxPosition(), Quantum.PlayerHitboxLink.Entity, Quantum.PlayerData.HitboxListAll, and Quantum.PlayerHitboxLink.Position.
Referenced by MoveTowards(), Rotate(), and UpdatePlayerMovement().
MoveTowards()
static void Quantum.PlayerMovementSystem.MoveTowards (Frame f, PlayerData * playerData, Transform2D * transform, FPVector2 position, FP maxDelta) inline static
References MoveHitbox(), and MoveTowardsNoHitboxUpdate().
MoveTowardsNoHitboxUpdate()
static void Quantum.PlayerMovementSystem.MoveTowardsNoHitboxUpdate (Frame f, Transform2D * transform, FPVector2 position, FP maxDelta) inline static private
Referenced by MoveTowards(), and UpdatePlayerMovement().
Rotate()
static void Quantum.PlayerMovementSystem.Rotate (Frame f, PlayerData * playerData, Transform2D * transform, FP radians) inline static
References MoveHitbox(), and RotateNoHitboxUpdate().
RotateNoHitboxUpdate()
static void Quantum.PlayerMovementSystem.RotateNoHitboxUpdate (Frame f, Transform2D * transform, FP radians) inline static private
Referenced by Rotate(), and UpdatePlayerMovement().
Teleport()
static void Quantum.PlayerMovementSystem.Teleport (Frame f, PlayerData * playerData, Transform2D * transform, FPVector2 position, FP rotation) inline static
References TeleportHitbox(), and TeleportNoHitboxUpdate().
Referenced by Quantum.PlayerManager.DespawnPlayer(), Quantum.PlayerManager.InitPlayer(), and Quantum.PlayerManager.SpawnPlayer().
TeleportHitbox()
static void Quantum.PlayerMovementSystem.TeleportHitbox (Frame f, PlayerData * playerData, Transform2D * transform) inline static private
References CalculateHitboxPosition(), Quantum.PlayerHitboxLink.Entity, Quantum.PlayerData.HitboxListAll, and Quantum.PlayerHitboxLink.Position.
Referenced by Teleport().
TeleportNoHitboxUpdate()
static void Quantum.PlayerMovementSystem.TeleportNoHitboxUpdate (Frame f, Transform2D * transform, FPVector2 position, FP rotation) inline static private
Referenced by Teleport().
Update()
override void Quantum.PlayerMovementSystem.Update (Frame f, ref Filter filter) inline
References Quantum.Frame.GetPlayerInput(), and UpdatePlayerMovement().
UpdatePlayerMovement()
void Quantum.PlayerMovementSystem.UpdatePlayerMovement (Frame f, ref Filter filter, Input * input) inline private
References Quantum.GridManager.GridPositionToWorldPosition(), Quantum.Input.MouseClick, MoveHitbox(), Quantum.Input.MovementPosition, MoveTowardsNoHitboxUpdate(), Quantum.Input.RotateMotion, RotateNoHitboxUpdate(), Quantum.PlayerData.RotationBase, Quantum.Input.RotationDirection, Quantum.PlayerData.RotationOffset, Quantum.PlayerData.StatSpeed, Quantum.PlayerData.TargetPosition, and Quantum.PlayerData.TeamNumber.
Referenced by Update().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Scripts/Player/PlayerMovementSystem.cs