Battle: Quantum.Prototypes.GoalPrototype Class Reference
Quantum.Prototypes.GoalPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.Goal result, in PrototypeMaterializationContext context=default)
Public Attributes
AssetRef< GoalConfig > goalConfig
QBoolean hasTriggered
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.Goal result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.GoalPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.GoalPrototype.Materialize (Frame frame, ref Quantum.Goal result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.GoalPrototype.MaterializeUser (Frame frame, ref Quantum.Goal result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
goalConfig
AssetRef<GoalConfig> Quantum.Prototypes.GoalPrototype.goalConfig
hasTriggered
QBoolean Quantum.Prototypes.GoalPrototype.hasTriggered
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs