Battle: Quantum.Prototypes.BattleDiamondDataQComponentPrototype Class Reference
Quantum.Prototypes.BattleDiamondDataQComponentPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattleDiamondDataQComponent result, in PrototypeMaterializationContext context=default)
Public Attributes
Quantum.Prototypes.FrameTimerPrototype LifetimeTimer
QBoolean IsTraveling
FP TravelSpeed
FPVector2 TravelDirection
FPVector2 StartPosition
FP TargetDistance
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleDiamondDataQComponent result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattleDiamondDataQComponentPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattleDiamondDataQComponentPrototype.Materialize (Frame frame, ref Quantum.BattleDiamondDataQComponent result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattleDiamondDataQComponentPrototype.MaterializeUser (Frame frame, ref Quantum.BattleDiamondDataQComponent result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
IsTraveling
QBoolean Quantum.Prototypes.BattleDiamondDataQComponentPrototype.IsTraveling
LifetimeTimer
Quantum.Prototypes.FrameTimerPrototype Quantum.Prototypes.BattleDiamondDataQComponentPrototype.LifetimeTimer
StartPosition
FPVector2 Quantum.Prototypes.BattleDiamondDataQComponentPrototype.StartPosition
TargetDistance
FP Quantum.Prototypes.BattleDiamondDataQComponentPrototype.TargetDistance
TravelDirection
FPVector2 Quantum.Prototypes.BattleDiamondDataQComponentPrototype.TravelDirection
TravelSpeed
FP Quantum.Prototypes.BattleDiamondDataQComponentPrototype.TravelSpeed
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs