Battle: Battle.QSimulation.Player.BattlePlayerClassManager Class Reference
Battle.QSimulation.Player.BattlePlayerClassManager Class Reference
Handles the initial loading of player classes and routes individual game events to the correct class scripts.
Static Public Member Functions
static void Init ()
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
static void LoadClass (BattlePlayerCharacterClass characterClass)
Loads the specified class to be ready for use, if it is implemented.
static void OnCreate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Calls the OnCreate method of the class of the given player character, if it is implemented.
static void OnSpawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Calls the OnSpawn method of the class of the given player character, if it is implemented.
static void OnDespawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Calls the OnDespawn method of the class of the given player character, if it is implemented.
static void OnProjectileHitPlayerCharacter (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerCharacterCollisionData *playerCollisionData)
Calls the OnProjectileHitPlayerCharacter method of the class of the given player character, if it is implemented.
static void OnProjectileHitPlayerShield (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerShieldCollisionData *shieldCollisionData)
Calls the OnProjectileHitPlayerShield method of the class of the given player character, if it is implemented.
static void OnUpdate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Calls the OnUpdate method of the class of the given player character, if it is implemented.
Private Types
enum ReturnCode { ClassRetrieved = 0 , NoClass = 1 , Error = 2 }
Enum that defines the GetClass method's return codes.
Used to communicate the result of method call.
Static Private Member Functions
static ReturnCode GetClass (BattlePlayerCharacterClass characterClass, out BattlePlayerClassBase playerClass)
Returns the class script of the specified class from the class array, if it is implemented.
Static Private Attributes
const int ClassIndexError = -2
Constant for a class index error.
const int ClassIndexNoCode = -1
Constant for a no code class index.
const int ClassIndexDesensitizer = 0
Constant for Desensitizer class index.
const int ClassIndexTrickster = 1
Constant for Trickster class index.
const int ClassIndexProjector = 2
Constant for Projector class index.
const int ClassIndexRetroflector = 3
Constant for Retroflector class index.
const int ClassIndexConfluent = 4
Constant for Confluent class index.
const int ClassIndexIntellectualizer = 5
Constant for Intellectualizer class index.
const int ClassCount = 6
Constant for the amount of classes that exist.
static BattlePlayerClassBase[] s_classArray = new BattlePlayerClassBase[ClassCount]
An array containing all of the class scripts that have been implemented and can be used.
static Dictionary< BattlePlayerCharacterClass, bool > s_errorMessagesSent = new()
A dictionary used for tracking which classes have already had an error message sent regarding their missing implementation.
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
Detailed Description
Handles the initial loading of player classes and routes individual game events to the correct class scripts.
Member Enumeration Documentation
ReturnCode
enum Battle.QSimulation.Player.BattlePlayerClassManager.ReturnCode private
Enum that defines the GetClass method's return codes.
Used to communicate the result of method call.
Enumerator
ClassRetrieved
A class was retrieved.
NoClass
No class was retrieved.
Used when a character class has no code associated with it.
Error
Class could not be retrieved.
Member Function Documentation
GetClass()
ReturnCode Battle.QSimulation.Player.BattlePlayerClassManager.GetClass (BattlePlayerCharacterClass characterClass, out BattlePlayerClassBase playerClass) inline static private
Returns the class script of the specified class from the class array, if it is implemented.
Parameters
characterClass The player character class that's C# class is to be retrieved.
playerClass The player character C# class that is retrieved. (out param)
Returns
Result of the method call as a ReturnCode.
References Battle.QSimulation.Player.BattlePlayerClassBase.Class, ClassIndexConfluent, ClassIndexDesensitizer, ClassIndexError, ClassIndexNoCode, ClassIndexProjector, Quantum.Confluent, Quantum.Desensitizer, Quantum.None, Quantum.Obedient, Quantum.Projector, s_classArray, s_debugLogger, and s_errorMessagesSent.
Referenced by OnCreate(), OnDespawn(), OnProjectileHitPlayerCharacter(), OnProjectileHitPlayerShield(), OnSpawn(), and OnUpdate().
Init()
void Battle.QSimulation.Player.BattlePlayerClassManager.Init () inline static
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
References Battle.QSimulation.BattleDebugLogger.Create(), and s_debugLogger.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
LoadClass()
void Battle.QSimulation.Player.BattlePlayerClassManager.LoadClass (BattlePlayerCharacterClass characterClass) inline static
Loads the specified class to be ready for use, if it is implemented.
Parameters
characterClass The class that is to be loaded.
References ClassIndexConfluent, ClassIndexDesensitizer, ClassIndexIntellectualizer, ClassIndexProjector, ClassIndexRetroflector, ClassIndexTrickster, and s_classArray.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers().
OnCreate()
void Battle.QSimulation.Player.BattlePlayerClassManager.OnCreate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, EntityRef playerEntity) inline static
Calls the OnCreate method of the class of the given player character, if it is implemented.
Parameters
f Current simulation frame.
playerHandle Reference to the player handle.
playerData Pointer reference to the player data.
playerEntity Reference to the player entity.
References Quantum.BattlePlayerDataQComponent.CharacterClass, GetClass(), and s_debugLogger.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers().
OnDespawn()
void Battle.QSimulation.Player.BattlePlayerClassManager.OnDespawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, EntityRef playerEntity) inline static
Calls the OnDespawn method of the class of the given player character, if it is implemented.
Parameters
f Current simulation frame.
playerHandle Reference to the player handle.
playerData Pointer reference to the player data.
playerEntity Reference to the player entity.
References Quantum.BattlePlayerDataQComponent.CharacterClass, and GetClass().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer().
OnProjectileHitPlayerCharacter()
void Battle.QSimulation.Player.BattlePlayerClassManager.OnProjectileHitPlayerCharacter (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, BattleCollisionQSystem.PlayerCharacterCollisionData * playerCollisionData) inline static
Calls the OnProjectileHitPlayerCharacter method of the class of the given player character, if it is implemented.
Parameters
f Current simulation frame.
projectileCollisionData Collision data related to the projectile.
playerCollisionData Collision data related to the player character.
References Quantum.BattlePlayerDataQComponent.CharacterClass, and GetClass().
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
OnProjectileHitPlayerShield()
void Battle.QSimulation.Player.BattlePlayerClassManager.OnProjectileHitPlayerShield (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, BattleCollisionQSystem.PlayerShieldCollisionData * shieldCollisionData) inline static
Calls the OnProjectileHitPlayerShield method of the class of the given player character, if it is implemented.
Parameters
f Current simulation frame.
projectileCollisionData Collision data related to the projectile.
shieldCollisionData Collision data related to the player shield.
References Quantum.BattlePlayerDataQComponent.CharacterClass, and GetClass().
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
OnSpawn()
void Battle.QSimulation.Player.BattlePlayerClassManager.OnSpawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, EntityRef playerEntity) inline static
Calls the OnSpawn method of the class of the given player character, if it is implemented.
Parameters
f Current simulation frame.
playerHandle Reference to the player handle.
playerData Pointer reference to the player data.
playerEntity Reference to the player entity.
References Quantum.BattlePlayerDataQComponent.CharacterClass, and GetClass().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
OnUpdate()
void Battle.QSimulation.Player.BattlePlayerClassManager.OnUpdate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, EntityRef playerEntity) inline static
Calls the OnUpdate method of the class of the given player character, if it is implemented.
Parameters
f Current simulation frame.
playerHandle Reference to the player handle.
playerData Pointer reference to the player data.
playerEntity Reference to the player entity.
References Quantum.BattlePlayerDataQComponent.CharacterClass, and GetClass().
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.HandleInPlay().
Member Data Documentation
ClassCount
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassCount = 6 static private
Constant for the amount of classes that exist.
ClassIndexConfluent
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexConfluent = 4 static private
Constant for Confluent class index.
Referenced by GetClass(), and LoadClass().
ClassIndexDesensitizer
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexDesensitizer = 0 static private
Constant for Desensitizer class index.
Referenced by GetClass(), and LoadClass().
ClassIndexError
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexError = -2 static private
Constant for a class index error.
Referenced by GetClass().
ClassIndexIntellectualizer
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexIntellectualizer = 5 static private
Constant for Intellectualizer class index.
Referenced by LoadClass().
ClassIndexNoCode
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexNoCode = -1 static private
Constant for a no code class index.
Referenced by GetClass().
ClassIndexProjector
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexProjector = 2 static private
Constant for Projector class index.
Referenced by GetClass(), and LoadClass().
ClassIndexRetroflector
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexRetroflector = 3 static private
Constant for Retroflector class index.
Referenced by LoadClass().
ClassIndexTrickster
const int Battle.QSimulation.Player.BattlePlayerClassManager.ClassIndexTrickster = 1 static private
Constant for Trickster class index.
Referenced by LoadClass().
s_classArray
BattlePlayerClassBase [] Battle.QSimulation.Player.BattlePlayerClassManager.s_classArray = new BattlePlayerClassBase[ClassCount] static private
An array containing all of the class scripts that have been implemented and can be used.
Referenced by GetClass(), and LoadClass().
s_debugLogger
BattleDebugLogger Battle.QSimulation.Player.BattlePlayerClassManager.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by GetClass(), Init(), and OnCreate().
s_errorMessagesSent
Dictionary<BattlePlayerCharacterClass, bool> Battle.QSimulation.Player.BattlePlayerClassManager.s_errorMessagesSent = new() static private
A dictionary used for tracking which classes have already had an error message sent regarding their missing implementation.
Referenced by GetClass().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerClassManager.cs