Battle: Battle.View.Game.BattleGameViewController Class Reference
Battle.View.Game.BattleGameViewController Class Reference
Game view QuantumCallbacks class游못.
Initializes Battle UI elements, and controls their visibility and functionality.
Public Member Functions
UiInput methods
UiInput methods are called when the player gives an UI input, such as presses a button. These methods shouldn't be called any other way.
void UiInputOnLocalPlayerGiveUp ()
Public method that gets called when the local player pressed the give up button.
void UiInputOnCharacterSelected (int characterNumber)
Public method that gets called when the local player selected another character.
Calls BattlePlayerInput.OnCharacterSelected method in _playerInput.
void UiInputOnJoystickMovement (Vector2 input)
Public method that gets called when local player gives movement joystick input. Calls OnJoystickMovement method in _playerInput.
void UiInputOnJoystickRotation (float input)
Public method that gets called when local player gives rotation joystick input. Calls OnJoystickRotation method in _playerInput.
void UiInputOnExitGamePressed ()
Public method that gets called when the local player pressed the exit game button.
Calls ExitQuantum method in LobbyManager, which makes the local player leave the game.
Static Public Member Functions
static void AssignProjectileReference (GameObject projectileReference)
Public static method for assigning ProjectileReference.
Properties
static BattlePlayerSlot LocalPlayerSlot [get, private set]
The local player's BattlePlayerSlot.
static BattleTeamNumber LocalPlayerTeam [get, private set]
The local player's BattleTeamNumber.
static GameObject ProjectileReference [get, private set]
Reference to the projectile's GameObject游못.
static BattleUiController UiController [get]
Reference to the UiController.
Private Member Functions
void Awake ()
Private Awake游못 method. Handles subscribing to QuantumEvents.
void Update ()
Private Update游못 method. Handles UI updates based on the game's state and countdown.
QuantumEvent handlers
QuantumEvent handler methods are called by QuantumEvents. These methods shouldn't be called any other way.
void QEventOnViewWaitForPlayers (EventBattleViewWaitForPlayers e)
Private handler method for EventBattleViewWaitForPlayers QuantumEvent.
Handles initializing AnnouncementHandler in _uiController with waiting for players text.
void QEventOnViewPlayerConnected (EventBattleViewPlayerConnected e)
Private handler method for EventBattleViewPlayerConnected QuantumEvent.
Handles calling PlayerConnected through _uiController with the slot and character IDs of the connected player.
void QEventOnViewAllPlayersConnected (EventBattleViewAllPlayersConnected e)
Private handler method for EventBattleViewAllPlayersConnected QuantumEvent.
Handles calling ClearAnnouncerTextField once all players have successfully joined the game.
void QEventOnViewInit (EventBattleViewInit e)
Private handler method for EventViewInit QuantumEvent.
Handles initializing the UIHandlerReferences scripts and _gridViewController.
void QEventOnStoneCharacterPieceViewInit (EventBattleStoneCharacterPieceViewInit e)
Private handler method for EventBattleStoneCharacterPieceViewInit QuantumEvent.
Handles initializing BattleGameViewController._stoneCharacterViewController.
void QEventOnSetRotationJoystickVisibility (EventBattleViewSetRotationJoystickVisibility e)
Private handler method for EventBattleViewSetRotationJoystickVisibility QuantumEvent.
Sets the rotation control joystick to be shown or hidden, if that control method is selected.
void QEventOnViewActivate (EventBattleViewActivate e)
Private handler method for EventBattleViewActivate QuantumEvent.
Handles showing UI elements and initializing BattleCamera scale and rotation.
void QEventOnViewGetReadyToPlay (EventBattleViewGetReadyToPlay e)
Private handler method for EventBattleViewGetReadyToPlay QuantumEvent.
Handles showing end of countdown text in BattleUiController.AnnouncementHandler
and calling SetLocked false to unlock joysticks to allow player movement and rotation.
void QEventOnViewGameStart (EventBattleViewGameStart e)
Private handler method for EventBattleViewGameStart QuantumEvent.
Handles clearing AnnouncementHandler text and showing the game timer.
void QEventOnViewGameOver (EventBattleViewGameOver e)
Private handler method for EventBattleViewGameOver QuantumEvent.
Handles hiding UI elements, showing GameOverHandler and setting EndOfGameData variables.
void QEventOnChangeEmotionState (EventBattleChangeEmotionState e)
Private handler method for EventBattleChangeEmotionState QuantumEvent.
Handles calling ChangeColor in _screenEffectViewController.
void QEventOnLastRowWallDestroyed (EventBattleLastRowWallDestroyed e)
Private handler method for EventBattleLastRowWallDestroyed QuantumEvent.
Handles calling DestroyCharacterPart in _stoneCharacterViewController
and SpawnLightray in _lightrayEffectViewController.
void QEventPlaySoundFX (EventBattlePlaySoundFX e)
Private handler method for EventBattlePlaySoundFX QuantumEvent.
Handles calling PlaySound.
void QEventCharacterSelected (EventBattleCharacterSelected e)
void QEventOnCharacterTakeDamage (EventBattleCharacterTakeDamage e)
Private handler method for EventBattleCharacterTakeDamage QuantumEvent.
Handles calling UpdateHealthVisual in _uiController's PlayerInfoHandler.
void QEventOnShieldTakeDamage (EventBattleShieldTakeDamage e)
Private handler method for EventBattleShieldTakeDamage QuantumEvent.
Handles calling UpdateDefenceVisual in _uiController's PlayerInfoHandler.
void QEventOnGiveUpStateChange (EventBattleGiveUpStateChange e)
Private handler method for EventBattleGiveUpStateChange QuantumEvent.
Handles calling UpdateState in _uiController's GiveUpButtonHandler.
void QEventDebugOnScreenMessage (EventBattleDebugOnScreenMessage e)
Private handler method for EventBattleDebugOnScreenMessage QuantumEvent.
Handles calling SetDebugtext in _uiController's BattleUiController.AnnouncementHandler.
Private Attributes
BattleDebugLogger _debugLogger
This classes BattleDebugLogger instance.
SerializeField variables
SerializeFields游못 are serialized variables exposed to the Unity editor.
BattleGridViewController _gridViewController
[SerializeField] Reference to BattleGridViewController which handles visual functionality for the Battle arena's grid.
BattleUiController _uiController
[SerializeField] Reference to BattleUiController which holds references to all of the UIHandlerReferences scripts.
BattleScreenEffectViewController _screenEffectViewController
[SerializeField] Reference to BattleScreenEffectViewController which handles the screen effects.
BattleStoneCharacterViewController _stoneCharacterViewController
[SerializeField] Reference to BattleStoneCharacterViewController which handles stone character parts visibility.
BattleLightrayEffectViewController _lightrayEffectViewController
[SerializeField] Reference to BattleLightrayEffectViewController which handles lightray effects visibility.
BattlePlayerInput _playerInput
[SerializeField] Reference to BattlePlayerInput which polls player input for Quantum.
EndOfGameData variables
Private variables which contain end of game data to pass on to LobbyManager.
bool _endOfGameDataHasEnded = false
Bool to indicate whether the game has ended yet.
BattleTeamNumber _endOfGameDataWinningTeam
The winning team's BattleTeamNumber.
FP _endOfGameDataGameLengthSec
The game's length as seconds.
Static Private Attributes
static BattleGameViewController s_instance
Private static reference to an instance of BattleGameViewController.
Detailed Description
Game view QuantumCallbacks class游못.
Initializes Battle UI elements, and controls their visibility and functionality.
Handles any functionality needed by the [UI Handlers] which need to access other parts of Battle, for example triggering the selection of another character. Accesses all of the UIHandlerReferences through the BattleUiController reference variable _uiController.
Member Function Documentation
AssignProjectileReference()
void Battle.View.Game.BattleGameViewController.AssignProjectileReference (GameObject projectileReference) inline static
Public static method for assigning ProjectileReference.
Parameters
projectileReference The projectile GameObject游못.
References ProjectileReference.
Referenced by Battle.View.Projectile.BattleProjectileViewController.OnActivate().
Awake()
void Battle.View.Game.BattleGameViewController.Awake () inline private
Private Awake游못 method. Handles subscribing to QuantumEvents.
References _debugLogger, _gridViewController, _lightrayEffectViewController, _stoneCharacterViewController, _uiController, Battle.QSimulation.BattleDebugLogger.Create(), Battle.View.BattleDebugOverlay.Init(), QEventCharacterSelected(), QEventDebugOnScreenMessage(), QEventOnChangeEmotionState(), QEventOnCharacterTakeDamage(), QEventOnGiveUpStateChange(), QEventOnLastRowWallDestroyed(), QEventOnSetRotationJoystickVisibility(), QEventOnShieldTakeDamage(), QEventOnStoneCharacterPieceViewInit(), QEventOnViewActivate(), QEventOnViewAllPlayersConnected(), QEventOnViewGameOver(), QEventOnViewGameStart(), QEventOnViewGetReadyToPlay(), QEventOnViewInit(), QEventOnViewPlayerConnected(), QEventOnViewWaitForPlayers(), QEventPlaySoundFX(), and s_instance.
QEventCharacterSelected()
void Battle.View.Game.BattleGameViewController.QEventCharacterSelected (EventBattleCharacterSelected e) inline private
References _uiController, Quantum.EventBattleCharacterSelected.CharacterNumber, and Quantum.EventBattleCharacterSelected.Slot.
Referenced by Awake().
QEventDebugOnScreenMessage()
void Battle.View.Game.BattleGameViewController.QEventDebugOnScreenMessage (EventBattleDebugOnScreenMessage e) inline private
Private handler method for EventBattleDebugOnScreenMessage QuantumEvent.
Handles calling SetDebugtext in _uiController's BattleUiController.AnnouncementHandler.
Parameters
e The event data.
References _uiController, and Quantum.EventBattleDebugOnScreenMessage.Message.
Referenced by Awake().
QEventOnChangeEmotionState()
void Battle.View.Game.BattleGameViewController.QEventOnChangeEmotionState (EventBattleChangeEmotionState e) inline private
Private handler method for EventBattleChangeEmotionState QuantumEvent.
Handles calling ChangeColor in _screenEffectViewController.
Parameters
e The event data.
References _screenEffectViewController, and Quantum.EventBattleChangeEmotionState.Emotion.
Referenced by Awake().
QEventOnCharacterTakeDamage()
void Battle.View.Game.BattleGameViewController.QEventOnCharacterTakeDamage (EventBattleCharacterTakeDamage e) inline private
Private handler method for EventBattleCharacterTakeDamage QuantumEvent.
Handles calling UpdateHealthVisual in _uiController's PlayerInfoHandler.
Parameters
e The event data.
References _uiController, Quantum.EventBattleCharacterTakeDamage.CharacterNumber, Quantum.EventBattleCharacterTakeDamage.HealthPercentage, LocalPlayerTeam, Quantum.EventBattleCharacterTakeDamage.Slot, and Quantum.EventBattleCharacterTakeDamage.Team.
Referenced by Awake().
QEventOnGiveUpStateChange()
void Battle.View.Game.BattleGameViewController.QEventOnGiveUpStateChange (EventBattleGiveUpStateChange e) inline private
Private handler method for EventBattleGiveUpStateChange QuantumEvent.
Handles calling UpdateState in _uiController's GiveUpButtonHandler.
Parameters
e The event data.
References _uiController, LocalPlayerTeam, Quantum.EventBattleGiveUpStateChange.Slot, Quantum.EventBattleGiveUpStateChange.StateUpdate, and Quantum.EventBattleGiveUpStateChange.Team.
Referenced by Awake().
QEventOnLastRowWallDestroyed()
void Battle.View.Game.BattleGameViewController.QEventOnLastRowWallDestroyed (EventBattleLastRowWallDestroyed e) inline private
Private handler method for EventBattleLastRowWallDestroyed QuantumEvent.
Handles calling DestroyCharacterPart in _stoneCharacterViewController
and SpawnLightray in _lightrayEffectViewController.
Parameters
e The event data.
References _lightrayEffectViewController, _stoneCharacterViewController, Quantum.EventBattleLastRowWallDestroyed.LightrayColor, Quantum.EventBattleLastRowWallDestroyed.Team, and Quantum.EventBattleLastRowWallDestroyed.WallNumber.
Referenced by Awake().
QEventOnSetRotationJoystickVisibility()
void Battle.View.Game.BattleGameViewController.QEventOnSetRotationJoystickVisibility (EventBattleViewSetRotationJoystickVisibility e) inline private
Private handler method for EventBattleViewSetRotationJoystickVisibility QuantumEvent.
Sets the rotation control joystick to be shown or hidden, if that control method is selected.
Parameters
e The event data.
References _uiController, Quantum.EventBattleViewSetRotationJoystickVisibility.IsVisible, LocalPlayerSlot, and Quantum.EventBattleViewSetRotationJoystickVisibility.Slot.
Referenced by Awake().
QEventOnShieldTakeDamage()
void Battle.View.Game.BattleGameViewController.QEventOnShieldTakeDamage (EventBattleShieldTakeDamage e) inline private
Private handler method for EventBattleShieldTakeDamage QuantumEvent.
Handles calling UpdateDefenceVisual in _uiController's PlayerInfoHandler.
Parameters
e The event data.
References _uiController, Quantum.EventBattleShieldTakeDamage.CharacterNumber, Quantum.EventBattleShieldTakeDamage.DefenceValue, LocalPlayerTeam, Quantum.EventBattleShieldTakeDamage.Slot, and Quantum.EventBattleShieldTakeDamage.Team.
Referenced by Awake().
QEventOnStoneCharacterPieceViewInit()
void Battle.View.Game.BattleGameViewController.QEventOnStoneCharacterPieceViewInit (EventBattleStoneCharacterPieceViewInit e) inline private
Private handler method for EventBattleStoneCharacterPieceViewInit QuantumEvent.
Handles initializing BattleGameViewController._stoneCharacterViewController.
Parameters
e The event data.
References _stoneCharacterViewController, Quantum.EventBattleStoneCharacterPieceViewInit.EmotionIndicatorColorIndex, Quantum.EventBattleStoneCharacterPieceViewInit.Team, and Quantum.EventBattleStoneCharacterPieceViewInit.WallNumber.
Referenced by Awake().
QEventOnViewActivate()
void Battle.View.Game.BattleGameViewController.QEventOnViewActivate (EventBattleViewActivate e) inline private
Private handler method for EventBattleViewActivate QuantumEvent.
Handles showing UI elements and initializing BattleCamera scale and rotation.
Parameters
e The event data.
References _uiController, LocalPlayerTeam, Battle.View.Audio.BattleAudioViewController.PlayMusic(), and Battle.View.Game.BattleCamera.SetView().
Referenced by Awake().
QEventOnViewAllPlayersConnected()
void Battle.View.Game.BattleGameViewController.QEventOnViewAllPlayersConnected (EventBattleViewAllPlayersConnected e) inline private
Private handler method for EventBattleViewAllPlayersConnected QuantumEvent.
Handles calling ClearAnnouncerTextField once all players have successfully joined the game.
Parameters
e The event data.
References _uiController.
Referenced by Awake().
QEventOnViewGameOver()
void Battle.View.Game.BattleGameViewController.QEventOnViewGameOver (EventBattleViewGameOver e) inline private
Private handler method for EventBattleViewGameOver QuantumEvent.
Handles hiding UI elements, showing GameOverHandler and setting EndOfGameData variables.
Parameters
e The event data.
References _endOfGameDataGameLengthSec, _endOfGameDataHasEnded, _endOfGameDataWinningTeam, _uiController, Quantum.EventBattleViewGameOver.GameLengthSec, and Quantum.EventBattleViewGameOver.WinningTeam.
Referenced by Awake().
QEventOnViewGameStart()
void Battle.View.Game.BattleGameViewController.QEventOnViewGameStart (EventBattleViewGameStart e) inline private
Private handler method for EventBattleViewGameStart QuantumEvent.
Handles clearing AnnouncementHandler text and showing the game timer.
Parameters
e The event data.
References _uiController.
Referenced by Awake().
QEventOnViewGetReadyToPlay()
void Battle.View.Game.BattleGameViewController.QEventOnViewGetReadyToPlay (EventBattleViewGetReadyToPlay e) inline private
Private handler method for EventBattleViewGetReadyToPlay QuantumEvent.
Handles showing end of countdown text in BattleUiController.AnnouncementHandler
and calling SetLocked false to unlock joysticks to allow player movement and rotation.
Parameters
e The event data.
References _uiController.
Referenced by Awake().
QEventOnViewInit()
void Battle.View.Game.BattleGameViewController.QEventOnViewInit (EventBattleViewInit e) inline private
Private handler method for EventViewInit QuantumEvent.
Handles initializing the UIHandlerReferences scripts and _gridViewController.
See UIHandlerReferences for more info.
Parameters
e The event data.
References _gridViewController, _uiController, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetSlot(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeamNumber(), LocalPlayerSlot, LocalPlayerTeam, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.PlayerRef, Battle.QSimulation.BattleDebugOverlayLink.SetLocalPlayerSlot(), and Battle.View.Utils.TryGetQuantumFrame().
Referenced by Awake().
QEventOnViewPlayerConnected()
void Battle.View.Game.BattleGameViewController.QEventOnViewPlayerConnected (EventBattleViewPlayerConnected e) inline private
Private handler method for EventBattleViewPlayerConnected QuantumEvent.
Handles calling PlayerConnected through _uiController with the slot and character IDs of the connected player.
Parameters
e The event data.
References _uiController, Quantum.RuntimePlayer.Characters, Quantum.BattleCharacterBase.Class, Quantum.EventBattleViewPlayerConnected.Data, Quantum.BattleCharacterBase.Id, and Quantum.RuntimePlayer.PlayerSlot.
Referenced by Awake().
QEventOnViewWaitForPlayers()
void Battle.View.Game.BattleGameViewController.QEventOnViewWaitForPlayers (EventBattleViewWaitForPlayers e) inline private
Private handler method for EventBattleViewWaitForPlayers QuantumEvent.
Handles initializing AnnouncementHandler in _uiController with waiting for players text.
Parameters
e The event data.
References _uiController, Quantum.EventBattleViewWaitForPlayers.Data, Battle.QSimulation.Game.BattleParameters.GetPlayerSlotTypes(), Quantum.BattleWaitForPlayersData.PlayerNames, and Battle.View.Utils.TryGetQuantumFrame().
Referenced by Awake().
QEventPlaySoundFX()
void Battle.View.Game.BattleGameViewController.QEventPlaySoundFX (EventBattlePlaySoundFX e) inline private
Private handler method for EventBattlePlaySoundFX QuantumEvent.
Handles calling PlaySound.
Parameters
e The event data.
References Quantum.EventBattlePlaySoundFX.Effect, and Battle.View.Audio.BattleAudioViewController.PlaySoundFX().
Referenced by Awake().
UiInputOnCharacterSelected()
void Battle.View.Game.BattleGameViewController.UiInputOnCharacterSelected (int characterNumber) inline
Public method that gets called when the local player selected another character.
Calls BattlePlayerInput.OnCharacterSelected method in _playerInput.
Parameters
characterNumber The character number which the local player selected.
References _debugLogger, and _playerInput.
UiInputOnExitGamePressed()
void Battle.View.Game.BattleGameViewController.UiInputOnExitGamePressed () inline
Public method that gets called when the local player pressed the exit game button.
Calls ExitQuantum method in LobbyManager, which makes the local player leave the game.
References _endOfGameDataGameLengthSec, _endOfGameDataHasEnded, _endOfGameDataWinningTeam, and LocalPlayerTeam.
UiInputOnJoystickMovement()
void Battle.View.Game.BattleGameViewController.UiInputOnJoystickMovement (Vector2 input) inline
Public method that gets called when local player gives movement joystick input. Calls OnJoystickMovement method in _playerInput.
Parameters
input The movement direction Vector2.
References _playerInput.
UiInputOnJoystickRotation()
void Battle.View.Game.BattleGameViewController.UiInputOnJoystickRotation (float input) inline
Public method that gets called when local player gives rotation joystick input. Calls OnJoystickRotation method in _playerInput.
Parameters
input The rotation input as float.
References _playerInput.
UiInputOnLocalPlayerGiveUp()
void Battle.View.Game.BattleGameViewController.UiInputOnLocalPlayerGiveUp () inline
Public method that gets called when the local player pressed the give up button.
References _debugLogger, and _playerInput.
Update()
void Battle.View.Game.BattleGameViewController.Update () inline private
Private Update游못 method. Handles UI updates based on the game's state and countdown.
References _debugLogger, _uiController, Quantum.BattleDiamondCounterQSingleton.AlphaDiamonds, Quantum.BattleDiamondCounterQSingleton.BetaDiamonds, Quantum.BattleGameSessionQSingleton.GameTimeSec, LocalPlayerTeam, Quantum.BattleGameSessionQSingleton.State, Quantum.BattleGameSessionQSingleton.TimeUntilStartSec, and Battle.View.Utils.TryGetQuantumFrame().
Member Data Documentation
_debugLogger
BattleDebugLogger Battle.View.Game.BattleGameViewController._debugLogger private
This classes BattleDebugLogger instance.
Referenced by Awake(), UiInputOnCharacterSelected(), UiInputOnLocalPlayerGiveUp(), and Update().
_endOfGameDataGameLengthSec
FP Battle.View.Game.BattleGameViewController._endOfGameDataGameLengthSec private
The game's length as seconds.
Referenced by QEventOnViewGameOver(), and UiInputOnExitGamePressed().
_endOfGameDataHasEnded
bool Battle.View.Game.BattleGameViewController._endOfGameDataHasEnded = false private
Bool to indicate whether the game has ended yet.
Referenced by QEventOnViewGameOver(), and UiInputOnExitGamePressed().
_endOfGameDataWinningTeam
BattleTeamNumber Battle.View.Game.BattleGameViewController._endOfGameDataWinningTeam private
The winning team's BattleTeamNumber.
Referenced by QEventOnViewGameOver(), and UiInputOnExitGamePressed().
_gridViewController
BattleGridViewController Battle.View.Game.BattleGameViewController._gridViewController private
[SerializeField] Reference to BattleGridViewController which handles visual functionality for the Battle arena's grid.
BattleGameViewController-SerializeFields
Referenced by Awake(), and QEventOnViewInit().
_lightrayEffectViewController
BattleLightrayEffectViewController Battle.View.Game.BattleGameViewController._lightrayEffectViewController private
[SerializeField] Reference to BattleLightrayEffectViewController which handles lightray effects visibility.
BattleGameViewController-SerializeFields
Referenced by Awake(), and QEventOnLastRowWallDestroyed().
_playerInput
BattlePlayerInput Battle.View.Game.BattleGameViewController._playerInput private
[SerializeField] Reference to BattlePlayerInput which polls player input for Quantum.
BattleGameViewController-SerializeFields
Referenced by UiInputOnCharacterSelected(), UiInputOnJoystickMovement(), UiInputOnJoystickRotation(), and UiInputOnLocalPlayerGiveUp().
_screenEffectViewController
BattleScreenEffectViewController Battle.View.Game.BattleGameViewController._screenEffectViewController private
[SerializeField] Reference to BattleScreenEffectViewController which handles the screen effects.
BattleGameViewController-SerializeFields
Referenced by QEventOnChangeEmotionState().
_stoneCharacterViewController
BattleStoneCharacterViewController Battle.View.Game.BattleGameViewController._stoneCharacterViewController private
[SerializeField] Reference to BattleStoneCharacterViewController which handles stone character parts visibility.
BattleGameViewController-SerializeFields
Referenced by Awake(), QEventOnLastRowWallDestroyed(), and QEventOnStoneCharacterPieceViewInit().
_uiController
BattleUiController Battle.View.Game.BattleGameViewController._uiController private
[SerializeField] Reference to BattleUiController which holds references to all of the UIHandlerReferences scripts.
BattleGameViewController-SerializeFields
Referenced by Awake(), QEventCharacterSelected(), QEventDebugOnScreenMessage(), QEventOnCharacterTakeDamage(), QEventOnGiveUpStateChange(), QEventOnSetRotationJoystickVisibility(), QEventOnShieldTakeDamage(), QEventOnViewActivate(), QEventOnViewAllPlayersConnected(), QEventOnViewGameOver(), QEventOnViewGameStart(), QEventOnViewGetReadyToPlay(), QEventOnViewInit(), QEventOnViewPlayerConnected(), QEventOnViewWaitForPlayers(), and Update().
s_instance
BattleGameViewController Battle.View.Game.BattleGameViewController.s_instance static private
Private static reference to an instance of BattleGameViewController.
Referenced by Awake().
Property Documentation
LocalPlayerSlot
BattlePlayerSlot Battle.View.Game.BattleGameViewController.LocalPlayerSlot static get private set
The local player's BattlePlayerSlot.
Referenced by Battle.View.UI.BattleUiPlayerInfoHandler.GetPlayerInfoComponent(), Battle.View.Player.BattlePlayerViewController.OnActivate(), Battle.View.Player.BattlePlayerInput.PollInput(), QEventOnSetRotationJoystickVisibility(), QEventOnViewInit(), Battle.View.UI.BattleUiPlayerInfoHandler.SetSelected(), and Battle.View.UI.BattleUiGiveUpButtonHandler.UpdateState().
LocalPlayerTeam
BattleTeamNumber Battle.View.Game.BattleGameViewController.LocalPlayerTeam static get private set
The local player's BattleTeamNumber.
Referenced by Battle.View.Player.BattlePlayerInput.GetMovementInput(), Battle.View.Player.BattlePlayerInput.GetRotationInput(), Battle.View.Diamond.BattleDiamondViewController.OnActivate(), Battle.View.Player.BattlePlayerViewController.OnActivate(), Battle.View.Projectile.BattleProjectileViewController.OnActivate(), QEventOnCharacterTakeDamage(), QEventOnGiveUpStateChange(), QEventOnShieldTakeDamage(), QEventOnViewActivate(), QEventOnViewInit(), UiInputOnExitGamePressed(), and Update().
ProjectileReference
GameObject Battle.View.Game.BattleGameViewController.ProjectileReference static get private set
Reference to the projectile's GameObject游못.
Referenced by AssignProjectileReference(), and Battle.View.Player.BattlePlayerClassProjectorViewController.OnUpdateView().
UiController
BattleUiController Battle.View.Game.BattleGameViewController.UiController static get
Reference to the UiController.
Referenced by Battle.View.BattleDebugOverlay.AddEntries(), Battle.View.BattleDebugOverlay.AddEntry(), Battle.View.BattleDebugOverlay.SetEntries(), and Battle.View.BattleDebugOverlay.SetEntry().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/View/Battle/Scripts/Game/BattleGameViewController.cs