Battle: QuantumUser.Scripts.SoundFXManager Class Reference
QuantumUser.Scripts.SoundFXManager Class Reference
Static Public Attributes
static SoundFXManager instance
Private Member Functions
void Awake ()
void OnEnable ()
void OnDisable ()
void OnPlaySoundEvent (EventPlaySoundEvent e)
void PlaySoundFXclip (AudioClip clip)
Private Attributes
AudioSource _audioSource
AudioClip _soulWallHitClip
AudioClip _goalHitClip
AudioClip _sideWallHitClip
AudioClip _wallBroken
Member Function Documentation
Awake()
void QuantumUser.Scripts.SoundFXManager.Awake () inline private
References instance.
OnDisable()
void QuantumUser.Scripts.SoundFXManager.OnDisable () inline private
OnEnable()
void QuantumUser.Scripts.SoundFXManager.OnEnable () inline private
References OnPlaySoundEvent().
OnPlaySoundEvent()
void QuantumUser.Scripts.SoundFXManager.OnPlaySoundEvent (EventPlaySoundEvent e) inline private
References _goalHitClip, _sideWallHitClip, _soulWallHitClip, _wallBroken, Quantum.GoalHit, PlaySoundFXclip(), Quantum.SideWallHit, Quantum.SoulWallHit, Quantum.EventPlaySoundEvent.SoundEffect, and Quantum.WallBroken.
Referenced by OnEnable().
PlaySoundFXclip()
void QuantumUser.Scripts.SoundFXManager.PlaySoundFXclip (AudioClip clip) inline private
References _audioSource.
Referenced by OnPlaySoundEvent().
Member Data Documentation
_audioSource
AudioSource QuantumUser.Scripts.SoundFXManager._audioSource private
Referenced by PlaySoundFXclip().
_goalHitClip
AudioClip QuantumUser.Scripts.SoundFXManager._goalHitClip private
Referenced by OnPlaySoundEvent().
_sideWallHitClip
AudioClip QuantumUser.Scripts.SoundFXManager._sideWallHitClip private
Referenced by OnPlaySoundEvent().
_soulWallHitClip
AudioClip QuantumUser.Scripts.SoundFXManager._soulWallHitClip private
Referenced by OnPlaySoundEvent().
_wallBroken
AudioClip QuantumUser.Scripts.SoundFXManager._wallBroken private
Referenced by OnPlaySoundEvent().
instance
SoundFXManager QuantumUser.Scripts.SoundFXManager.instance static
Referenced by Awake().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Scripts/SoundFXManager.cs