Battle: Battle.QSimulation.Game.BattleGridManager Class Reference
Battle.QSimulation.Game.BattleGridManager Class Reference
Static Public Member Functions
static void Init (BattleArenaQSpec battleArenaSpec)
static int WorldXPositionToGridCol (FP x)
static int WorldYPositionToGridRow (FP y)
static FP GridRowToWorldYPosition (int row)
static FP GridColToWorldXPosition (int col)
static BattleGridPosition WorldPositionToGridPosition (FPVector2 wordPosition)
static FPVector2 GridPositionToWorldPosition (BattleGridPosition gridPosition)
Properties
static int Rows [get, private set]
static int Columns [get, private set]
static int TeamAlphaFieldStart [get, private set]
static int TeamAlphaFieldEnd [get, private set]
static int TeamBetaFieldStart [get, private set]
static int TeamBetaFieldEnd [get, private set]
static FP GridScaleFactor [get, private set]
Static Private Attributes
static FPVector2 s_gridOffset
Member Function Documentation
GridColToWorldXPosition()
FP Battle.QSimulation.Game.BattleGridManager.GridColToWorldXPosition (int col) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetOutOfPlayPosition(), GridPositionToWorldPosition(), and Battle.View.Game.BattleGridViewController.SetGrid().
GridPositionToWorldPosition()
FPVector2 Battle.QSimulation.Game.BattleGridManager.GridPositionToWorldPosition (BattleGridPosition gridPosition) inline static
References Quantum.BattleGridPosition.Col, GridColToWorldXPosition(), GridRowToWorldYPosition(), and Quantum.BattleGridPosition.Row.
Referenced by Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition(), Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateSoulWalls(), and Battle.QSimulation.Player.BattlePlayerManager.Init().
GridRowToWorldYPosition()
FP Battle.QSimulation.Game.BattleGridManager.GridRowToWorldYPosition (int row) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetOutOfPlayPosition(), GridPositionToWorldPosition(), and Battle.View.Game.BattleGridViewController.SetGrid().
Init()
void Battle.QSimulation.Game.BattleGridManager.Init (BattleArenaQSpec battleArenaSpec) inline static
References Columns, Battle.QSimulation.Game.BattleArenaQSpec.GridHeight, GridScaleFactor, Battle.QSimulation.Game.BattleArenaQSpec.GridWidth, Battle.QSimulation.Game.BattleArenaQSpec.MiddleAreaHeight, Rows, s_gridOffset, Battle.QSimulation.Game.BattleArenaQSpec.SoulWallHeight, TeamAlphaFieldEnd, TeamAlphaFieldStart, TeamBetaFieldEnd, TeamBetaFieldStart, and Battle.QSimulation.Game.BattleArenaQSpec.WorldHeight.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
WorldPositionToGridPosition()
BattleGridPosition Battle.QSimulation.Game.BattleGridManager.WorldPositionToGridPosition (FPVector2 wordPosition) inline static
References WorldXPositionToGridCol(), and WorldYPositionToGridRow().
Referenced by Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition(), Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput(), and Battle.QSimulation.Projectile.BattleProjectileQSystem.ProjectileHitPlayerShield().
WorldXPositionToGridCol()
int Battle.QSimulation.Game.BattleGridManager.WorldXPositionToGridCol (FP x) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Battle.View.Player.BattlePlayerInput.GetMovementInput(), and WorldPositionToGridPosition().
WorldYPositionToGridRow()
int Battle.QSimulation.Game.BattleGridManager.WorldYPositionToGridRow (FP y) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Battle.View.Player.BattlePlayerInput.GetMovementInput(), and WorldPositionToGridPosition().
Member Data Documentation
s_gridOffset
FPVector2 Battle.QSimulation.Game.BattleGridManager.s_gridOffset static private
Referenced by GridColToWorldXPosition(), GridRowToWorldYPosition(), Init(), WorldXPositionToGridCol(), and WorldYPositionToGridRow().
Property Documentation
Columns
int Battle.QSimulation.Game.BattleGridManager.Columns static get private set
Referenced by Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition(), Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetOutOfPlayPosition(), Init(), and Battle.View.Game.BattleGridViewController.SetGrid().
GridScaleFactor
FP Battle.QSimulation.Game.BattleGridManager.GridScaleFactor static get private set
Referenced by Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateAbilitySoulWallTest(), Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateSoulWalls(), GridColToWorldXPosition(), GridRowToWorldYPosition(), Init(), Battle.QSimulation.Player.BattlePlayerClassProjector.OnUpdate(), Battle.View.Game.BattleGridViewController.SetGrid(), WorldXPositionToGridCol(), and WorldYPositionToGridRow().
Rows
int Battle.QSimulation.Game.BattleGridManager.Rows static get private set
Referenced by Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateSoulWalls(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetOutOfPlayPosition(), Init(), and Battle.View.Game.BattleGridViewController.SetGrid().
TeamAlphaFieldEnd
int Battle.QSimulation.Game.BattleGridManager.TeamAlphaFieldEnd static get private set
Referenced by Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition(), Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput(), Init(), and Battle.View.Game.BattleGridViewController.SetGrid().
TeamAlphaFieldStart
int Battle.QSimulation.Game.BattleGridManager.TeamAlphaFieldStart static get private set
Referenced by Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition(), Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput(), and Init().
TeamBetaFieldEnd
int Battle.QSimulation.Game.BattleGridManager.TeamBetaFieldEnd static get private set
Referenced by Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition(), Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput(), and Init().
TeamBetaFieldStart
int Battle.QSimulation.Game.BattleGridManager.TeamBetaFieldStart static get private set
Referenced by Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition(), Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput(), Init(), and Battle.View.Game.BattleGridViewController.SetGrid().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleGridManager.cs