Battle: Battle.View.BattleDebugOverlay Class Reference
Battle.View.BattleDebugOverlay Class Reference
Handles the debug info.
Implements methods to control the debug overlay.
Static Public Member Functions
static void Init ()
Initializes debug overlay and calls BattleDebugOverlayLink.InitLink to establish a link with Simulation.
static int AddEntry (string name)
Adds new entry to debug overlay.
static int AddEntries (string[] names)
Adds multiple new entries to debug overlay.
static void SetEntry (int entryNumber, object value)
Sets value of an existing entry in debug overlay.
static void SetEntries (int entryNumber, object[] values)
Sets values of multiple existing entries in debug overlay.
Static Private Attributes
static BattleDebugLogger s_debugLogger = BattleDebugLogger.Create(typeof(BattleDebugOverlay))
This classes BattleDebugLogger instance.
static int s_entryCount
The amount of entries.
Used to assign entry numbers.
Detailed Description
Handles the debug info.
Implements methods to control the debug overlay.
Controls the BattleUiDebugOverlayHandler which handles displaying the debug information.
Establishes a link with BattleDebugOverlayLink to expose debug overlay control methods to Simulation.
Member Function Documentation
AddEntries()
int Battle.View.BattleDebugOverlay.AddEntries (string[] names) inline static
Adds multiple new entries to debug overlay.
Adds new entries and sets their names.
Adds as many entries as there are elements in the names array.
To set entries' values call SetEntry or SetEntries methods with the entryNumber you want to set.
Parameters
names An array of strings used to set entry names.
Returns
The entryNumber of the first added entry.
References s_entryCount, and Battle.View.Game.BattleGameViewController.UiController.
Referenced by Init().
AddEntry()
int Battle.View.BattleDebugOverlay.AddEntry (string name) inline static
Adds new entry to debug overlay.
Adds new entry and sets its name.
To set entries' values call SetEntry or SetEntries methods with the entryNumber you want to set.
Parameters
name Name of the entry.
Returns
The entryNumber of the added entry.
References s_entryCount, and Battle.View.Game.BattleGameViewController.UiController.
Referenced by Init().
Init()
void Battle.View.BattleDebugOverlay.Init () inline static
Initializes debug overlay and calls BattleDebugOverlayLink.InitLink to establish a link with Simulation.
References AddEntries(), AddEntry(), Battle.QSimulation.BattleDebugOverlayLink.InitLink(), s_entryCount, SetEntries(), and SetEntry().
Referenced by Battle.View.Game.BattleGameViewController.Awake().
SetEntries()
void Battle.View.BattleDebugOverlay.SetEntries (int entryNumber, object[] values) inline static
Sets values of multiple existing entries in debug overlay.
Sets values of existing entries from entryNumber to entrynumber + length of the values array.
To add new entries first call AddEntry or AddEntries methods.
Parameters
entryNumber Entry number used to identify the first entry.
values An array of objects to set entries' new values.
References s_debugLogger, s_entryCount, and Battle.View.Game.BattleGameViewController.UiController.
Referenced by Init().
SetEntry()
void Battle.View.BattleDebugOverlay.SetEntry (int entryNumber, object value) inline static
Sets value of an existing entry in debug overlay.
Sets value of an existing entry at entryNumber.
To add new entry first call AddEntry or AddEntries methods.
Parameters
entryNumber Entry number used to identify the entry.
value The entry's new value.
References s_debugLogger, s_entryCount, and Battle.View.Game.BattleGameViewController.UiController.
Referenced by Init().
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.View.BattleDebugOverlay.s_debugLogger = BattleDebugLogger.Create(typeof(BattleDebugOverlay)) static private
This classes BattleDebugLogger instance.
Referenced by SetEntries(), and SetEntry().
s_entryCount
int Battle.View.BattleDebugOverlay.s_entryCount static private
The amount of entries.
Used to assign entry numbers.
Referenced by AddEntries(), AddEntry(), Init(), SetEntries(), and SetEntry().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/View/Battle/Scripts/BattleDebugOverlay.cs