Battle: Battle.QSimulation.Diamond.BattleDiamondQSystem Class Reference
Battle.QSimulation.Diamond.BattleDiamondQSystem Class Reference
Diamond Quantum System游못 [Systems]
Handles spawning diamonds, managing their lifetime and destroying them.
Classes
struct Filter
Filter for filtering diamond entities.
Public Member Functions
override void Update (Frame f, ref Filter filter)
Quantum System Update method游못 gets called every frame.
Updates each diamond's position and speed while they are traveling. Manages each diamond's lifetime and destroys them if players don't gather them quickly enough.
void BattleOnDiamondHitPlayer (Frame f, BattleDiamondDataQComponent *diamond, EntityRef diamondEntity, BattlePlayerHitboxQComponent *playerHitbox, EntityRef playerEntity)
Quantum System Signal method游못 that gets called when ISignalBattleOnDiamondHitPlayer is sent.
Destroys diamonds when player hits them and increases diamondcounters.
void BattleOnDiamondHitArenaBorder (Frame f, BattleDiamondDataQComponent *diamond, EntityRef diamondEntity, BattleArenaBorderQComponent *arenaBorder, EntityRef arenaBorderEntity)
Quantum System Signal method游못 that gets called when ISignalBattleOnDiamondHitArenaBorder is sent.
Reflects the diamonds travel direction off of the arena border.
Static Public Member Functions
static void OnProjectileHitSoulWall (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.SoulWallCollisionData *soulWallCollisionData)
A method called by BattleCollisionQSystem when the projectile collides with a soul wall. If the projectile is not in the held state, calls CreateDiamonds to spawn a diamond.
Static Private Member Functions
static void CreateDiamonds (Frame f, FPVector2 wallPosition, FPVector2 wallNormal, BattleDiamondQSpec diamondSpec)
Creates diamonds.
Diamonds are assigned a target vertical distance to travel, a starting direction to begin traveling in and spawned at the destroyed soulwalls position.
Detailed Description
Diamond Quantum System游못 [Systems]
Handles spawning diamonds, managing their lifetime and destroying them.
This system:
Spawns diamonds when BattleCollisionQSystem calls the OnProjectileHitSoulWall method upon SoulWall segment's destruction.
Filters all diamond entities and handles their lifetime.
Destroys diamonds when player collects them by colliding with them or if diamond's lifetime ends.
Member Function Documentation
BattleOnDiamondHitArenaBorder()
void Battle.QSimulation.Diamond.BattleDiamondQSystem.BattleOnDiamondHitArenaBorder (Frame f, BattleDiamondDataQComponent * diamond, EntityRef diamondEntity, BattleArenaBorderQComponent * arenaBorder, EntityRef arenaBorderEntity) inline
Quantum System Signal method游못 that gets called when ISignalBattleOnDiamondHitArenaBorder is sent.
Reflects the diamonds travel direction off of the arena border.
Warning
This method should only be called via Quantum signal.
Parameters
f Current simulation frame.
diamond Pointer to the diamond component.
diamondEntity EntityRef of the diamond.
arenaBorder Pointer to the arena border component.
arenaBorderEntity EntityRef of the arena border.
Implements Quantum.ISignalBattleOnDiamondHitArenaBorder.
References Quantum.BattleArenaBorderQComponent.CollisionMinOffset, Quantum.BattleArenaBorderQComponent.Normal, and Quantum.BattleDiamondDataQComponent.TravelDirection.
BattleOnDiamondHitPlayer()
void Battle.QSimulation.Diamond.BattleDiamondQSystem.BattleOnDiamondHitPlayer (Frame f, BattleDiamondDataQComponent * diamond, EntityRef diamondEntity, BattlePlayerHitboxQComponent * playerHitbox, EntityRef playerEntity) inline
Quantum System Signal method游못 that gets called when ISignalBattleOnDiamondHitPlayer is sent.
Destroys diamonds when player hits them and increases diamondcounters.
Warning
This method should only be called via Quantum signal.
Parameters
f Current simulation frame.
diamond Pointer to the diamond component.
diamondEntity EntityRef of the diamond.
playerHitbox Pointer to the playerHitbox component.
playerEntity EntityRef of the player.
Implements Quantum.ISignalBattleOnDiamondHitPlayer.
References Quantum.BattleDiamondCounterQSingleton.AlphaDiamonds, Quantum.BattleDiamondCounterQSingleton.BetaDiamonds, Quantum.BattleDiamondDataQComponent.IsTraveling, and Quantum.BattlePlayerHitboxQComponent.PlayerEntity.
CreateDiamonds()
void Battle.QSimulation.Diamond.BattleDiamondQSystem.CreateDiamonds (Frame f, FPVector2 wallPosition, FPVector2 wallNormal, BattleDiamondQSpec diamondSpec) inline static private
Creates diamonds.
Diamonds are assigned a target vertical distance to travel, a starting direction to begin traveling in and spawned at the destroyed soulwalls position.
Parameters
f Current simulation frame.
wallPosition Position of the soulwall where the diamonds spawn at.
wallNormal Normal of the SoulWall.
diamondSpec The DiamondSpec.
References Battle.QSimulation.Diamond.BattleDiamondQSpec.DiamondPrototype, Quantum.BattleDiamondDataQComponent.IsTraveling, Battle.QSimulation.Diamond.BattleDiamondQSpec.SpawnAmount, Battle.QSimulation.Diamond.BattleDiamondQSpec.SpawnAngleDeg, Quantum.BattleDiamondDataQComponent.StartPosition, Quantum.BattleDiamondDataQComponent.TargetDistance, Quantum.BattleDiamondDataQComponent.TravelDirection, Battle.QSimulation.Diamond.BattleDiamondQSpec.TravelDistanceMax, Battle.QSimulation.Diamond.BattleDiamondQSpec.TravelDistanceMin, Battle.QSimulation.Diamond.BattleDiamondQSpec.TravelSpeed, and Quantum.BattleDiamondDataQComponent.TravelSpeed.
Referenced by OnProjectileHitSoulWall().
OnProjectileHitSoulWall()
void Battle.QSimulation.Diamond.BattleDiamondQSystem.OnProjectileHitSoulWall (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, BattleCollisionQSystem.SoulWallCollisionData * soulWallCollisionData) inline static
A method called by BattleCollisionQSystem when the projectile collides with a soul wall. If the projectile is not in the held state, calls CreateDiamonds to spawn a diamond.
Parameters
f Current simulation frame.
projectileCollisionData Collision data related to the projectile.
soulWallCollisionData Collision data related to the soul wall.
References CreateDiamonds(), and Battle.QSimulation.Game.BattleQConfig.GetDiamondSpec().
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
Update()
override void Battle.QSimulation.Diamond.BattleDiamondQSystem.Update (Frame f, ref Filter filter) inline
Quantum System Update method游못 gets called every frame.
Updates each diamond's position and speed while they are traveling. Manages each diamond's lifetime and destroys them if players don't gather them quickly enough.
Warning
This method should only be called by Quantum.
Parameters
f Current simulation frame.
filter Reference to Quantum Filter游못.
References Battle.QSimulation.Diamond.BattleDiamondQSpec.BreakDistance, Battle.QSimulation.Game.BattleQConfig.GetDiamondSpec(), Quantum.BattleDiamondDataQComponent.IsTraveling, Battle.QSimulation.Diamond.BattleDiamondQSpec.LifetimeSec, Quantum.BattleDiamondDataQComponent.LifetimeTimer, Quantum.BattleDiamondDataQComponent.StartPosition, Quantum.BattleDiamondDataQComponent.TargetDistance, Quantum.BattleDiamondDataQComponent.TravelDirection, and Quantum.BattleDiamondDataQComponent.TravelSpeed.
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Diamonds/BattleDiamondQSystem.cs