Battle: QuantumUser.Scripts.GameViewController Class Reference
QuantumUser.Scripts.GameViewController Class Reference
Private Member Functions
void Awake ()
void OnChangeEmotionState (EventChangeEmotionState e)
void OnGridSet (EventGridSet e)
void OnUpdateDebugStatsOverlay (EventUpdateDebugStatsOverlay e)
void Update ()
Private Attributes
GridViewController _gridViewController
GameUiController _gameUiController
ScreenEffectViewController _screenEffectViewController
Member Function Documentation
Awake()
void QuantumUser.Scripts.GameViewController.Awake () inline private
References _gridViewController, OnChangeEmotionState(), OnGridSet(), and OnUpdateDebugStatsOverlay().
OnChangeEmotionState()
void QuantumUser.Scripts.GameViewController.OnChangeEmotionState (EventChangeEmotionState e) inline private
References _screenEffectViewController, and Quantum.EventChangeEmotionState.Emotion.
Referenced by Awake().
OnGridSet()
void QuantumUser.Scripts.GameViewController.OnGridSet (EventGridSet e) inline private
References _gridViewController.
Referenced by Awake().
OnUpdateDebugStatsOverlay()
void QuantumUser.Scripts.GameViewController.OnUpdateDebugStatsOverlay (EventUpdateDebugStatsOverlay e) inline private
References _gameUiController, and Quantum.EventUpdateDebugStatsOverlay.Character.
Referenced by Awake().
Update()
void QuantumUser.Scripts.GameViewController.Update () inline private
References _gameUiController, Quantum.GameSession.state, Quantum.GameSession.TimeUntilStart, and Utils.TryGetQuantumFrame().
Member Data Documentation
_gameUiController
GameUiController QuantumUser.Scripts.GameViewController._gameUiController private
Referenced by OnUpdateDebugStatsOverlay(), and Update().
_gridViewController
GridViewController QuantumUser.Scripts.GameViewController._gridViewController private
Referenced by Awake(), and OnGridSet().
_screenEffectViewController
ScreenEffectViewController QuantumUser.Scripts.GameViewController._screenEffectViewController private
Referenced by OnChangeEmotionState().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Scripts/Game/GameViewController.cs