Battle: Quantum.Prototypes.ProjectilePrototype Class Reference
Quantum.Prototypes.ProjectilePrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.Projectile result, in PrototypeMaterializationContext context=default)
Public Attributes
QBoolean IsLaunched
FP Speed
FPVector2 Direction
FP Radius
Quantum.QEnum32< EmotionState > Emotion
Quantum.QEnum8< ProjectileCollisionFlags >[] CollisionFlags = new Quantum.QEnum8<ProjectileCollisionFlags>[2]
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.Projectile result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.ProjectilePrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.ProjectilePrototype.Materialize (Frame frame, ref Quantum.Projectile result, in PrototypeMaterializationContext context = default) inline
References CollisionFlags, and MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.ProjectilePrototype.MaterializeUser (Frame frame, ref Quantum.Projectile result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
CollisionFlags
Quantum.QEnum8<ProjectileCollisionFlags> [] Quantum.Prototypes.ProjectilePrototype.CollisionFlags = new Quantum.QEnum8<ProjectileCollisionFlags>[2]
Referenced by Materialize().
Direction
FPVector2 Quantum.Prototypes.ProjectilePrototype.Direction
Emotion
Quantum.QEnum32<EmotionState> Quantum.Prototypes.ProjectilePrototype.Emotion
IsLaunched
QBoolean Quantum.Prototypes.ProjectilePrototype.IsLaunched
Radius
FP Quantum.Prototypes.ProjectilePrototype.Radius
Speed
FP Quantum.Prototypes.ProjectilePrototype.Speed
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs