Battle: Quantum.Prototypes.InputPrototype Class Reference
Quantum.Prototypes.InputPrototype Class Reference
Public Member Functions
void Materialize (Frame frame, ref Quantum.Input result, in PrototypeMaterializationContext context=default)
Public Attributes
QBoolean IsValid
Int32 DebugNumber
Quantum.QEnum32< BattleMovementInputType > MovementInput
QBoolean MovementDirectionIsNormalized
Quantum.Prototypes.BattleGridPositionPrototype MovementPositionTarget
FPVector2 MovementPositionMove
FPVector2 MovementDirection
QBoolean RotationInput
FP RotationValue
QBoolean AbilityActivate
Int32 PlayerCharacterNumber
QBoolean GiveUpInput
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.Input result, in PrototypeMaterializationContext context)
Member Function Documentation
Materialize()
void Quantum.Prototypes.InputPrototype.Materialize (Frame frame, ref Quantum.Input result, in PrototypeMaterializationContext context = default) inline
References Quantum.Prototypes.BattleGridPositionPrototype.Materialize(), and MaterializeUser().
MaterializeUser()
partial void Quantum.Prototypes.InputPrototype.MaterializeUser (Frame frame, ref Quantum.Input result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
AbilityActivate
QBoolean Quantum.Prototypes.InputPrototype.AbilityActivate
DebugNumber
Int32 Quantum.Prototypes.InputPrototype.DebugNumber
GiveUpInput
QBoolean Quantum.Prototypes.InputPrototype.GiveUpInput
IsValid
QBoolean Quantum.Prototypes.InputPrototype.IsValid
MovementDirection
FPVector2 Quantum.Prototypes.InputPrototype.MovementDirection
MovementDirectionIsNormalized
QBoolean Quantum.Prototypes.InputPrototype.MovementDirectionIsNormalized
MovementInput
Quantum.QEnum32<BattleMovementInputType> Quantum.Prototypes.InputPrototype.MovementInput
MovementPositionMove
FPVector2 Quantum.Prototypes.InputPrototype.MovementPositionMove
MovementPositionTarget
Quantum.Prototypes.BattleGridPositionPrototype Quantum.Prototypes.InputPrototype.MovementPositionTarget
PlayerCharacterNumber
Int32 Quantum.Prototypes.InputPrototype.PlayerCharacterNumber
RotationInput
QBoolean Quantum.Prototypes.InputPrototype.RotationInput
RotationValue
FP Quantum.Prototypes.InputPrototype.RotationValue
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs