Battle: Quantum.GridManager Class Reference
Quantum.GridManager Class Reference
Static Public Member Functions
static void Init (BattleArenaSpec battleArenaSpec)
static int WorldXPositionToGridCol (FP x)
static int WorldYPositionToGridRow (FP y)
static FP GridRowToWorldYPosition (int row)
static FP GridColToWorldXPosition (int col)
static GridPosition WorldPositionToGridPosition (FPVector2 wordPosition)
static FPVector2 GridPositionToWorldPosition (GridPosition gridPosition)
Properties
static int Rows [get, private set]
static int Columns [get, private set]
static int TeamAlphaFieldStart [get, private set]
static int TeamAlphaFieldEnd [get, private set]
static int TeamBetaFieldStart [get, private set]
static int TeamBetaFieldEnd [get, private set]
static FP GridScaleFactor [get, private set]
Static Private Attributes
static FPVector2 s_gridOffset
Member Function Documentation
GridColToWorldXPosition()
static FP Quantum.GridManager.GridColToWorldXPosition (int col) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Quantum.PlayerManager.PlayerHandle.GetOutOfPlayPosition(), GridPositionToWorldPosition(), and Quantum.GridViewController.SetGrid().
GridPositionToWorldPosition()
static FPVector2 Quantum.GridManager.GridPositionToWorldPosition (GridPosition gridPosition) inline static
References Quantum.GridPosition.Col, GridColToWorldXPosition(), GridRowToWorldYPosition(), and Quantum.GridPosition.Row.
Referenced by Quantum.PlayerManager.Init(), and Quantum.PlayerMovementSystem.UpdatePlayerMovement().
GridRowToWorldYPosition()
static FP Quantum.GridManager.GridRowToWorldYPosition (int row) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Quantum.PlayerManager.PlayerHandle.GetOutOfPlayPosition(), GridPositionToWorldPosition(), and Quantum.GridViewController.SetGrid().
Init()
static void Quantum.GridManager.Init (BattleArenaSpec battleArenaSpec) inline static
References Columns, Quantum.BattleArenaSpec.GridHeight, GridScaleFactor, Quantum.BattleArenaSpec.GridWidth, Quantum.BattleArenaSpec.MiddleAreaHeight, Rows, s_gridOffset, TeamAlphaFieldEnd, TeamAlphaFieldStart, TeamBetaFieldEnd, TeamBetaFieldStart, and Quantum.BattleArenaSpec.WorldHeight.
Referenced by Quantum.GameControlSystem.OnInit().
WorldPositionToGridPosition()
static GridPosition Quantum.GridManager.WorldPositionToGridPosition (FPVector2 wordPosition) inline static
References WorldXPositionToGridCol(), and WorldYPositionToGridRow().
WorldXPositionToGridCol()
static int Quantum.GridManager.WorldXPositionToGridCol (FP x) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Quantum.PlayerInput.PollInput(), and WorldPositionToGridPosition().
WorldYPositionToGridRow()
static int Quantum.GridManager.WorldYPositionToGridRow (FP y) inline static
References GridScaleFactor, and s_gridOffset.
Referenced by Quantum.PlayerInput.PollInput(), and WorldPositionToGridPosition().
Member Data Documentation
s_gridOffset
FPVector2 Quantum.GridManager.s_gridOffset static private
Referenced by GridColToWorldXPosition(), GridRowToWorldYPosition(), Init(), WorldXPositionToGridCol(), and WorldYPositionToGridRow().
Property Documentation
Columns
int Quantum.GridManager.Columns static get private set
Referenced by Quantum.PlayerManager.PlayerHandle.GetOutOfPlayPosition(), Init(), and Quantum.GridViewController.SetGrid().
GridScaleFactor
FP Quantum.GridManager.GridScaleFactor static get private set
Referenced by GridColToWorldXPosition(), GridRowToWorldYPosition(), Init(), Quantum.PlayerManager.InitPlayer(), Quantum.GridViewController.SetGrid(), WorldXPositionToGridCol(), and WorldYPositionToGridRow().
Rows
int Quantum.GridManager.Rows static get private set
Referenced by Quantum.PlayerManager.PlayerHandle.GetOutOfPlayPosition(), Init(), and Quantum.GridViewController.SetGrid().
TeamAlphaFieldEnd
int Quantum.GridManager.TeamAlphaFieldEnd static get private set
Referenced by Init(), and Quantum.GridViewController.SetGrid().
TeamAlphaFieldStart
int Quantum.GridManager.TeamAlphaFieldStart static get private set
Referenced by Init().
TeamBetaFieldEnd
int Quantum.GridManager.TeamBetaFieldEnd static get private set
Referenced by Init().
TeamBetaFieldStart
int Quantum.GridManager.TeamBetaFieldStart static get private set
Referenced by Init(), and Quantum.GridViewController.SetGrid().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Scripts/Grid/GridManager.cs