Battle: Battle.QSimulation.Game.BattleCollisionQSystem Class Reference
Battle.QSimulation.Game.BattleCollisionQSystem Class Reference
Collision Quantum SystemSignalsOnly游못 [Systems]
Handles all collisions in the game. Reacts only when it receives a signal upon collision.
Classes
struct ProjectileCollisionData
struct ArenaBorderCollisionData
struct SoulWallCollisionData
struct PlayerCharacterCollisionData
struct PlayerShieldCollisionData
struct GoalCollisionData
Public Member Functions
void OnTrigger2D (Frame f, TriggerInfo2D info)
Quantum System Signal method游못 that gets called when ISignalOnTrigger2D游못 is sent.
Handles all 2D trigger collisions in the game.
Routes projectile collisions to the correct systems based on the type of object hit.
Static Public Member Functions
static void Init ()
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
Static Private Attributes
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
Detailed Description
Collision Quantum SystemSignalsOnly游못 [Systems]
Handles all collisions in the game. Reacts only when it receives a signal upon collision.
This system reacts to ISignalOnTrigger2D signals. Depending on which entities are colliding, the appropriate methods in other systems are called.
Member Function Documentation
Init()
void Battle.QSimulation.Game.BattleCollisionQSystem.Init () inline static
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
References Battle.QSimulation.BattleDebugLogger.Create(), and s_debugLogger.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
OnTrigger2D()
void Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D (Frame f, TriggerInfo2D info) inline
Quantum System Signal method游못 that gets called when ISignalOnTrigger2D游못 is sent.
Handles all 2D trigger collisions in the game.
Routes projectile collisions to the correct systems based on the type of object hit.
Warning
This method should only be called via Quantum signal.
Parameters
f Current simulation frame.
info Trigger collision information.
References Quantum.ArenaBorder, Battle.QSimulation.Projectile.BattleProjectileQSystem.IsCollisionFlagSet(), Battle.QSimulation.Projectile.BattleProjectileQSystem.OnProjectileCollision(), Battle.QSimulation.Goal.BattleGoalQSystem.OnProjectileHitGoal(), Battle.QSimulation.Player.BattlePlayerClassManager.OnProjectileHitPlayerCharacter(), Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerCharacter(), Battle.QSimulation.Player.BattlePlayerClassManager.OnProjectileHitPlayerShield(), Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerShield(), Battle.QSimulation.Diamond.BattleDiamondQSystem.OnProjectileHitSoulWall(), Battle.QSimulation.SoulWall.BattleSoulWallQSystem.OnProjectileHitSoulWall(), and s_debugLogger.
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.QSimulation.Game.BattleCollisionQSystem.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by Init(), and OnTrigger2D().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleCollisionQSystem.cs