Battle: Battle.QSimulation.SoulWall.BattleSoulWallQSystem Class Reference
Battle.QSimulation.SoulWall.BattleSoulWallQSystem Class Reference
SoulWall Quantum SystemSignalsOnly游못 [Systems]
Handles creating SoulWalls and reacting to the projectile colliding with them.
Static Public Member Functions
static void Init ()
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
static void CreateSoulWalls (Frame f, BattleArenaQSpec battleArenaSpec, BattleSoulWallQSpec soulWallSpec)
Creates soulwalls based on BattleArena and SoulWall Specs during map creation phase.
static void CreateAbilitySoulWallTest (Frame f, BattleTeamNumber teamNumber, FPVector2 spawnPosition)
Temporary method for ability testing.
static void OnProjectileHitSoulWall (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.SoulWallCollisionData *soulWallCollisionData)
Called by BattleCollisionQSystem. Destroys the soulwall entity that was hit and sends forward the appropriate event that spawns a lightray if the soul wall hit was in the last row.
Static Private Member Functions
static void CreateSoulWalls (Frame f, BattleTeamNumber teamNumber, BattleSoulWallTemplate[] soulWallTemplates, AssetRef< EntityPrototype >[] soulWallPrototypes)
Private helper method (for the public CreateSoulWalls) that creates soulwalls on one side of the arena.
Static Private Attributes
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
Detailed Description
SoulWall Quantum SystemSignalsOnly游못 [Systems]
Handles creating SoulWalls and reacting to the projectile colliding with them.
This system creates SoulWalls based on BattleArena and SoulWall Specs when GameControlSystem calls CreateSoulWalls method during the map creation.
Also destroys SoulWall segment when BattleCollisionQSystem calls the collision method.
Member Function Documentation
CreateAbilitySoulWallTest()
void Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateAbilitySoulWallTest (Frame f, BattleTeamNumber teamNumber, FPVector2 spawnPosition) inline static
Temporary method for ability testing.
References Quantum.BattleSoulWallQComponent.CollisionMinOffset, Quantum.BattleSoulWallQComponent.Emotion, Battle.QSimulation.Game.BattleQConfig.GetSoulWallSpec(), Battle.QSimulation.Game.BattleGridManager.GridScaleFactor, Quantum.BattleSoulWallQComponent.Normal, Quantum.BattleSoulWallQComponent.Row, Quantum.BattleSoulWallQComponent.Team, and Quantum.BattleSoulWallQComponent.WallNumber.
CreateSoulWalls() [1/2]
void Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateSoulWalls (Frame f, BattleArenaQSpec battleArenaSpec, BattleSoulWallQSpec soulWallSpec) inline static
Creates soulwalls based on BattleArena and SoulWall Specs during map creation phase.
Warning
This method should only be called once by GameControlSystem during the map creation
Parameters
f Current simulation frame.
battleArenaSpec The BattleArenaSpec.
soulWallSpec The SoulWallSpec.
References CreateSoulWalls(), Battle.QSimulation.SoulWall.BattleSoulWallQSpec.SoulWallPrototypes, Battle.QSimulation.Game.BattleArenaQSpec.SoulWallTeamAlphaTemplates, and Battle.QSimulation.Game.BattleArenaQSpec.SoulWallTeamBetaTemplates.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.CreateMap(), and CreateSoulWalls().
CreateSoulWalls() [2/2]
void Battle.QSimulation.SoulWall.BattleSoulWallQSystem.CreateSoulWalls (Frame f, BattleTeamNumber teamNumber, BattleSoulWallTemplate[] soulWallTemplates, AssetRef< EntityPrototype >[] soulWallPrototypes) inline static private
Private helper method (for the public CreateSoulWalls) that creates soulwalls on one side of the arena.
Parameters
f Current simulation frame.
teamNumber The teamNumber of the team whose side is being created.
soulWallTemplates An array of soulwall templates that are used to create the soulwalls.
soulWallPrototypes An array of entityPrototypes that can be created.
References Quantum.BattleSoulWallTemplate.ColorIndex, Battle.QSimulation.Game.BattleGridManager.GridPositionToWorldPosition(), Battle.QSimulation.Game.BattleGridManager.GridScaleFactor, Quantum.BattleSoulWallTemplate.Position, Quantum.BattleGridPosition.Row, Battle.QSimulation.Game.BattleGridManager.Rows, s_debugLogger, and Quantum.BattleSoulWallTemplate.WidthType.
Init()
void Battle.QSimulation.SoulWall.BattleSoulWallQSystem.Init () inline static
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
References Battle.QSimulation.BattleDebugLogger.Create(), and s_debugLogger.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
OnProjectileHitSoulWall()
void Battle.QSimulation.SoulWall.BattleSoulWallQSystem.OnProjectileHitSoulWall (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, BattleCollisionQSystem.SoulWallCollisionData * soulWallCollisionData) inline static
Called by BattleCollisionQSystem. Destroys the soulwall entity that was hit and sends forward the appropriate event that spawns a lightray if the soul wall hit was in the last row.
Parameters
f Current simulation frame.
projectileCollisionData Collision data related to the projectile.
soulWallCollisionData Collision data related to the soul wall.
References s_debugLogger, and Battle.QSimulation.Projectile.BattleProjectileQSystem.SetCollisionFlag().
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.QSimulation.SoulWall.BattleSoulWallQSystem.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by CreateSoulWalls(), Init(), and OnProjectileHitSoulWall().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/SoulWall/BattleSoulWallQSystem.cs