Battle: Quantum.Prototypes.BattleProjectileQComponentPrototype Class Reference
Quantum.Prototypes.BattleProjectileQComponentPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattleProjectileQComponent result, in PrototypeMaterializationContext context=default)
Public Attributes
QBoolean IsLaunched
QBoolean IsHeld
QBoolean IsPassed
Quantum.QEnum32< BattleEmotionState > EmotionBase
Quantum.QEnum32< BattleEmotionState > EmotionCurrent
Quantum.QEnum8< BattleProjectileCollisionFlags >[] CollisionFlags = new Quantum.QEnum8<BattleProjectileCollisionFlags>[2]
FP Speed
FPVector2 Position
FPVector2 Direction
FP Attack
FP Radius
FP SpeedBase
FP SpeedIncrement
FP SpeedMax
FP AttackMax
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleProjectileQComponent result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattleProjectileQComponentPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattleProjectileQComponentPrototype.Materialize (Frame frame, ref Quantum.BattleProjectileQComponent result, in PrototypeMaterializationContext context = default) inline
References CollisionFlags, and MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattleProjectileQComponentPrototype.MaterializeUser (Frame frame, ref Quantum.BattleProjectileQComponent result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
Attack
FP Quantum.Prototypes.BattleProjectileQComponentPrototype.Attack
AttackMax
FP Quantum.Prototypes.BattleProjectileQComponentPrototype.AttackMax
CollisionFlags
Quantum.QEnum8<BattleProjectileCollisionFlags> [] Quantum.Prototypes.BattleProjectileQComponentPrototype.CollisionFlags = new Quantum.QEnum8<BattleProjectileCollisionFlags>[2]
Referenced by Materialize().
Direction
FPVector2 Quantum.Prototypes.BattleProjectileQComponentPrototype.Direction
EmotionBase
Quantum.QEnum32<BattleEmotionState> Quantum.Prototypes.BattleProjectileQComponentPrototype.EmotionBase
EmotionCurrent
Quantum.QEnum32<BattleEmotionState> Quantum.Prototypes.BattleProjectileQComponentPrototype.EmotionCurrent
IsHeld
QBoolean Quantum.Prototypes.BattleProjectileQComponentPrototype.IsHeld
IsLaunched
QBoolean Quantum.Prototypes.BattleProjectileQComponentPrototype.IsLaunched
IsPassed
QBoolean Quantum.Prototypes.BattleProjectileQComponentPrototype.IsPassed
Position
FPVector2 Quantum.Prototypes.BattleProjectileQComponentPrototype.Position
Radius
FP Quantum.Prototypes.BattleProjectileQComponentPrototype.Radius
Speed
FP Quantum.Prototypes.BattleProjectileQComponentPrototype.Speed
SpeedBase
FP Quantum.Prototypes.BattleProjectileQComponentPrototype.SpeedBase
SpeedIncrement
FP Quantum.Prototypes.BattleProjectileQComponentPrototype.SpeedIncrement
SpeedMax
FP Quantum.Prototypes.BattleProjectileQComponentPrototype.SpeedMax
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs