Battle: Quantum.Prototypes.BattleSoulWallQComponentPrototype Class Reference
Quantum.Prototypes.BattleSoulWallQComponentPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattleSoulWallQComponent result, in PrototypeMaterializationContext context=default)
Public Attributes
Quantum.QEnum32< BattleTeamNumber > Team
Quantum.QEnum32< BattleSoulWallRow > Row
Int32 WallNumber
Quantum.QEnum32< BattleEmotionState > Emotion
FPVector2 Normal
FP CollisionMinOffset
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleSoulWallQComponent result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattleSoulWallQComponentPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattleSoulWallQComponentPrototype.Materialize (Frame frame, ref Quantum.BattleSoulWallQComponent result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattleSoulWallQComponentPrototype.MaterializeUser (Frame frame, ref Quantum.BattleSoulWallQComponent result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
CollisionMinOffset
FP Quantum.Prototypes.BattleSoulWallQComponentPrototype.CollisionMinOffset
Emotion
Quantum.QEnum32<BattleEmotionState> Quantum.Prototypes.BattleSoulWallQComponentPrototype.Emotion
Normal
FPVector2 Quantum.Prototypes.BattleSoulWallQComponentPrototype.Normal
Row
Quantum.QEnum32<BattleSoulWallRow> Quantum.Prototypes.BattleSoulWallQComponentPrototype.Row
Team
Quantum.QEnum32<BattleTeamNumber> Quantum.Prototypes.BattleSoulWallQComponentPrototype.Team
WallNumber
Int32 Quantum.Prototypes.BattleSoulWallQComponentPrototype.WallNumber
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs