Battle: Battle.QSimulation.Player.BattlePlayerManager Class Reference
Battle.QSimulation.Player.BattlePlayerManager Class Reference
PlayerManager handles player management, allowing other classes to focus on gameplay logic.
Provides static methods to initialize, spawn, despawn, and query player-related data.
Classes
struct PlayerHandle
Public helper struct for getting player information.
struct PlayerHandleInternal
Internal helper struct for player operations and state management in BattlePlayerManager.
Has static helper methods for player operations.
Can be instantiated to handle specific player's data stored in BattlePlayerManagerDataQSingleton.
Static Public Member Functions
static void Init (Frame f, BattleArenaQSpec battleArenaSpec)
Initializes the spawn positions for players.
Sets the initial play state of all players to not in game.
Prevents the game from starting if the amount of players is not what it should be.
static void RegisterPlayer (Frame f, PlayerRef playerRef)
Registers player.
static void MarkAbandoned (Frame f, PlayerRef playerRef)
Marks the player as abandoned.
static bool IsAllPlayersRegistered (Frame f)
Verifies that all players in the game have been registered.
static void CreatePlayers (Frame f)
Creates all character entities for each player in the game, inititalizing data, hitboxes and view components.
static void SpawnPlayer (Frame f, BattlePlayerSlot slot, int characterNumber)
Spawns a player character entity into the game.
Verifies that the player is in the game and the character to be spawned is valid.
Actual spawning handled by a separate private method.
static void DespawnPlayer (Frame f, BattlePlayerSlot slot, bool kill=false)
Despawns a player's active character entity from the game.
Verifies that the player has a character in play.
If kill is set to true, the character's state is marked as dead prior to despawning.
Actual despawning handled by a separate private method.
Static Private Member Functions
static BattlePlayerManagerDataQSingleton * GetPlayerManagerData (Frame f)
Private helper method for getting the BattlePlayerManagerDataQSingleton from the Quantum Frame.
static void SpawnPlayer (Frame f, PlayerHandleInternal playerHandle, int characterNumber)
Spawns a player character entity into the game.
static void DespawnPlayer (Frame f, PlayerHandleInternal playerHandle)
Despawns a player's active character entity from the game.
static void Error (Frame f, string messageformat, params object[] args)
Static Private Attributes
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
static int s_debugOverlayStats
Debug overlay entry number for stats.
static readonly FPVector2[] s_spawnPoints = new FPVector2[Constants.BATTLE_PLAYER_SLOT_COUNT]
Detailed Description
PlayerManager handles player management, allowing other classes to focus on gameplay logic.
Provides static methods to initialize, spawn, despawn, and query player-related data.
{Player Overview}
{Player Simulation Code Overview}
Handles initializing players that are present in the game, as well as spawning and despawning player characters.
Also contains the public and private PlayerHandle structs.
Member Function Documentation
CreatePlayers()
void Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers (Frame f) inline static
Creates all character entities for each player in the game, inititalizing data, hitboxes and view components.
Parameters
f Current simulation frame.
References Quantum.BattlePlayerStats.Attack, Quantum.Constants.BATTLE_PLAYER_CHARACTER_COUNT, Quantum.Constants.BATTLE_PLAYER_SLOT_COUNT, Quantum.BattlePlayerStats.CharacterSize, Quantum.BattlePlayerHitboxTemplate.ColliderTemplateList, Quantum.BattlePlayerHitboxTemplate.CollisionType, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.ConvertToPublic(), Quantum.BattlePlayerDataQComponent.CurrentHp, Quantum.BattlePlayerStats.Defence, Quantum.BattlePlayerDataTemplateQComponent.DisableRotation, Battle.QSimulation.Player.BattlePlayerBotController.GetBotCharacters(), Battle.QSimulation.Game.BattleAltzoneLink.GetCharacterPrototype(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetOutOfPlayPosition(), GetPlayerManagerData(), Battle.QSimulation.Game.BattleParameters.GetPlayerSlotTypes(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetSlot(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetTeamNumber(), Quantum.BattlePlayerDataTemplateQComponent.GridExtendBottom, Quantum.BattlePlayerDataTemplateQComponent.GridExtendTop, Battle.QSimulation.Game.BattleGridManager.GridScaleFactor, Quantum.BattlePlayerDataTemplateQComponent.HitboxCharacter, Quantum.BattlePlayerDataTemplateQComponent.HitboxShield, Quantum.BattlePlayerStats.Hp, Quantum.BattleCharacterBase.Id, Battle.QSimulation.Player.BattlePlayerClassManager.LoadClass(), Quantum.BattlePlayerHitboxTemplate.NormalAngleDeg, Battle.QSimulation.Player.BattlePlayerClassManager.OnCreate(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayerRef, Quantum.BattlePlayerHitboxColliderTemplate.Position, s_debugLogger, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetCharacterEntities(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetCharacterState(), Quantum.BattlePlayerHitboxColliderTemplate.Size, Quantum.BattlePlayerStats.Speed, Quantum.BattleCharacterBase.Stats, Quantum.BattlePlayerDataQComponent.Stats, and Battle.QSimulation.Player.BattlePlayerMovementController.Teleport().
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.CreateMap().
DespawnPlayer() [1/2]
void Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer (Frame f, BattlePlayerSlot slot, bool kill = false) inline static
Despawns a player's active character entity from the game.
Verifies that the player has a character in play.
If kill is set to true, the character's state is marked as dead prior to despawning.
Actual despawning handled by a separate private method.
Parameters
f Current simulation frame.
slot The slot of the player for which the character is to be despawned.
kill If true, marks the character as dead.
References DespawnPlayer(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerHandle(), GetPlayerManagerData(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayState, and s_debugLogger.
Referenced by DespawnPlayer(), Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerCharacter(), and SpawnPlayer().
DespawnPlayer() [2/2]
void Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer (Frame f, PlayerHandleInternal playerHandle) inline static private
Despawns a player's active character entity from the game.
Parameters
f Current simulation frame.
playerHandle PlayerHandle of the player the character will be spawned for.
References Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.ConvertToPublic(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetOutOfPlayPosition(), Battle.QSimulation.Player.BattlePlayerClassManager.OnDespawn(), Quantum.BattlePlayerDataQComponent.PlayerRef, Quantum.BattlePlayerDataQComponent.RotationBase, s_debugLogger, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SelectedCharacterEntity, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SelectedCharacterNumber, Quantum.BattlePlayerDataQComponent.Slot, Quantum.BattlePlayerDataQComponent.TargetPosition, Quantum.BattlePlayerDataQComponent.TeamNumber, Battle.QSimulation.Player.BattlePlayerMovementController.Teleport(), and Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.UnsetSelectedCharacter().
Error()
void Battle.QSimulation.Player.BattlePlayerManager.Error (Frame f, string messageformat, params object[] args) inline static private
References s_debugLogger.
Referenced by Init(), and RegisterPlayer().
GetPlayerManagerData()
BattlePlayerManagerDataQSingleton * Battle.QSimulation.Player.BattlePlayerManager.GetPlayerManagerData (Frame f) inline static private
Private helper method for getting the BattlePlayerManagerDataQSingleton from the Quantum Frame.
Parameters
f
Returns
References s_debugLogger.
Referenced by CreatePlayers(), DespawnPlayer(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandle(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandleArray(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetSlot(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle(), Init(), IsAllPlayersRegistered(), MarkAbandoned(), RegisterPlayer(), and SpawnPlayer().
Init()
void Battle.QSimulation.Player.BattlePlayerManager.Init (Frame f, BattleArenaQSpec battleArenaSpec) inline static
Initializes the spawn positions for players.
Sets the initial play state of all players to not in game.
Prevents the game from starting if the amount of players is not what it should be.
Parameters
f Current simulation frame.
battleArenaSpec The spec of the arena.
References Battle.QSimulation.BattleDebugOverlayLink.AddEntries(), Battle.QSimulation.BattleDebugLogger.Create(), Error(), Battle.QSimulation.Game.BattleParameters.GetPlayerCount(), GetPlayerManagerData(), Battle.QSimulation.Game.BattleParameters.GetPlayerSlotTypes(), Battle.QSimulation.Game.BattleParameters.GetPlayerSlotUserIDs(), Battle.QSimulation.Game.BattleGridManager.GridPositionToWorldPosition(), Quantum.BattlePlayerManagerDataQSingleton.PlayerCount, Battle.QSimulation.Game.BattleArenaQSpec.PlayerSpawnPositions, s_debugLogger, s_debugOverlayStats, s_spawnPoints, and Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetAllPlayStates().
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
IsAllPlayersRegistered()
bool Battle.QSimulation.Player.BattlePlayerManager.IsAllPlayersRegistered (Frame f) inline static
Verifies that all players in the game have been registered.
Parameters
f Current simulation frame.
Returns
True if all players have been registered, false if any have not.
References Battle.QSimulation.Game.BattleParameters.GetPlayerCount(), GetPlayerManagerData(), and Quantum.BattlePlayerManagerDataQSingleton.PlayerCount.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.Update().
MarkAbandoned()
void Battle.QSimulation.Player.BattlePlayerManager.MarkAbandoned (Frame f, PlayerRef playerRef) inline static
Marks the player as abandoned.
Parameters
f Current simulation frame.
playerRef Reference to the player.
References Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.ConvertToPublic(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerIndex(), GetPlayerManagerData(), and Battle.QSimulation.Player.BattlePlayerQSystem.HandlePlayerAbandoned().
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnPlayerDisconnected().
RegisterPlayer()
void Battle.QSimulation.Player.BattlePlayerManager.RegisterPlayer (Frame f, PlayerRef playerRef) inline static
Registers player.
Parameters
f Current Quantum Frame.
playerRef Reference to the player.
References Error(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerHandle(), GetPlayerManagerData(), Battle.QSimulation.Game.BattleParameters.GetPlayerSlotTypes(), Battle.QSimulation.Game.BattleParameters.GetPlayerSlotUserIDs(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.Index, Quantum.BattlePlayerManagerDataQSingleton.PlayerCount, Quantum.RuntimePlayer.PlayerSlot, s_debugLogger, and Quantum.RuntimePlayer.UserID.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnPlayerAdded().
SpawnPlayer() [1/2]
void Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer (Frame f, BattlePlayerSlot slot, int characterNumber) inline static
Spawns a player character entity into the game.
Verifies that the player is in the game and the character to be spawned is valid.
Actual spawning handled by a separate private method.
Parameters
f Current simulation frame.
slot The slot of the player for which the character is to be spawned.
characterNumber The character number of the character to be spawned.
References Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetCharacterState(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerHandle(), GetPlayerManagerData(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.IsValidCharacterNumber(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayState, s_debugLogger, and SpawnPlayer().
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.HandleCharacterSwapping(), Battle.QSimulation.Player.BattlePlayerQSystem.HandleOutOfPlay(), SpawnPlayer(), and Battle.QSimulation.Player.BattlePlayerQSystem.SpawnPlayers().
SpawnPlayer() [2/2]
void Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer (Frame f, PlayerHandleInternal playerHandle, int characterNumber) inline static private
Spawns a player character entity into the game.
Parameters
f Current simulation frame.
playerHandle PlayerHandle of the player the character will be spawned for.
characterNumber The character number of the character to be spawned.
References Quantum.BattlePlayerDataQComponent.AbilityActivateBufferSec, Quantum.BattlePlayerDataQComponent.AbilityCooldownSec, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.ConvertToPublic(), DespawnPlayer(), Quantum.BattlePlayerDataQComponent.DisableRotation, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetCharacterEntity(), Battle.QSimulation.Player.BattlePlayerClassManager.OnSpawn(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayerRef, Quantum.BattlePlayerDataQComponent.PlayerRef, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayState, Quantum.BattlePlayerDataQComponent.RotationBase, s_debugLogger, s_debugOverlayStats, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SelectedCharacterEntity, Battle.QSimulation.BattleDebugOverlayLink.SetEntries(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetSelectedCharacter(), Quantum.BattlePlayerDataQComponent.Slot, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SpawnPosition, Quantum.BattlePlayerDataQComponent.TargetPosition, and Battle.QSimulation.Player.BattlePlayerMovementController.Teleport().
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.QSimulation.Player.BattlePlayerManager.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by CreatePlayers(), DespawnPlayer(), DespawnPlayer(), Error(), GetPlayerManagerData(), Init(), RegisterPlayer(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SetOutOfPlayFinal(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SetOutOfPlayRespawning(), SpawnPlayer(), and SpawnPlayer().
s_debugOverlayStats
int Battle.QSimulation.Player.BattlePlayerManager.s_debugOverlayStats static private
Debug overlay entry number for stats.
Referenced by Init(), and SpawnPlayer().
s_spawnPoints
readonly FPVector2 [] Battle.QSimulation.Player.BattlePlayerManager.s_spawnPoints = new FPVector2[Constants.BATTLE_PLAYER_SLOT_COUNT] static private
Referenced by Init().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerManager.cs