Battle: Quantum.Prototypes.BattleGameSessionQSingletonPrototype Class Reference
Quantum.Prototypes.BattleGameSessionQSingletonPrototype Class Reference
Public Member Functions
override Boolean AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context)
void Materialize (Frame frame, ref Quantum.BattleGameSessionQSingleton result, in PrototypeMaterializationContext context=default)
Public Attributes
QBoolean GameInitialized
Quantum.QEnum32< BattleGameState > State
FP LoadDelaySec
FP TimeUntilStartSec
FP GameTimeSec
Private Member Functions
partial void MaterializeUser (Frame frame, ref Quantum.BattleGameSessionQSingleton result, in PrototypeMaterializationContext context)
Member Function Documentation
AddToEntity()
override Boolean Quantum.Prototypes.BattleGameSessionQSingletonPrototype.AddToEntity (FrameBase f, EntityRef entity, in PrototypeMaterializationContext context) inline
References Materialize().
Materialize()
void Quantum.Prototypes.BattleGameSessionQSingletonPrototype.Materialize (Frame frame, ref Quantum.BattleGameSessionQSingleton result, in PrototypeMaterializationContext context = default) inline
References MaterializeUser().
Referenced by AddToEntity().
MaterializeUser()
partial void Quantum.Prototypes.BattleGameSessionQSingletonPrototype.MaterializeUser (Frame frame, ref Quantum.BattleGameSessionQSingleton result, in PrototypeMaterializationContext context) private
Referenced by Materialize().
Member Data Documentation
GameInitialized
QBoolean Quantum.Prototypes.BattleGameSessionQSingletonPrototype.GameInitialized
GameTimeSec
FP Quantum.Prototypes.BattleGameSessionQSingletonPrototype.GameTimeSec
LoadDelaySec
FP Quantum.Prototypes.BattleGameSessionQSingletonPrototype.LoadDelaySec
State
Quantum.QEnum32<BattleGameState> Quantum.Prototypes.BattleGameSessionQSingletonPrototype.State
TimeUntilStartSec
FP Quantum.Prototypes.BattleGameSessionQSingletonPrototype.TimeUntilStartSec
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Prototypes.cs