Battle: Battle.View.Player.BattlePlayerViewController Class Reference
Battle.View.Player.BattlePlayerViewController Class Reference
Player's QuantumEntityViewComponent游못.
Handles player view logic.
Public Member Functions
override void OnActivate (Frame _)
Public method that is called when entity is activated upon its creation.
Calls PreInitSetup and subscribes to EventBattlePlayerViewInit event with a lambda, which sets the player model scale and active GameObjects游못. Handles subscribing to QuantumEvents.
override void OnUpdateView ()
Public method that is called when the view should update.
Calls UpdateModelPositionAdjustment to update the player model's position.
Private Member Functions
void PreInitSetup ()
Handles setup that needs to happen before EventBattlePlayerViewInit event is received.
Currently this is needed for initializing character's class as none.
void UpdateModelPositionAdjustment (Vector3 *targetPosition)
Updates the player model's position.
void UpdateAnimator (Vector3 *targetPosition, BattleTeamNumber battleTeamNumber)
Updates the player model's animator.
void QEventOnCharacterTakeDamage (EventBattleCharacterTakeDamage e)
Handler method for EventBattleCharacterTakeDamage QuantumEvent.
Starts DamageFlashCoroutine.
void QEventOnShieldTakeDamage (EventBattleShieldTakeDamage e)
Handler method for EventBattleShieldTakeDamage QuantumEvent.
.
IEnumerator DamageFlashCoroutine ()
Coroutine which plays the damage flash animation.
Private Attributes
BattleDebugLogger _debugLogger
This classes BattleDebugLogger instance.
SpriteRenderer _spriteRenderer
Reference to the active character's SpriteRenderer游못.
Coroutine _damageFlashCoroutine = null
Holder variable for the damage flash coroutine.
BattlePlayerClassBaseViewController _classViewController
Reference to the active class view controller.
SerializeField variables
SerializeFields游못 are serialized variables exposed to the Unity editor.
BattlePlayerClassBaseViewController _classViewControllerOverride
[SerializeField] Reference to an override class view controller.
Animator _animator
[SerializeField] Animator GameObject游못 that handles player animations.
GameObject[] _characterGameObjects
[SerializeField] Player's child GameObject游못 where heart sprite is located.
GameObject _localPlayerIndicator
[SerializeField] Player's local player indicator GameObject游못.
Sprite _noShieldSprite
[SerializeField] Reference to a character sprite without shield.
ParticleSystem _shieldHitParticle
[SerializeField] Reference to the shield hit particle system.
float _transparencyEffectRange
[SerializeField] The transparency effect's range.
float _transparencyEffectTransitionRate
[SerializeField] The transparency effect's transition rate.
float _transparencyEffectMinimumAlpha
[SerializeField] The transparency effect's minimum alpha value..
float _damageFlashDuration = 1f
[SerializeField] The damage flash animation's duration.
int _damageFlashAmount = 5
[SerializeField] The amount of damage flashes.
Detailed Description
Player's QuantumEntityViewComponent游못.
Handles player view logic.
{Player Overview}
{Player View Code Overview}
Member Function Documentation
DamageFlashCoroutine()
IEnumerator Battle.View.Player.BattlePlayerViewController.DamageFlashCoroutine () inline private
Coroutine which plays the damage flash animation.
Returns
Coroutine IEnumerator.
References _damageFlashAmount, _damageFlashDuration, and _spriteRenderer.
Referenced by QEventOnCharacterTakeDamage().
OnActivate()
override void Battle.View.Player.BattlePlayerViewController.OnActivate (Frame _) inline
Public method that is called when entity is activated upon its creation.
Calls PreInitSetup and subscribes to EventBattlePlayerViewInit event with a lambda, which sets the player model scale and active GameObjects游못. Handles subscribing to QuantumEvents.
Parameters
_ Current simulation frame.
References _characterGameObjects, _classViewController, _classViewControllerOverride, _debugLogger, _localPlayerIndicator, _spriteRenderer, Quantum.EventBattlePlayerViewInit.CharacterId, Quantum.EventBattlePlayerViewInit.Class, Quantum.EventBattlePlayerViewInit.Entity, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeamNumber(), Battle.View.Game.BattleGameViewController.LocalPlayerSlot, Battle.View.Game.BattleGameViewController.LocalPlayerTeam, Quantum.EventBattlePlayerViewInit.ModelScale, PreInitSetup(), QEventOnCharacterTakeDamage(), QEventOnShieldTakeDamage(), and Quantum.EventBattlePlayerViewInit.Slot.
OnUpdateView()
override void Battle.View.Player.BattlePlayerViewController.OnUpdateView () inline
Public method that is called when the view should update.
Calls UpdateModelPositionAdjustment to update the player model's position.
References _classViewController, Quantum.BattlePlayerDataQComponent.PlayerRef, Quantum.BattlePlayerDataQComponent.TargetPosition, Quantum.BattlePlayerDataQComponent.TeamNumber, and UpdateModelPositionAdjustment().
PreInitSetup()
void Battle.View.Player.BattlePlayerViewController.PreInitSetup () inline private
Handles setup that needs to happen before EventBattlePlayerViewInit event is received.
Currently this is needed for initializing character's class as none.
References _classViewController, _debugLogger, and Battle.QSimulation.BattleDebugLogger.Create().
Referenced by OnActivate().
QEventOnCharacterTakeDamage()
void Battle.View.Player.BattlePlayerViewController.QEventOnCharacterTakeDamage (EventBattleCharacterTakeDamage e) inline private
Handler method for EventBattleCharacterTakeDamage QuantumEvent.
Starts DamageFlashCoroutine.
Parameters
e The event data.
References _classViewController, _damageFlashCoroutine, DamageFlashCoroutine(), and Quantum.EventBattleCharacterTakeDamage.Entity.
Referenced by OnActivate().
QEventOnShieldTakeDamage()
void Battle.View.Player.BattlePlayerViewController.QEventOnShieldTakeDamage (EventBattleShieldTakeDamage e) inline private
Handler method for EventBattleShieldTakeDamage QuantumEvent.
.
Parameters
e The event data.
References _classViewController, _noShieldSprite, _shieldHitParticle, Quantum.EventBattleShieldTakeDamage.DefenceValue, and Quantum.EventBattleShieldTakeDamage.Entity.
Referenced by OnActivate().
UpdateAnimator()
void Battle.View.Player.BattlePlayerViewController.UpdateAnimator (Vector3 * targetPosition, BattleTeamNumber battleTeamNumber) inline private
Updates the player model's animator.
Parameters
targetPosition Target position Vector3.
battleTeamNumber The BattleTeamNumber for the player.
References _animator.
UpdateModelPositionAdjustment()
void Battle.View.Player.BattlePlayerViewController.UpdateModelPositionAdjustment (Vector3 * targetPosition) inline private
Updates the player model's position.
Parameters
targetPosition Target position Vector3.
Referenced by OnUpdateView().
Member Data Documentation
_animator
Animator Battle.View.Player.BattlePlayerViewController._animator private
[SerializeField] Animator GameObject游못 that handles player animations.
BattlePlayerViewController-SerializeFields
Referenced by UpdateAnimator().
_characterGameObjects
GameObject [] Battle.View.Player.BattlePlayerViewController._characterGameObjects private
[SerializeField] Player's child GameObject游못 where heart sprite is located.
BattlePlayerViewController-SerializeFields
[SerializeField] Array of character GameObjects游못. BattlePlayerViewController-SerializeFields
Referenced by OnActivate().
_classViewController
BattlePlayerClassBaseViewController Battle.View.Player.BattlePlayerViewController._classViewController private
Reference to the active class view controller.
Referenced by OnActivate(), OnUpdateView(), PreInitSetup(), QEventOnCharacterTakeDamage(), and QEventOnShieldTakeDamage().
_classViewControllerOverride
BattlePlayerClassBaseViewController Battle.View.Player.BattlePlayerViewController._classViewControllerOverride private
[SerializeField] Reference to an override class view controller.
BattlePlayerViewController-SerializeFields
Referenced by OnActivate().
_damageFlashAmount
int Battle.View.Player.BattlePlayerViewController._damageFlashAmount = 5 private
[SerializeField] The amount of damage flashes.
BattlePlayerViewController-SerializeFields
Referenced by DamageFlashCoroutine().
_damageFlashCoroutine
Coroutine Battle.View.Player.BattlePlayerViewController._damageFlashCoroutine = null private
Holder variable for the damage flash coroutine.
Referenced by QEventOnCharacterTakeDamage().
_damageFlashDuration
float Battle.View.Player.BattlePlayerViewController._damageFlashDuration = 1f private
[SerializeField] The damage flash animation's duration.
BattlePlayerViewController-SerializeFields
Referenced by DamageFlashCoroutine().
_debugLogger
BattleDebugLogger Battle.View.Player.BattlePlayerViewController._debugLogger private
This classes BattleDebugLogger instance.
Referenced by OnActivate(), and PreInitSetup().
_localPlayerIndicator
GameObject Battle.View.Player.BattlePlayerViewController._localPlayerIndicator private
[SerializeField] Player's local player indicator GameObject游못.
BattlePlayerViewController-SerializeFields
Referenced by OnActivate().
_noShieldSprite
Sprite Battle.View.Player.BattlePlayerViewController._noShieldSprite private
[SerializeField] Reference to a character sprite without shield.
BattlePlayerViewController-SerializeFields
Referenced by QEventOnShieldTakeDamage().
_shieldHitParticle
ParticleSystem Battle.View.Player.BattlePlayerViewController._shieldHitParticle private
[SerializeField] Reference to the shield hit particle system.
BattlePlayerViewController-SerializeFields
Referenced by QEventOnShieldTakeDamage().
_spriteRenderer
SpriteRenderer Battle.View.Player.BattlePlayerViewController._spriteRenderer private
Reference to the active character's SpriteRenderer游못.
Referenced by DamageFlashCoroutine(), and OnActivate().
_transparencyEffectMinimumAlpha
float Battle.View.Player.BattlePlayerViewController._transparencyEffectMinimumAlpha private
[SerializeField] The transparency effect's minimum alpha value..
BattlePlayerViewController-SerializeFields
_transparencyEffectRange
float Battle.View.Player.BattlePlayerViewController._transparencyEffectRange private
[SerializeField] The transparency effect's range.
BattlePlayerViewController-SerializeFields
_transparencyEffectTransitionRate
float Battle.View.Player.BattlePlayerViewController._transparencyEffectTransitionRate private
[SerializeField] The transparency effect's transition rate.
BattlePlayerViewController-SerializeFields
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/View/Battle/Scripts/Player/BattlePlayerViewController.cs