Battle: Battle.QSimulation.Player.BattlePlayerMovementController Class Reference
Battle.QSimulation.Player.BattlePlayerMovementController Class Reference
Handles player movement and rotation.
Static Public Member Functions
static void Init ()
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
static void UpdateMovement (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *transform, Input *input)
Handles player's movement and rotation.
static void Move (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *transform, FPVector2 position)
Moves the player to the specified position while updating the hitbox.
static void Rotate (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *transform, FP radians)
Rotates the player to the specified angle while updating the hitbox.
static void MoveAndRotate (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *transform, FPVector2 position, FP radians)
Moves and rotates the player to the specified position and angle while updating the hitbox.
static void Teleport (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *transform, FPVector2 position, FP rotation)
Instantly moves and rotates the player to the specified position and rotation, and teleports the hitbox.
Static Private Member Functions
static void MoveHitbox (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *transform)
Private method for moving and rotating all of the player's hitboxes to the player's current position and rotation.
static void TeleportHitbox (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *transform)
Private method for instantly teleporting all of player's hitboxes to the specified position and rotation.
static bool ClampPosition (BattlePlayerDataQComponent *playerData, BattleGridPosition gridPosition, out FPVector2 clampedPosition)
Clamps the grid position of the player to the playfield of their team.
static bool ClampPosition (BattlePlayerDataQComponent *playerData, FPVector2 position, out FPVector2 clampedPosition)
Clamps the world position of the player to the playfield of their team.
Static Private Attributes
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
Detailed Description
Handles player movement and rotation.
{Player Overview}
{Player Simulation Code Overview}
Contains the primary UpdateMovement method which handles player movement, and is called by BattlePlayerQSystem.
Also contains individual helper methods for moving and rotating players, which can be used by other scripts.
Member Function Documentation
ClampPosition() [1/2]
bool Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition (BattlePlayerDataQComponent * playerData, BattleGridPosition gridPosition, out FPVector2 clampedPosition) inline static private
Clamps the grid position of the player to the playfield of their team.
Parameters
playerData Pointer to the player's data component.
gridPosition The grid position of the player.
clampedPosition The resulting clamped position of the player.
Returns
True if the position changed from clamping, false if it remained the same.
References Quantum.BattleGridPosition.Col, Battle.QSimulation.Game.BattleGridManager.Columns, Quantum.BattlePlayerDataQComponent.GridExtendBottom, Quantum.BattlePlayerDataQComponent.GridExtendTop, Battle.QSimulation.Game.BattleGridManager.GridPositionToWorldPosition(), Quantum.BattleGridPosition.Row, Battle.QSimulation.Game.BattleGridManager.TeamAlphaFieldEnd, Battle.QSimulation.Game.BattleGridManager.TeamAlphaFieldStart, Battle.QSimulation.Game.BattleGridManager.TeamBetaFieldEnd, Battle.QSimulation.Game.BattleGridManager.TeamBetaFieldStart, and Quantum.BattlePlayerDataQComponent.TeamNumber.
Referenced by ClampPosition(), and UpdateMovement().
ClampPosition() [2/2]
bool Battle.QSimulation.Player.BattlePlayerMovementController.ClampPosition (BattlePlayerDataQComponent * playerData, FPVector2 position, out FPVector2 clampedPosition) inline static private
Clamps the world position of the player to the playfield of their team.
Parameters
playerData Pointer to the player's data component.
position The world position of the player.
clampedPosition The resulting clamped position of the player.
Returns
True if the position changed from clamping, false if it remained the same.
References ClampPosition(), and Battle.QSimulation.Game.BattleGridManager.WorldPositionToGridPosition().
Init()
void Battle.QSimulation.Player.BattlePlayerMovementController.Init () inline static
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
References Battle.QSimulation.BattleDebugLogger.Create(), and s_debugLogger.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
Move()
void Battle.QSimulation.Player.BattlePlayerMovementController.Move (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * transform, FPVector2 position) inline static
Moves the player to the specified position while updating the hitbox.
Parameters
f Current simulation frame.
playerData Pointer to the player's data component.
transform Pointer to the player's transform component.
position World position to move to.
References MoveHitbox().
MoveAndRotate()
void Battle.QSimulation.Player.BattlePlayerMovementController.MoveAndRotate (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * transform, FPVector2 position, FP radians) inline static
Moves and rotates the player to the specified position and angle while updating the hitbox.
Parameters
f Current simulation frame.
playerData Pointer to the player's data component.
transform Pointer to the player's transform component.
position World position to move to.
radians Target rotation angle in radians.
References MoveHitbox().
Referenced by UpdateMovement().
MoveHitbox()
void Battle.QSimulation.Player.BattlePlayerMovementController.MoveHitbox (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * transform) inline static private
Private method for moving and rotating all of the player's hitboxes to the player's current position and rotation.
Parameters
f Current simulation frame.
playerData Pointer to the player's data component.
transform Pointer to the player's transform component.
References Quantum.BattlePlayerDataQComponent.HitboxCharacterEntity, Quantum.BattlePlayerDataQComponent.HitboxShieldEntity, Quantum.BattlePlayerHitboxQComponent.Normal, and Quantum.BattlePlayerHitboxQComponent.NormalBase.
Referenced by Move(), MoveAndRotate(), and Rotate().
Rotate()
void Battle.QSimulation.Player.BattlePlayerMovementController.Rotate (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * transform, FP radians) inline static
Rotates the player to the specified angle while updating the hitbox.
Parameters
f Current simulation frame.
playerData Pointer to the player's data component.
transform Pointer to the player's transform component.
radians Target rotation angle in radians.
References MoveHitbox().
Teleport()
void Battle.QSimulation.Player.BattlePlayerMovementController.Teleport (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * transform, FPVector2 position, FP rotation) inline static
Instantly moves and rotates the player to the specified position and rotation, and teleports the hitbox.
Parameters
f Current simulation frame.
playerData Pointer to the player's data component.
transform Pointer to the player's transform component.
position New world position.
rotation New rotation in radians.
References TeleportHitbox().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer(), and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
TeleportHitbox()
void Battle.QSimulation.Player.BattlePlayerMovementController.TeleportHitbox (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * transform) inline static private
Private method for instantly teleporting all of player's hitboxes to the specified position and rotation.
Parameters
f Current simulation frame.
playerData Pointer to the player's data component.
transform Pointer to the player's transform component.
References Quantum.BattlePlayerDataQComponent.HitboxCharacterEntity, Quantum.BattlePlayerDataQComponent.HitboxShieldEntity, Quantum.BattlePlayerHitboxQComponent.Normal, and Quantum.BattlePlayerHitboxQComponent.NormalBase.
Referenced by Teleport().
UpdateMovement()
void Battle.QSimulation.Player.BattlePlayerMovementController.UpdateMovement (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * transform, Input * input) inline static
Handles player's movement and rotation.
Checks Quantum Input for player's actions.
When movement action is taken: Checks and updates player's TargetPosition based on input.
When rotation action is taken: updates player's RotationOffset based on input.
When rotation action is not taken: updates player's RotationOffset back to zero.
Always: updates player's position and rotation based on the current TargetPosition and RotationOffset.
Parameters
f Current Quantum Frame.
playerData Pointer to player's BattlePlayerDataQComponent.
transform Pointer to player's transform component.
input Pointer to player's Quantum Input.
References ClampPosition(), Quantum.BattlePlayerDataQComponent.DisableRotation, Battle.QSimulation.Game.BattleQConfig.GetPlayerSpec(), Quantum.BattlePlayerDataQComponent.HasTargetPosition, MoveAndRotate(), Quantum.Input.MovementDirection, Quantum.Input.MovementDirectionIsNormalized, Quantum.Input.MovementInput, Quantum.Input.MovementPositionMove, Quantum.Input.MovementPositionTarget, Quantum.BattlePlayerDataQComponent.RotationBase, Quantum.Input.RotationInput, Quantum.BattlePlayerDataQComponent.RotationOffset, Battle.QSimulation.Player.BattlePlayerQSpec.RotationSpeed, Quantum.Input.RotationValue, s_debugLogger, Quantum.BattlePlayerStats.Speed, Quantum.BattlePlayerDataQComponent.Stats, and Quantum.BattlePlayerDataQComponent.TargetPosition.
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.HandleInPlay().
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.QSimulation.Player.BattlePlayerMovementController.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by Init(), and UpdateMovement().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerMovementController.cs