Battle: Battle.QSimulation.Player.BattlePlayerClassBase< T > Class Template Reference
Battle.QSimulation.Player.BattlePlayerClassBase< T > Class Template Reference abstract
An extended base abstact class for player classes.
Contains a method for retrieving the class data component attached to the player character entity.
Class scripts should extend this class if they make use of a class data component.
Protected Member Functions
T * GetClassData (Frame f, EntityRef playerEntity)
Returns a pointer reference to the class data of the specified player entity.
Additional Inherited Members
Public Member Functions inherited from Battle.QSimulation.Player.BattlePlayerClassBase
virtual unsafe void OnCreate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Virtual OnCreate method that can be implemented.
Called by the public BattlePlayerClassManager OnCreate method.
virtual unsafe void OnSpawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Virtual OnSpawn method that can be implemented.
Called by the public BattlePlayerClassManager OnSpawn method.
virtual unsafe void OnDespawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Virtual OnDespawn method that can be implemented.
Called by the public BattlePlayerClassManager OnDespawn method.
virtual unsafe void OnProjectileHitPlayerCharacter (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerCharacterCollisionData *playerCollisionData)
Virtual OnProjectileHitPlayerCharacter method that can be implemented.
Called by the public BattlePlayerClassManager OnProjectileHitPlayerHitbox method.
virtual unsafe void OnProjectileHitPlayerShield (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerShieldCollisionData *shieldCollisionData)
Virtual OnProjectileHitPlayerShield method that can be implemented.
Called by the public BattlePlayerClassManager OnProjectileHitPlayerShield method.
virtual unsafe void OnUpdate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Virtual OnUpdate method that can be implemented.
Called by the public BattlePlayerClassManager OnUpdate method.
Properties inherited from Battle.QSimulation.Player.BattlePlayerClassBase
BattlePlayerCharacterClass Class [get]
Getter for the associated BattlePlayerCharacterClass enum of the class.
Detailed Description
An extended base abstact class for player classes.
Contains a method for retrieving the class data component attached to the player character entity.
Class scripts should extend this class if they make use of a class data component.
See {PlayerClass} for more info.
See {Player Character Classes} for more info.
Type Constraints
T : unmanaged
T : IComponent
Member Function Documentation
GetClassData()
T * Battle.QSimulation.Player.BattlePlayerClassBase< T >.GetClassData (Frame f, EntityRef playerEntity) inline protected
Returns a pointer reference to the class data of the specified player entity.
Parameters
f Current simulation frame.
playerEntity Reference to the player entity.
Returns
A pointer reference to the player's class data.
References Battle.QSimulation.BattleDebugLogger.ErrorFormat().
Referenced by Battle.QSimulation.Player.BattlePlayerClassProjector.OnCreate(), Battle.QSimulation.Player.BattlePlayerClassProjector.OnProjectileHitPlayerShield(), and Battle.QSimulation.Player.BattlePlayerClassProjector.OnUpdate().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerClassManager.cs