Battle: Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem Class Reference
Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem Class Reference
Classes
struct Filter
Public Member Functions
override void Update (Frame f, ref Filter filter)
void OnTriggerProjectileHitSoulWall (Frame f, Quantum.Projectile *projectile, EntityRef projectileEntity, Quantum.SoulWall *soulWall, EntityRef soulWallEntity)
void OnTriggerProjectileHitArenaBorder (Frame f, Quantum.Projectile *projectile, EntityRef projectileEntity, Quantum.ArenaBorder *arenaBorder, EntityRef arenaBorderEntity)
void OnTriggerProjectileHitPlayerHitbox (Frame f, Quantum.Projectile *projectile, EntityRef projectileEntity, PlayerHitbox *playerHitbox, EntityRef playerEntity)
void PickRandomEmotionState (Frame f, Quantum.Projectile *projectile)
Static Public Member Functions
static bool IsCollisionFlagSet (Frame f, Quantum.Projectile *projectile, ProjectileCollisionFlags flag)
static void SetCollisionFlag (Frame f, Quantum.Projectile *projectile, ProjectileCollisionFlags flag)
Private Member Functions
void ProjectileBounce (Frame f, Quantum.Projectile *projectile, EntityRef projectileEntity, EntityRef otherEntity, FPVector2 normal, FP collisionMinOffset)
Member Function Documentation
IsCollisionFlagSet()
static bool Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.IsCollisionFlagSet (Frame f, Quantum.Projectile * projectile, ProjectileCollisionFlags flag) static
Referenced by Quantum.QuantumUser.Simulation.SoulWall.SoulWallSystem.OnTriggerProjectileHitSoulWall(), and ProjectileBounce().
OnTriggerProjectileHitArenaBorder()
void Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.OnTriggerProjectileHitArenaBorder (Frame f, Quantum.Projectile * projectile, EntityRef projectileEntity, Quantum.ArenaBorder * arenaBorder, EntityRef arenaBorderEntity) inline
Implements Quantum.ISignalOnTriggerProjectileHitArenaBorder.
References ProjectileBounce().
OnTriggerProjectileHitPlayerHitbox()
void Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.OnTriggerProjectileHitPlayerHitbox (Frame f, Quantum.Projectile * projectile, EntityRef projectileEntity, PlayerHitbox * playerHitbox, EntityRef playerEntity) inline
Implements Quantum.ISignalOnTriggerProjectileHitPlayerHitbox.
References Quantum.PlayerHitbox.CollisionMinOffset, Quantum.PlayerHitbox.Normal, and ProjectileBounce().
OnTriggerProjectileHitSoulWall()
void Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.OnTriggerProjectileHitSoulWall (Frame f, Quantum.Projectile * projectile, EntityRef projectileEntity, Quantum.SoulWall * soulWall, EntityRef soulWallEntity) inline
Implements Quantum.ISignalOnTriggerProjectileHitSoulWall.
References PickRandomEmotionState(), and ProjectileBounce().
PickRandomEmotionState()
void Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.PickRandomEmotionState (Frame f, Quantum.Projectile * projectile) inline
Referenced by OnTriggerProjectileHitSoulWall(), and Update().
ProjectileBounce()
void Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.ProjectileBounce (Frame f, Quantum.Projectile * projectile, EntityRef projectileEntity, EntityRef otherEntity, FPVector2 normal, FP collisionMinOffset) inline private
References IsCollisionFlagSet(), and SetCollisionFlag().
Referenced by OnTriggerProjectileHitArenaBorder(), OnTriggerProjectileHitPlayerHitbox(), and OnTriggerProjectileHitSoulWall().
SetCollisionFlag()
static void Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.SetCollisionFlag (Frame f, Quantum.Projectile * projectile, ProjectileCollisionFlags flag) inline static
Referenced by Quantum.QuantumUser.Simulation.SoulWall.SoulWallSystem.OnTriggerProjectileHitSoulWall(), and ProjectileBounce().
Update()
override void Quantum.QuantumUser.Simulation.Projectile.ProjectileSystem.Update (Frame f, ref Filter filter) inline
References Quantum.Projectile.Direction, PickRandomEmotionState(), and Quantum.ProjectileSpec.ProjectileInitialSpeed.
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Scripts/Projectile/ProjectileSystem.cs