Battle: Battle.View.UI.BattleUiPlayerInfoHandler Class Reference
Battle.View.UI.BattleUiPlayerInfoHandler Class Reference
PlayerInfo UI Handler (Unity MonoBehaviour script游못).
Handles Battle UI player and teammate info visual functionality through BattleUiPlayerInfoComponent.
Public Types
enum PlayerType { LocalPlayer , LocalTeammate }
Helper enum to differentiate between local player and local player's teammate when calling SetInfo method.
Public Member Functions
void SetShow (bool show)
Sets the UI element visibility.
void SetShowPlayer (bool show)
Sets the Player UI element visibility.
void SetShowTeammate (bool show)
Sets the Teammate UI element visibility.
void SetInfo (PlayerType playerType, string playerName, int[] characterIds, int[] characterClasses, float[] characterDefenceNumbers, BattleUiMovableElementData data)
Sets the player's info to BattleUiPlayerInfo prefab through BattleUiPlayerInfoComponent.
void SetSelected (BattlePlayerSlot slot, int characterNumber)
Checks if the character selection was for the local player.
Calls SetSelected on all character buttons to set them to false, then sets the selected character's to true.
void UpdateHealthVisual (BattlePlayerSlot slot, int characterNumber, float healthPercentage)
Updates character health visual through BattleUiPlayerInfoComponent.
void UpdateDefenceVisual (BattlePlayerSlot slot, int characterNumber, float defenceValue)
Calls SetDefenceNumber on the character button of the correct players correct character.
BattleUiPlayerInfoComponent GetPlayerInfoComponent (BattlePlayerSlot slot)
Retrieves the BattleUiPlayerInfoComponent for either the local player or their teammate.
Properties
bool IsVisible [get]
Is the UI element visible or not.
bool IsVisiblePlayer [get]
Is the Player UI element visible or not.
bool IsVisibleTeammate [get]
Is the Teammate UI element visible or not.
BattleUiMultiOrientationElement LocalPlayerMultiOrientationElement [get]
Public getter for _localPlayerMultiOrientationElement.
BattleUiMultiOrientationElement LocalTeammateMultiOrientationElement [get]
Public getter for _localTeammateMultiOrientationElement.
Private Attributes
bool _isVisible = false
Is the UI element visible or not.
bool _isVisiblePlayer = false
Is the Player UI element visible or not.
bool _isVisibleTeammate = false
Is the Teammate UI element visible or not.
SerializeField variables
SerializeFields游못 are serialized variables exposed to the Unity editor.
BattleUiController _uiController
[SerializeField] Reference to BattleUiController.
BattleUiMultiOrientationElement _localPlayerMultiOrientationElement
[SerializeField] Reference to the BattleUiMultiOrientationElement script which is attached to the local player's BattleUiPlayerInfo prefab.
BattleUiMultiOrientationElement _localTeammateMultiOrientationElement
[SerializeField] Reference to the BattleUiMultiOrientationElement script which is attached to the local player's teammate's BattleUiPlayerInfo prefab.
Detailed Description
PlayerInfo UI Handler (Unity MonoBehaviour script游못).
Handles Battle UI player and teammate info visual functionality through BattleUiPlayerInfoComponent.
Member Enumeration Documentation
PlayerType
enum Battle.View.UI.BattleUiPlayerInfoHandler.PlayerType
Helper enum to differentiate between local player and local player's teammate when calling SetInfo method.
Enumerator
LocalPlayer
LocalTeammate
Member Function Documentation
GetPlayerInfoComponent()
BattleUiPlayerInfoComponent Battle.View.UI.BattleUiPlayerInfoHandler.GetPlayerInfoComponent (BattlePlayerSlot slot) inline
Retrieves the BattleUiPlayerInfoComponent for either the local player or their teammate.
Parameters
slot The slot of the player in question.
Returns
The BattleUiPlayerInfoComponent for the specified player.
References _localPlayerMultiOrientationElement, _localTeammateMultiOrientationElement, and Battle.View.Game.BattleGameViewController.LocalPlayerSlot.
Referenced by SetSelected(), UpdateDefenceVisual(), and UpdateHealthVisual().
SetInfo()
void Battle.View.UI.BattleUiPlayerInfoHandler.SetInfo (PlayerType playerType, string playerName, int[] characterIds, int[] characterClasses, float[] characterDefenceNumbers, BattleUiMovableElementData data) inline
Sets the player's info to BattleUiPlayerInfo prefab through BattleUiPlayerInfoComponent.
Parameters
playerType The PlayerType which info to set.
playerName Name of the player.
characterIds An array of the character IDs of the players selected characters.
characterClasses An array of the character classes of the players selected characters.
characterDefenceNumbers Array of defence values for each character.
data The BattleUiMovableElementData for this UI element.
References _localPlayerMultiOrientationElement, _localTeammateMultiOrientationElement, _uiController, Battle.View.UI.BattleUiCharacterButtonComponent.ButtonComponent, Battle.View.UI.BattleUiPlayerInfoComponent.CharacterButtons, Battle.View.UI.BattleUiCharacterButtonComponent.EventSender, Battle.View.UI.BattleUiPlayerInfoComponent.FrameComponents, Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.GetActiveGameObject(), OnPointerDownButton.onClick, Battle.View.UI.BattleUiCharacterFrameComponent.SetCharacterFrame(), Battle.View.UI.BattleUiCharacterButtonComponent.SetCharacterIcon(), Altzone.Scripts.BattleUiShared.BattleUiMultiOrientationElement.SetData(), and Battle.View.UI.BattleUiCharacterButtonComponent.SetDefenceNumber().
SetSelected()
void Battle.View.UI.BattleUiPlayerInfoHandler.SetSelected (BattlePlayerSlot slot, int characterNumber) inline
Checks if the character selection was for the local player.
Calls SetSelected on all character buttons to set them to false, then sets the selected character's to true.
Parameters
slot The slot of the player in question.
characterNumber The character number of the selected character.
References GetPlayerInfoComponent(), Battle.View.Game.BattleGameViewController.LocalPlayerSlot, and Battle.View.UI.BattleUiCharacterButtonComponent.SetSelected().
SetShow()
void Battle.View.UI.BattleUiPlayerInfoHandler.SetShow (bool show) inline
Sets the UI element visibility.
Updates both elements using the master flag and their individual states. Acts as a master switch without overriding individual visibility settings.
Parameters
show True/False : visible / not visible.
References _isVisible, _isVisiblePlayer, _isVisibleTeammate, _localPlayerMultiOrientationElement, and _localTeammateMultiOrientationElement.
SetShowPlayer()
void Battle.View.UI.BattleUiPlayerInfoHandler.SetShowPlayer (bool show) inline
Sets the Player UI element visibility.
Updates only the Player element. Visible only if both the master and Player flags are true.
Parameters
show True/False : visible / not visible.
References _isVisible, _isVisiblePlayer, and _localPlayerMultiOrientationElement.
SetShowTeammate()
void Battle.View.UI.BattleUiPlayerInfoHandler.SetShowTeammate (bool show) inline
Sets the Teammate UI element visibility.
Updates only the Teammate element. Visible only if both the master and Teammate flags are true.
Parameters
show True/False : visible / not visible.
References _isVisible, _isVisibleTeammate, and _localTeammateMultiOrientationElement.
UpdateDefenceVisual()
void Battle.View.UI.BattleUiPlayerInfoHandler.UpdateDefenceVisual (BattlePlayerSlot slot, int characterNumber, float defenceValue) inline
Calls SetDefenceNumber on the character button of the correct players correct character.
Parameters
slot The slot of the player in question.
characterNumber The character number of the character in question.
defenceValue The defence value of the character in question.
References Battle.View.UI.BattleUiPlayerInfoComponent.CharacterButtons, GetPlayerInfoComponent(), and Battle.View.UI.BattleUiCharacterButtonComponent.SetDefenceNumber().
UpdateHealthVisual()
void Battle.View.UI.BattleUiPlayerInfoHandler.UpdateHealthVisual (BattlePlayerSlot slot, int characterNumber, float healthPercentage) inline
Updates character health visual through BattleUiPlayerInfoComponent.
Parameters
slot The player's BattlePlayerSlot who's character health visual to update.
characterNumber The character number which health visual to update.
healthPercentage The updated health percentage for the character.
References Battle.View.UI.BattleUiPlayerInfoComponent.CharacterButtons, GetPlayerInfoComponent(), and Battle.View.UI.BattleUiCharacterButtonComponent.SetDamageFill().
Member Data Documentation
_isVisible
bool Battle.View.UI.BattleUiPlayerInfoHandler._isVisible = false private
Is the UI element visible or not.
Referenced by SetShow(), SetShowPlayer(), and SetShowTeammate().
_isVisiblePlayer
bool Battle.View.UI.BattleUiPlayerInfoHandler._isVisiblePlayer = false private
Is the Player UI element visible or not.
Referenced by SetShow(), and SetShowPlayer().
_isVisibleTeammate
bool Battle.View.UI.BattleUiPlayerInfoHandler._isVisibleTeammate = false private
Is the Teammate UI element visible or not.
Referenced by SetShow(), and SetShowTeammate().
_localPlayerMultiOrientationElement
BattleUiMultiOrientationElement Battle.View.UI.BattleUiPlayerInfoHandler._localPlayerMultiOrientationElement private
[SerializeField] Reference to the BattleUiMultiOrientationElement script which is attached to the local player's BattleUiPlayerInfo prefab.
BattleUiPlayerInfoHandler-SerializeFields
Referenced by GetPlayerInfoComponent(), SetInfo(), SetShow(), and SetShowPlayer().
_localTeammateMultiOrientationElement
BattleUiMultiOrientationElement Battle.View.UI.BattleUiPlayerInfoHandler._localTeammateMultiOrientationElement private
[SerializeField] Reference to the BattleUiMultiOrientationElement script which is attached to the local player's teammate's BattleUiPlayerInfo prefab.
BattleUiPlayerInfoHandler-SerializeFields
Referenced by GetPlayerInfoComponent(), SetInfo(), SetShow(), and SetShowTeammate().
_uiController
BattleUiController Battle.View.UI.BattleUiPlayerInfoHandler._uiController private
[SerializeField] Reference to BattleUiController.
BattleUiPlayerInfoHandler-SerializeFields
Referenced by SetInfo().
Property Documentation
IsVisible
bool Battle.View.UI.BattleUiPlayerInfoHandler.IsVisible get
Is the UI element visible or not.
IsVisiblePlayer
bool Battle.View.UI.BattleUiPlayerInfoHandler.IsVisiblePlayer get
Is the Player UI element visible or not.
IsVisibleTeammate
bool Battle.View.UI.BattleUiPlayerInfoHandler.IsVisibleTeammate get
Is the Teammate UI element visible or not.
LocalPlayerMultiOrientationElement
BattleUiMultiOrientationElement Battle.View.UI.BattleUiPlayerInfoHandler.LocalPlayerMultiOrientationElement get
Public getter for _localPlayerMultiOrientationElement.
LocalTeammateMultiOrientationElement
BattleUiMultiOrientationElement Battle.View.UI.BattleUiPlayerInfoHandler.LocalTeammateMultiOrientationElement get
Public getter for _localTeammateMultiOrientationElement.
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/View/Battle/Scripts/UI/Handler/BattleUiPlayerInfoHandler.cs