Battle: Battle.QSimulation.Player.BattlePlayerQSystem Class Reference
Battle.QSimulation.Player.BattlePlayerQSystem Class Reference
Player Quantum System游못 [Systems]
Handles the quantum side of player logic.
Public Member Functions
override void Update (Frame f)
Quantum System Update method游못 gets called every frame.
Relays the appropriate input data to each player in the game
Static Public Member Functions
static void Init ()
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
static void SpawnPlayers (Frame f)
Calls BattlePlayerManager.SpawnPlayer for players that are in the game.
static void HandlePlayerAbandoned (Frame f, BattlePlayerManager.PlayerHandle playerHandle)
Handles logic when a player abandons the game.
static void OnProjectileHitPlayerCharacter (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerCharacterCollisionData *playerCollisionData)
Called by BattleCollisionQSystem. Applies damage to the player after checking if it is appropriate to do so.
static void OnProjectileHitPlayerShield (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerShieldCollisionData *shieldCollisionData)
Called by BattleCollisionQSystem. Applies damage to the player's shield after checking if it is appropriate to do so.
Private Member Functions
Input * GetInput (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, Input *stackInputStorage)
Private helper method for retrieving the correct input (bot, abandoned, active player).
Subprocess of the Update method.
bool HandleGiveUpInput (Frame f, Input *input, BattlePlayerManager.PlayerHandle playerHandle)
Private helper method for handling player input for giving up during the game play.
Subprocess of the Update method.
bool HandleCharacterSwapping (Frame f, Input *input, BattlePlayerManager.PlayerHandle playerHandle)
Private helper method for handling character swapping.
Subprocess of the Update method.
bool HandleOutOfPlay (Frame f, BattlePlayerManager.PlayerHandle playerHandle)
Private helper method for handling player logic when out of play or any of its substates.
Subprocess of the Update method.
void HandleInPlay (Frame f, Input *input, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity, Transform2D *playerTransform)
Private helper method for handling player logic and updates when state is in play.
Subprocess of the Update method.
void AbilityActivate (Frame f, BattlePlayerDataQComponent *playerData, Transform2D *playerTransform)
Static Private Member Functions
static bool HandleGiveUpLogic (Frame f, BattlePlayerManager.PlayerHandle playerHandle)
Private helper method for handling when a player gives up or abandons the match.
Static Private Attributes
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
Detailed Description
Player Quantum System游못 [Systems]
Handles the quantum side of player logic.
{Player Overview}
{Player Simulation Code Overview}
This system contains methods called by BattleCollisionQSystem that deal damage to players and shields, as well as sending input data forward for movement and character switching.
Member Function Documentation
AbilityActivate()
void Battle.QSimulation.Player.BattlePlayerQSystem.AbilityActivate (Frame f, BattlePlayerDataQComponent * playerData, Transform2D * playerTransform) inline private
References Quantum.BattlePlayerDataQComponent.AbilityCooldownSec.
Referenced by GetInput(), and HandleInPlay().
GetInput()
Input * Battle.QSimulation.Player.BattlePlayerQSystem.GetInput (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, Input * stackInputStorage) inline private
Private helper method for retrieving the correct input (bot, abandoned, active player).
Subprocess of the Update method.
Parameters
f Current simulation frame.
playerHandle Handle of the player.
playerData Player data component.
stackInputStorage Temporary input storage for bots and abandoned players.
Returns
Pointer to the player's input.
References AbilityActivate(), Quantum.Input.DebugNumber, Battle.QSimulation.BattleInputDebugUtils.GenerateDebugInfo(), Battle.QSimulation.Player.BattlePlayerBotController.GetBotInput(), Quantum.Frame.GetPlayerInput(), Quantum.Input.IsValid, and s_debugLogger.
Referenced by Update().
HandleCharacterSwapping()
bool Battle.QSimulation.Player.BattlePlayerQSystem.HandleCharacterSwapping (Frame f, Input * input, BattlePlayerManager.PlayerHandle playerHandle) inline private
Private helper method for handling character swapping.
Subprocess of the Update method.
Parameters
f Current simulation frame.
input Pointer to the player's input data.
playerHandle Handle of the player.
Returns
True if character swapped.
References Quantum.Input.PlayerCharacterNumber, s_debugLogger, and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
Referenced by Update().
HandleGiveUpInput()
bool Battle.QSimulation.Player.BattlePlayerQSystem.HandleGiveUpInput (Frame f, Input * input, BattlePlayerManager.PlayerHandle playerHandle) inline private
Private helper method for handling player input for giving up during the game play.
Subprocess of the Update method.
Updates give up state and calls HandleGiveUpLogic method which handles the rest of the logic.
Parameters
f Current simulation frame.
input Pointer to the player's input data.
playerHandle Handle of the player.
Returns
True if the give up input was processed.
References Quantum.Input.GiveUpInput, HandleGiveUpLogic(), and s_debugLogger.
Referenced by Update().
HandleGiveUpLogic()
bool Battle.QSimulation.Player.BattlePlayerQSystem.HandleGiveUpLogic (Frame f, BattlePlayerManager.PlayerHandle playerHandle) inline static private
Private helper method for handling when a player gives up or abandons the match.
Used by HandleGiveUpInput and HandlePlayerAbandoned.
Parameters
f Current simulation frame.
playerHandle Handle of the player.
References Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeamNumber(), Quantum.NoTeam, Battle.QSimulation.Game.BattleGameControlQSystem.OnGameOver(), Quantum.TeamAlpha, and Quantum.TeamBeta.
Referenced by HandleGiveUpInput(), and HandlePlayerAbandoned().
HandleInPlay()
void Battle.QSimulation.Player.BattlePlayerQSystem.HandleInPlay (Frame f, Input * input, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, EntityRef playerEntity, Transform2D * playerTransform) inline private
Private helper method for handling player logic and updates when state is in play.
Subprocess of the Update method.
Parameters
f Current simulation frame.
input Pointer to the player's input data.
playerHandle Handle of the player.
playerData Pointer to the player's data component
playerEntity Reference to the player's entity
playerTransform Pointer to the player's transform component.
References AbilityActivate(), Quantum.Input.AbilityActivate, Quantum.BattlePlayerDataQComponent.AbilityActivateBufferSec, Quantum.BattlePlayerDataQComponent.AbilityCooldownSec, Quantum.BattlePlayerDataQComponent.CurrentDefence, Quantum.BattlePlayerDataQComponent.HitboxShieldEntity, Battle.QSimulation.Player.BattlePlayerClassManager.OnUpdate(), s_debugLogger, and Battle.QSimulation.Player.BattlePlayerMovementController.UpdateMovement().
Referenced by Update().
HandleOutOfPlay()
bool Battle.QSimulation.Player.BattlePlayerQSystem.HandleOutOfPlay (Frame f, BattlePlayerManager.PlayerHandle playerHandle) inline private
Private helper method for handling player logic when out of play or any of its substates.
Subprocess of the Update method.
Parameters
f Current simulation frame.
playerHandle Handle of the player.
Returns
True if the player is out of play or out of play respawn.
References Quantum.Constants.BATTLE_PLAYER_CHARACTER_COUNT, s_debugLogger, and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
Referenced by Update().
HandlePlayerAbandoned()
void Battle.QSimulation.Player.BattlePlayerQSystem.HandlePlayerAbandoned (Frame f, BattlePlayerManager.PlayerHandle playerHandle) inline static
Handles logic when a player abandons the game.
Updates give up state and calls HandleGiveUpLogic method which handles the rest of the logic.
Parameters
f Current simulation frame.
playerHandle Handle of the player who abandoned.
References HandleGiveUpLogic().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.MarkAbandoned().
Init()
void Battle.QSimulation.Player.BattlePlayerQSystem.Init () inline static
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
References Battle.QSimulation.BattleDebugLogger.Create(), and s_debugLogger.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
OnProjectileHitPlayerCharacter()
void Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerCharacter (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, BattleCollisionQSystem.PlayerCharacterCollisionData * playerCollisionData) inline static
Called by BattleCollisionQSystem. Applies damage to the player after checking if it is appropriate to do so.
Parameters
f Current simulation frame
projectileCollisionData Collision data related to the projectile.
playerCollisionData Collision data related to the player character.
References Quantum.BattlePlayerDataQComponent.CurrentHp, Quantum.BattlePlayerDataQComponent.DamageCooldown, Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandle(), Battle.QSimulation.Game.BattleQConfig.GetPlayerSpec(), Quantum.BattlePlayerStats.Hp, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SelectedCharacterNumber, Battle.QSimulation.Projectile.BattleProjectileQSystem.SetCollisionFlag(), Quantum.BattlePlayerDataQComponent.Slot, Quantum.BattlePlayerDataQComponent.Stats, and Quantum.BattlePlayerDataQComponent.TeamNumber.
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
OnProjectileHitPlayerShield()
void Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerShield (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, BattleCollisionQSystem.PlayerShieldCollisionData * shieldCollisionData) inline static
Called by BattleCollisionQSystem. Applies damage to the player's shield after checking if it is appropriate to do so.
Parameters
f Current simulation frame
projectileCollisionData Collision data related to the projectile.
shieldCollisionData Collision data related to the player shield.
References Quantum.BattlePlayerStats.Attack, Quantum.BattlePlayerDataQComponent.CurrentDefence, Quantum.BattlePlayerDataQComponent.DamageCooldown, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandle(), Battle.QSimulation.Game.BattleQConfig.GetPlayerSpec(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SelectedCharacterNumber, Battle.QSimulation.Projectile.BattleProjectileQSystem.SetAttack(), Battle.QSimulation.Projectile.BattleProjectileQSystem.SetCollisionFlag(), Quantum.BattlePlayerDataQComponent.Slot, Quantum.BattlePlayerDataQComponent.Stats, and Quantum.BattlePlayerDataQComponent.TeamNumber.
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
SpawnPlayers()
void Battle.QSimulation.Player.BattlePlayerQSystem.SpawnPlayers (Frame f) inline static
Calls BattlePlayerManager.SpawnPlayer for players that are in the game.
Parameters
f Current simulation frame.
References Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandleArray(), and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.CreateMap().
Update()
override void Battle.QSimulation.Player.BattlePlayerQSystem.Update (Frame f) inline
Quantum System Update method游못 gets called every frame.
Relays the appropriate input data to each player in the game
Update method has been split into subprocesses.
see GetInput
see HandleGiveUpInput
see HandleCharacterSwapping
see HandleOutOfPlay
see HandleInPlay
Parameters
f Current simulation frame
References GetInput(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandleArray(), HandleCharacterSwapping(), HandleGiveUpInput(), HandleInPlay(), and HandleOutOfPlay().
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.QSimulation.Player.BattlePlayerQSystem.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by GetInput(), HandleCharacterSwapping(), HandleGiveUpInput(), HandleInPlay(), HandleOutOfPlay(), and Init().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerQSystem.cs