Battle: Quantum.PlayerManager Class Reference
Quantum.PlayerManager Class Reference
Classes
struct PlayerHandle
Static Public Member Functions
static void Init (Frame f)
static BattlePlayerSlot InitPlayer (Frame f, PlayerRef playerRef)
static void SpawnPlayer (Frame f, BattlePlayerSlot slot, int characterNumber)
static void DespawnPlayer (Frame f, BattlePlayerSlot slot)
static BattleTeamNumber GetPlayerTeamNumber (BattlePlayerSlot slot)
static PlayerPlayState GetPlayerPlayState (Frame f, BattlePlayerSlot slot)
static EntityRef GetPlayerEntity (Frame f, BattlePlayerSlot slot)
static EntityRef GetTeammateEntity (Frame f, BattlePlayerSlot slot)
static bool IsValidCharacterNumber (int characterNumber)
Static Private Member Functions
static PlayerManagerData * GetPlayerManagerData (Frame f)
static void SpawnPlayer (Frame f, PlayerHandle playerHandle, int characterNumber)
static void DespawnPlayer (Frame f, PlayerHandle playerHandle)
Static Private Attributes
static readonly FPVector2[] s_spawnPoints = new FPVector2[Constants.PLAYER_SLOT_COUNT]
Member Function Documentation
DespawnPlayer() [1/2]
static void Quantum.PlayerManager.DespawnPlayer (Frame f, BattlePlayerSlot slot) inline static
References DespawnPlayer(), GetPlayerManagerData(), and Quantum.PlayerManager.PlayerHandle.PlayState.
Referenced by DespawnPlayer(), and SpawnPlayer().
DespawnPlayer() [2/2]
static void Quantum.PlayerManager.DespawnPlayer (Frame f, PlayerHandle playerHandle) inline static private
References Quantum.PlayerManager.PlayerHandle.GetOutOfPlayPosition(), Quantum.PlayerData.PlayerRef, Quantum.PlayerData.RotationBase, Quantum.PlayerManager.PlayerHandle.SelectedCharacter, Quantum.PlayerManager.PlayerHandle.SelectedCharacterNumber, Quantum.PlayerData.TargetPosition, Quantum.PlayerData.TeamNumber, Quantum.PlayerMovementSystem.Teleport(), and Quantum.PlayerManager.PlayerHandle.UnsetSelectedCharacter().
GetPlayerEntity()
static EntityRef Quantum.PlayerManager.GetPlayerEntity (Frame f, BattlePlayerSlot slot) inline static
References Quantum.PlayerManager.PlayerHandle.GetPlayerIndex(), GetPlayerManagerData(), and Quantum.PlayerManager.PlayerHandle.GetSelectedCharacter().
GetPlayerManagerData()
static PlayerManagerData * Quantum.PlayerManager.GetPlayerManagerData (Frame f) inline static private
Referenced by DespawnPlayer(), GetPlayerEntity(), GetPlayerPlayState(), GetTeammateEntity(), Init(), InitPlayer(), and SpawnPlayer().
GetPlayerPlayState()
static PlayerPlayState Quantum.PlayerManager.GetPlayerPlayState (Frame f, BattlePlayerSlot slot) inline static
References Quantum.PlayerManager.PlayerHandle.GetPlayerIndex(), GetPlayerManagerData(), and Quantum.PlayerManager.PlayerHandle.GetPlayState().
GetPlayerTeamNumber()
static BattleTeamNumber Quantum.PlayerManager.GetPlayerTeamNumber (BattlePlayerSlot slot) static
GetTeammateEntity()
static EntityRef Quantum.PlayerManager.GetTeammateEntity (Frame f, BattlePlayerSlot slot) inline static
References GetPlayerManagerData(), Quantum.PlayerManager.PlayerHandle.GetSelectedCharacter(), and Quantum.PlayerManager.PlayerHandle.GetTeammatePlayerIndex().
Init()
static void Quantum.PlayerManager.Init (Frame f) inline static
References GetPlayerManagerData(), Quantum.GridManager.GridPositionToWorldPosition(), Quantum.BattleArenaSpec.PlayerSpawnPositions, s_spawnPoints, and Quantum.PlayerManager.PlayerHandle.SetAllPlayStates().
Referenced by Quantum.GameControlSystem.OnInit().
InitPlayer()
static BattlePlayerSlot Quantum.PlayerManager.InitPlayer (Frame f, PlayerRef playerRef) inline static
References Quantum.BattleCharacterBase.Attack, Quantum.RuntimePlayer.Characters, Quantum.BattleCharacterBase.CharacterSize, Quantum.BattleCharacterBase.Class, Quantum.PlayerHitboxTemplate.CollisionType, Quantum.BattleCharacterBase.Defence, Quantum.PlayerManager.PlayerHandle.GetOutOfPlayPosition(), GetPlayerManagerData(), Quantum.PlayerManager.PlayerHandle.GetTeamNumber(), Quantum.GridManager.GridScaleFactor, Quantum.PlayerDataTemplate.HitboxListCharacter, Quantum.PlayerDataTemplate.HitboxListShield, Quantum.BattleCharacterBase.Hp, Quantum.BattleCharacterBase.Id, Quantum.PlayerHitboxTemplate.NormalAngle, Quantum.Constants.PLAYER_CHARACTER_COUNT, Quantum.RuntimePlayer.PlayerSlot, Quantum.PlayerHitboxTemplate.Position, Quantum.PlayerManager.PlayerHandle.SetCharacters(), Quantum.BattleCharacterBase.Speed, Quantum.TeamAlpha, and Quantum.PlayerMovementSystem.Teleport().
Referenced by Quantum.PlayerJoinSystem.OnPlayerAdded().
IsValidCharacterNumber()
static bool Quantum.PlayerManager.IsValidCharacterNumber (int characterNumber) static
SpawnPlayer() [1/2]
static void Quantum.PlayerManager.SpawnPlayer (Frame f, BattlePlayerSlot slot, int characterNumber) inline static
References GetPlayerManagerData(), Quantum.PlayerManager.PlayerHandle.IsValidCharacterNumber(), Quantum.PlayerManager.PlayerHandle.PlayState, and SpawnPlayer().
Referenced by Quantum.PlayerJoinSystem.OnPlayerAdded(), and SpawnPlayer().
SpawnPlayer() [2/2]
static void Quantum.PlayerManager.SpawnPlayer (Frame f, PlayerHandle playerHandle, int characterNumber) inline static private
References DespawnPlayer(), Quantum.PlayerManager.PlayerHandle.GetCharacter(), Quantum.PlayerData.PlayerRef, Quantum.PlayerManager.PlayerHandle.PlayerRef, Quantum.PlayerManager.PlayerHandle.PlayState, Quantum.PlayerData.RotationBase, Quantum.PlayerManager.PlayerHandle.SelectedCharacter, Quantum.PlayerManager.PlayerHandle.SetSelectedCharacter(), Quantum.PlayerManager.PlayerHandle.SpawnPosition, Quantum.PlayerData.TargetPosition, and Quantum.PlayerMovementSystem.Teleport().
Member Data Documentation
s_spawnPoints
readonly FPVector2 [] Quantum.PlayerManager.s_spawnPoints = new FPVector2[Constants.PLAYER_SLOT_COUNT] static private
Referenced by Init().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Scripts/Player/PlayerManager.cs