Battle: Battle.QSimulation.Player.BattlePlayerClassProjector Class Reference
Battle.QSimulation.Player.BattlePlayerClassProjector Class Reference
Player character class logic for the 400/Projector class.
Public Member Functions
override unsafe void OnCreate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Called when the player is created.
override unsafe void OnProjectileHitPlayerShield (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerShieldCollisionData *shieldCollisionData)
Called when a projectile hits a player shield.
override unsafe void OnUpdate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Called every frame to update the player.
Public Member Functions inherited from Battle.QSimulation.Player.BattlePlayerClassBase
virtual unsafe void OnSpawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Virtual OnSpawn method that can be implemented.
Called by the public BattlePlayerClassManager OnSpawn method.
virtual unsafe void OnDespawn (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent *playerData, EntityRef playerEntity)
Virtual OnDespawn method that can be implemented.
Called by the public BattlePlayerClassManager OnDespawn method.
virtual unsafe void OnProjectileHitPlayerCharacter (Frame f, BattleCollisionQSystem.ProjectileCollisionData *projectileCollisionData, BattleCollisionQSystem.PlayerCharacterCollisionData *playerCollisionData)
Virtual OnProjectileHitPlayerCharacter method that can be implemented.
Called by the public BattlePlayerClassManager OnProjectileHitPlayerHitbox method.
Properties
override BattlePlayerCharacterClass Class [get]
Gets the character class associated with this Class.
Always returns BattlePlayerCharacterClass.Projector.
Properties inherited from Battle.QSimulation.Player.BattlePlayerClassBase
BattlePlayerCharacterClass Class [get]
Getter for the associated BattlePlayerCharacterClass enum of the class.
Additional Inherited Members
Protected Member Functions inherited from Battle.QSimulation.Player.BattlePlayerClassBase< T >
T * GetClassData (Frame f, EntityRef playerEntity)
Returns a pointer reference to the class data of the specified player entity.
Detailed Description
Player character class logic for the 400/Projector class.
See {PlayerClass} for more info.
See {Player Character Classes} for more info.
See {Player Character Class 400 - Projector} for more info.
Member Function Documentation
OnCreate()
override unsafe void Battle.QSimulation.Player.BattlePlayerClassProjector.OnCreate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, EntityRef playerEntity) inline virtual
Called when the player is created.
Parameters
f Current simulation frame.
playerHandle Handle for the player.
playerData Pointer to player data.
playerEntity Entity reference for the player.
Reimplemented from Battle.QSimulation.Player.BattlePlayerClassBase.
References Battle.QSimulation.Player.BattlePlayerClassBase< T >.GetClassData().
OnProjectileHitPlayerShield()
override unsafe void Battle.QSimulation.Player.BattlePlayerClassProjector.OnProjectileHitPlayerShield (Frame f, BattleCollisionQSystem.ProjectileCollisionData * projectileCollisionData, BattleCollisionQSystem.PlayerShieldCollisionData * shieldCollisionData) inline virtual
Called when a projectile hits a player shield.
Parameters
f Current simulation frame.
projectileCollisionData Collision data related to the projectile.
shieldCollisionData Collision data related to the player shield.
Reimplemented from Battle.QSimulation.Player.BattlePlayerClassBase.
References Battle.QSimulation.Player.BattlePlayerClassBase< T >.GetClassData(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle(), Battle.QSimulation.Projectile.BattleProjectileQSystem.HandleIntersection(), Quantum.BattlePlayerClassProjectorDataQComponent.HeldProjectileAngleRadians, Quantum.BattlePlayerClassProjectorDataQComponent.HeldProjectileDistance, Quantum.BattlePlayerClassProjectorDataQComponent.HeldProjectileEntity, Quantum.BattlePlayerClassProjectorDataQComponent.HoldStartFrame, Quantum.BattlePlayerClassProjectorDataQComponent.IsHoldingProjectile, Battle.QSimulation.Projectile.BattleProjectileQSystem.SetHeld(), Quantum.BattlePlayerDataQComponent.Slot, and Battle.QSimulation.Projectile.BattleProjectileQSystem.UpdateVelocity().
OnUpdate()
override unsafe void Battle.QSimulation.Player.BattlePlayerClassProjector.OnUpdate (Frame f, BattlePlayerManager.PlayerHandle playerHandle, BattlePlayerDataQComponent * playerData, EntityRef playerEntity) inline virtual
Called every frame to update the player.
Parameters
f Current simulation frame.
playerHandle Handle for the player.
playerData Pointer to player data.
playerEntity Entity reference for the player.
Reimplemented from Battle.QSimulation.Player.BattlePlayerClassBase.
References Battle.QSimulation.Player.BattlePlayerClassBase< T >.GetClassData(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle(), Battle.QSimulation.Game.BattleGridManager.GridScaleFactor, Quantum.BattlePlayerClassProjectorDataQComponent.HeldProjectileAngleRadians, Quantum.BattlePlayerClassProjectorDataQComponent.HeldProjectileDistance, Quantum.BattlePlayerClassProjectorDataQComponent.HeldProjectileEntity, Quantum.BattlePlayerClassProjectorDataQComponent.HoldStartFrame, Quantum.BattlePlayerClassProjectorDataQComponent.IsHoldingProjectile, Quantum.BattleProjectileQComponent.Position, Quantum.BattlePlayerClassProjectorDataQComponent.RotationDurationFrames, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SelectedCharacterEntity, Battle.QSimulation.Projectile.BattleProjectileQSystem.SetHeld(), Quantum.BattlePlayerDataQComponent.Slot, Quantum.TeamAlpha, Quantum.BattlePlayerDataQComponent.TeamNumber, and Battle.QSimulation.Projectile.BattleProjectileQSystem.UpdateVelocity().
Property Documentation
Class
override BattlePlayerCharacterClass Battle.QSimulation.Player.BattlePlayerClassProjector.Class get
Gets the character class associated with this Class.
Always returns BattlePlayerCharacterClass.Projector.
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/PlayerClasses/BattlePlayerClassProjector.cs