Battle: Battle.View.UI.BattleUiGiveUpButtonHandler Class Reference
Battle.View.UI.BattleUiGiveUpButtonHandler Class Reference
GiveUpButton UI Handler (Unity MonoBehaviour script游못).
Handles give up button functionality.
Public Member Functions
void SetShow (bool show)
Sets the UI element visibility.
void UpdateState (BattlePlayerSlot playerSlot, BattleGiveUpStateUpdate stateUpdate)
Updates the give up info text state.
Properties
bool IsVisible [get]
Is the UI element visible or not.
BattleUiMovableElement MovableUiElement [get]
Public getter for _movableUiElement.
Private Types
enum ButtonInfoState {
Normal , LocalGiveUp , TeammateGiveUp , TeammateAbandoned ,
TeamGiveUp
}
States for the give up info text.
Private Member Functions
void Awake ()
Private Awake游못 method which adds listener to the _giveUpButton's onClick游못 event.
void UpdateInfoText ()
Private helper method for updating give up button info text based on ButtonInfoState.
void OnDestroy ()
Private OnDestroy游못 method which removes all listeners from _giveUpButton's onClick游못 event.
Private Attributes
BattleDebugLogger _debugLogger
This classes BattleDebugLogger instance.
ButtonInfoState _buttonInfoState
Current state of the give up info text.
SerializeField variables
SerializeFields游못 are serialized variables exposed to the Unity editor.
BattleUiController _uiController
[SerializeField] Reference to BattleUiController.
BattleUiMovableElement _movableUiElement
[SerializeField] Reference to the BattleUiMovableElement script which is attached to a BattleUiGiveUpButton prefab.
OnPointerDownButton _giveUpButton
[SerializeField] Reference to the Button component of the give up button.
TextMeshProUGUI _giveUpButtonInfoText
[SerializeField] Reference to the Text component of the give up info text.
Detailed Description
GiveUpButton UI Handler (Unity MonoBehaviour script游못).
Handles give up button functionality.
Member Enumeration Documentation
ButtonInfoState
enum Battle.View.UI.BattleUiGiveUpButtonHandler.ButtonInfoState private
States for the give up info text.
Enumerator
Normal
LocalGiveUp
TeammateGiveUp
TeammateAbandoned
TeamGiveUp
Member Function Documentation
Awake()
void Battle.View.UI.BattleUiGiveUpButtonHandler.Awake () inline private
Private Awake游못 method which adds listener to the _giveUpButton's onClick游못 event.
References _buttonInfoState, _debugLogger, _giveUpButton, _uiController, Battle.QSimulation.BattleDebugLogger.Create(), and UpdateInfoText().
OnDestroy()
void Battle.View.UI.BattleUiGiveUpButtonHandler.OnDestroy () inline private
Private OnDestroy游못 method which removes all listeners from _giveUpButton's onClick游못 event.
References _giveUpButton.
SetShow()
void Battle.View.UI.BattleUiGiveUpButtonHandler.SetShow (bool show) inline
Sets the UI element visibility.
Parameters
show True/False : visible / not visible.
References MovableUiElement.
UpdateInfoText()
void Battle.View.UI.BattleUiGiveUpButtonHandler.UpdateInfoText () inline private
Private helper method for updating give up button info text based on ButtonInfoState.
References _buttonInfoState.
Referenced by Awake(), and UpdateState().
UpdateState()
void Battle.View.UI.BattleUiGiveUpButtonHandler.UpdateState (BattlePlayerSlot playerSlot, BattleGiveUpStateUpdate stateUpdate) inline
Updates the give up info text state.
Parameters
playerSlot The slot of the player
stateUpdate Type of the give up state update.
References _buttonInfoState, _debugLogger, LocalGiveUp, Battle.View.Game.BattleGameViewController.LocalPlayerSlot, TeamGiveUp, TeammateAbandoned, TeammateGiveUp, and UpdateInfoText().
Member Data Documentation
_buttonInfoState
ButtonInfoState Battle.View.UI.BattleUiGiveUpButtonHandler._buttonInfoState private
Current state of the give up info text.
Referenced by Awake(), UpdateInfoText(), and UpdateState().
_debugLogger
BattleDebugLogger Battle.View.UI.BattleUiGiveUpButtonHandler._debugLogger private
This classes BattleDebugLogger instance.
Referenced by Awake(), and UpdateState().
_giveUpButton
OnPointerDownButton Battle.View.UI.BattleUiGiveUpButtonHandler._giveUpButton private
[SerializeField] Reference to the Button component of the give up button.
BattleUiGiveUpButtonHandler-SerializeFields
Referenced by Awake(), and OnDestroy().
_giveUpButtonInfoText
TextMeshProUGUI Battle.View.UI.BattleUiGiveUpButtonHandler._giveUpButtonInfoText private
[SerializeField] Reference to the Text component of the give up info text.
BattleUiGiveUpButtonHandler-SerializeFields
_movableUiElement
BattleUiMovableElement Battle.View.UI.BattleUiGiveUpButtonHandler._movableUiElement private
[SerializeField] Reference to the BattleUiMovableElement script which is attached to a BattleUiGiveUpButton prefab.
BattleUiGiveUpButtonHandler-SerializeFields
_uiController
BattleUiController Battle.View.UI.BattleUiGiveUpButtonHandler._uiController private
[SerializeField] Reference to BattleUiController.
BattleUiGiveUpButtonHandler-SerializeFields
Referenced by Awake().
Property Documentation
IsVisible
bool Battle.View.UI.BattleUiGiveUpButtonHandler.IsVisible get
Is the UI element visible or not.
MovableUiElement
BattleUiMovableElement Battle.View.UI.BattleUiGiveUpButtonHandler.MovableUiElement get
Public getter for _movableUiElement.
Referenced by SetShow().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/View/Battle/Scripts/UI/Handler/BattleUiGiveUpButtonHandler.cs