Battle: Battle.QSimulation.Goal.BattleGoalQSystem Class Reference
Battle.QSimulation.Goal.BattleGoalQSystem Class Reference
Goal Quantum SystemSignalsOnly游못 [Systems]
Triggers the end of the game when the projectile hits a goal.
Static Public Member Functions
static void Init ()
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
static void OnProjectileHitGoal (Frame f, BattleCollisionQSystem.GoalCollisionData *goalCollisionData)
Called by BattleCollisionQSystem. If the goal has not already been triggered and projectile is not in held state, calls the OnGameOver method in BattleGameControlQSystem.
Static Private Attributes
static BattleDebugLogger s_debugLogger
This classes BattleDebugLogger instance.
Detailed Description
Goal Quantum SystemSignalsOnly游못 [Systems]
Triggers the end of the game when the projectile hits a goal.
This system is activated by BattleCollisionQSystem when projectile hits a goal. System then changes BattleGameState to "GameOver" to initiate game over procedures.
Member Function Documentation
Init()
void Battle.QSimulation.Goal.BattleGoalQSystem.Init () inline static
Initializes this classes BattleDebugLogger instance.
This method is exclusively for debug logging purposes.
References Battle.QSimulation.BattleDebugLogger.Create(), and s_debugLogger.
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.OnInit().
OnProjectileHitGoal()
void Battle.QSimulation.Goal.BattleGoalQSystem.OnProjectileHitGoal (Frame f, BattleCollisionQSystem.GoalCollisionData * goalCollisionData) inline static
Called by BattleCollisionQSystem. If the goal has not already been triggered and projectile is not in held state, calls the OnGameOver method in BattleGameControlQSystem.
Parameters
f Current simulation frame.
goalCollisionData Collision data.
References Quantum.NoTeam, Battle.QSimulation.Game.BattleGameControlQSystem.OnGameOver(), s_debugLogger, Quantum.TeamAlpha, and Quantum.TeamBeta.
Referenced by Battle.QSimulation.Game.BattleCollisionQSystem.OnTrigger2D().
Member Data Documentation
s_debugLogger
BattleDebugLogger Battle.QSimulation.Goal.BattleGoalQSystem.s_debugLogger static private
This classes BattleDebugLogger instance.
Referenced by Init(), and OnProjectileHitGoal().
The documentation for this class was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Goal/BattleGoalQSystem.cs