Battle: Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle Struct Reference
Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle Struct Reference
Public helper struct for getting player information.
Public Member Functions
BattlePlayerCharacterState GetCharacterState (int characterNumber)
void SetOutOfPlayRespawning ()
void SetOutOfPlayFinal ()
Static Public Member Functions
static BattlePlayerSlot GetSlot (Frame f, PlayerRef playerRef)
static BattleTeamNumber GetTeamNumber (BattlePlayerSlot slot)
Retrieves team number based on slot.
static bool IsValidCharacterNumber (int characterNumber)
static PlayerHandle GetPlayerHandle (Frame f, BattlePlayerSlot slot)
static PlayerHandle GetTeammateHandle (Frame f, BattlePlayerSlot slot)
static PlayerHandle[] GetPlayerHandleArray (Frame f)
static PlayerHandle GetPlayerHandleFromInternal (BattlePlayerManagerDataQSingleton *playerManagerData, int playerIndex)
Properties
BattlePlayerPlayState PlayState [get]
BattlePlayerSlot Slot [get]
PlayerRef PlayerRef [get]
bool IsBot [get]
bool IsAbandoned [get]
Public getter for IsAbandoned.
FrameTimer RespawnTimer [get, set]
bool AllowCharacterSwapping [get, set]
EntityRef SelectedCharacterEntity [get]
int SelectedCharacterNumber [get]
BattlePlayerCharacterState SelectedCharacterState [get]
bool PlayerGiveUpState [get, set]
Private Member Functions
PlayerHandle (PlayerHandleInternal internalHandle)
Private Attributes
PlayerHandleInternal _internalHandle
Detailed Description
Public helper struct for getting player information.
{Player Overview}
{Player Simulation Code Overview}
This is a public wrapper for the private PlayerHandleInternal that is used by the BattlePlayerManager internally.
This only exposes the parts of the PlayerHandleInternal that is meant to be accessible outside of BattlePlayerManager.
Constructor & Destructor Documentation
PlayerHandle()
Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.PlayerHandle (PlayerHandleInternal internalHandle) inline private
References _internalHandle.
Referenced by GetPlayerHandle(), GetPlayerHandleArray(), GetPlayerHandleFromInternal(), and GetTeammateHandle().
Member Function Documentation
GetCharacterState()
BattlePlayerCharacterState Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetCharacterState (int characterNumber)
References _internalHandle.
GetPlayerHandle()
PlayerHandle Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandle (Frame f, BattlePlayerSlot slot) inline static
References Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerHandle(), Battle.QSimulation.Player.BattlePlayerManager.GetPlayerManagerData(), and PlayerHandle().
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerCharacter(), and Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerShield().
GetPlayerHandleArray()
PlayerHandle[] Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandleArray (Frame f) inline static
References Quantum.Constants.BATTLE_PLAYER_SLOT_COUNT, Battle.QSimulation.Player.BattlePlayerManager.GetPlayerManagerData(), and PlayerHandle().
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.SpawnPlayers(), and Battle.QSimulation.Player.BattlePlayerQSystem.Update().
GetPlayerHandleFromInternal()
PlayerHandle Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandleFromInternal (BattlePlayerManagerDataQSingleton * playerManagerData, int playerIndex) inline static
References PlayerHandle().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.ConvertToPublic().
GetSlot()
BattlePlayerSlot Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetSlot (Frame f, PlayerRef playerRef) inline static
References Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerIndex(), Battle.QSimulation.Player.BattlePlayerManager.GetPlayerManagerData(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetSlot(), and PlayerRef.
Referenced by Battle.View.Game.BattleGameViewController.QEventOnViewInit().
GetTeammateHandle()
PlayerHandle Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle (Frame f, BattlePlayerSlot slot) inline static
References Battle.QSimulation.Player.BattlePlayerManager.GetPlayerManagerData(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetTeammateHandle(), and PlayerHandle().
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.HandleGiveUpLogic(), Battle.QSimulation.Player.BattlePlayerClassProjector.OnProjectileHitPlayerShield(), Battle.QSimulation.Player.BattlePlayerClassProjector.OnUpdate(), Battle.QSimulation.Projectile.BattleProjectileQSystem.ProjectileHitPlayerShield(), and Battle.View.Game.BattleGameViewController.QEventOnViewInit().
GetTeamNumber()
BattleTeamNumber Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeamNumber (BattlePlayerSlot slot) static
Retrieves team number based on slot.
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.HandleGiveUpLogic(), Battle.View.Player.BattlePlayerViewController.OnActivate(), and Battle.View.Game.BattleGameViewController.QEventOnViewInit().
IsValidCharacterNumber()
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.IsValidCharacterNumber (int characterNumber) static
SetOutOfPlayFinal()
void Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SetOutOfPlayFinal () inline
References _internalHandle, and Battle.QSimulation.Player.BattlePlayerManager.s_debugLogger.
SetOutOfPlayRespawning()
void Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SetOutOfPlayRespawning () inline
References _internalHandle, and Battle.QSimulation.Player.BattlePlayerManager.s_debugLogger.
Member Data Documentation
_internalHandle
PlayerHandleInternal Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle._internalHandle private
Referenced by GetCharacterState(), PlayerHandle(), SetOutOfPlayFinal(), and SetOutOfPlayRespawning().
Property Documentation
AllowCharacterSwapping
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.AllowCharacterSwapping get set
IsAbandoned
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.IsAbandoned get
Public getter for IsAbandoned.
IsBot
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.IsBot get
PlayerGiveUpState
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.PlayerGiveUpState get set
PlayerRef
PlayerRef Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.PlayerRef get
Referenced by GetSlot(), and Battle.View.Game.BattleGameViewController.QEventOnViewInit().
PlayState
BattlePlayerPlayState Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.PlayState get
Referenced by Battle.QSimulation.Projectile.BattleProjectileQSystem.ProjectileHitPlayerShield().
RespawnTimer
FrameTimer Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.RespawnTimer get set
SelectedCharacterEntity
EntityRef Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SelectedCharacterEntity get
Referenced by Battle.QSimulation.Player.BattlePlayerClassProjector.OnUpdate(), and Battle.QSimulation.Projectile.BattleProjectileQSystem.ProjectileHitPlayerShield().
SelectedCharacterNumber
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SelectedCharacterNumber get
Referenced by Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerCharacter(), and Battle.QSimulation.Player.BattlePlayerQSystem.OnProjectileHitPlayerShield().
SelectedCharacterState
BattlePlayerCharacterState Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.SelectedCharacterState get
Slot
BattlePlayerSlot Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.Slot get
The documentation for this struct was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerManager.cs