Battle: Quantum.QString64 Struct Reference
Quantum.QString64 Struct Reference
Public Member Functions
QString64 (String str)
override System.String ToString ()
Int32 IQString. CompareOrdinal (byte *bytes, UInt16 byteCount)
Int32 CompareOrdinal (String str)
override Boolean Equals (Object obj)
Boolean Equals (QString64 str)
Boolean Equals< T > (ref T str)
Int32 CompareOrdinal< T > (ref T str)
override Int32 GetHashCode ()
Static Public Member Functions
static Boolean CanHold (String str)
static implicit operator QString64 (String str)
static implicit operator String (QString64 str)
static void Serialize (void *ptr, FrameSerializer serializer)
Public Attributes
UInt16 ByteCount
fixed Byte Bytes [62]
Static Public Attributes
const Int32 SIZE = 64
const Int32 ALIGNMENT = 4
const int MaxByteCount = 62
Properties
int Length [get]
Constructor & Destructor Documentation
QString64()
Quantum.QString64.QString64 (String str) inline
References MaxByteCount.
Referenced by Equals(), operator QString64(), operator String(), and Serialize().
Member Function Documentation
CanHold()
Boolean Quantum.QString64.CanHold (String str) inline static
References MaxByteCount.
CompareOrdinal() [1/2]
Int32 IQString. Quantum.QString64.CompareOrdinal (byte * bytes, UInt16 byteCount) inline
CompareOrdinal() [2/2]
Int32 Quantum.QString64.CompareOrdinal (String str) inline
CompareOrdinal< T >()
Int32 Quantum.QString64.CompareOrdinal< T > (ref T str) inline
Type Constraints
T : unmanaged
T : IQString
Equals() [1/2]
override Boolean Quantum.QString64.Equals (Object obj) inline
Equals() [2/2]
Boolean Quantum.QString64.Equals (QString64 str) inline
References ByteCount, Bytes, and QString64().
Equals< T >()
Boolean Quantum.QString64.Equals< T > (ref T str) inline
Type Constraints
T : unmanaged
T : IQString
GetHashCode()
override Int32 Quantum.QString64.GetHashCode () inline
References ByteCount, and Bytes.
operator QString64()
implicit Quantum.QString64.operator QString64 (String str) inline static
References QString64().
operator String()
implicit Quantum.QString64.operator String (QString64 str) inline static
References QString64(), and ToString().
Serialize()
void Quantum.QString64.Serialize (void * ptr, FrameSerializer serializer) inline static
References QString64().
Referenced by Quantum.Statics.InitStaticDelegatesGen().
ToString()
override System.String Quantum.QString64.ToString () inline
Referenced by operator String().
Member Data Documentation
ALIGNMENT
const Int32 Quantum.QString64.ALIGNMENT = 4 static
ByteCount
UInt16 Quantum.QString64.ByteCount
Referenced by Equals(), and GetHashCode().
Bytes
fixed Byte Quantum.QString64.Bytes[62]
Referenced by Equals(), and GetHashCode().
MaxByteCount
const int Quantum.QString64.MaxByteCount = 62 static
Referenced by CanHold(), and QString64().
SIZE
const Int32 Quantum.QString64.SIZE = 64 static
Referenced by Quantum.Statics.RegisterSimulationTypesGen().
Property Documentation
Length
int Quantum.QString64.Length get
The documentation for this struct was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs