Battle: Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal Struct Reference
Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal Struct Reference
Internal helper struct for player operations and state management in BattlePlayerManager.
Has static helper methods for player operations.
Can be instantiated to handle specific player's data stored in BattlePlayerManagerDataQSingleton.
Public Member Functions
PlayerHandleInternal (BattlePlayerManagerDataQSingleton *playerManagerData, int playerIndex)
Constructor for PlayerHandleInternal.
PlayerHandle ConvertToPublic ()
EntityRef GetCharacterEntity (int characterNumber)
Gets an EntityRef to a player's Character by characterNumber.
void SetCharacterEntities (EntityRef[] entityRefArray)
Saves player's created character EntityRefs to BattlePlayerManagerDataQSingleton.
BattlePlayerCharacterState GetCharacterState (int characterNumber)
Sets player's SelectedCharacter and updates SelectedCharacterNumber based on characterNumber .
The SelectedCharacter is a EntityRef to the character that is currently in play.
void SetCharacterState (int characterNumber, BattlePlayerCharacterState state)
void SetSelectedCharacter (int characterNumber)
void UnsetSelectedCharacter ()
Unsets player's SelectedCharacter and updates SelectedCharacterNumber.
The SelectedCharacter is a EntityRef to the character that is currently in play.
FPVector2 GetOutOfPlayPosition (int characterNumber, BattleTeamNumber teamNumber)
Generates a position for the player's character that is out of play.
Each character of each player has a unique position that is used when the character is out of play.
Static Public Member Functions
static BattlePlayerSlot GetSlot (int playerIndex)
static BattleTeamNumber GetTeamNumber (BattlePlayerSlot slot)
Retrieves team number based on slot.
static int GetPlayerIndex (BattlePlayerSlot slot)
Retrieves player index based on slot.
static int GetPlayerIndex (BattlePlayerManagerDataQSingleton *playerManagerData, PlayerRef playerRef)
Retrieves player index from a PlayerRef.
static int GetTeammatePlayerIndex (BattlePlayerSlot slot)
Retrieves the index of the teammate of a player based on slot.
static PlayerHandleInternal GetPlayerHandle (BattlePlayerManagerDataQSingleton *playerManagerData, BattlePlayerSlot slot)
Retrieves PlayerHandle based on slot.
static PlayerHandleInternal GetTeammateHandle (BattlePlayerManagerDataQSingleton *playerManagerData, BattlePlayerSlot slot)
Retrieves PlayerHandle of the teammate of a player based on slot.
static void SetAllPlayStates (BattlePlayerManagerDataQSingleton *playerManagerData, BattlePlayerPlayState playerPlayState)
Sets all players' play states to a given state.
static bool IsValidCharacterNumber (int characterNumber)
Checks if a given character number is valid.
Properties
int Index [get, set]
BattlePlayerPlayState PlayState [get, set]
Gets/Sets player's PlayState.
PlayerRef PlayerRef [get, set]
Gets/Sets player's PlayerRef.
bool IsBot [get, set]
bool IsAbandoned [get, set]
Gets and sets player's IsAbandoned state.
FrameTimer RespawnTimer [get, set]
bool AllowCharacterSwapping [get, set]
EntityRef SelectedCharacterEntity [get]
Gets player's SelectedCharacterEntity.
The SelectedCharacterEntity is a EntityRef to the character that is currently in play.
int SelectedCharacterNumber [get]
Gets player's SelectedCharacterNumber.
The SelectedCharacterNumber is the number of the character that is currently in play.
BattlePlayerCharacterState SelectedCharacterState [get, set]
bool PlayerGiveUpState [get, set]
FPVector2 SpawnPosition [get]
Private Member Functions
int GetCharacterOffset ()
Calculates the index where player's characters start in the BattlePlayerManagerDataQSingleton.
int GetCharacterIndex (int characterNumber)
Calculates the index of player's character is in the BattlePlayerManagerDataQSingleton.
Private Attributes
BattlePlayerManagerDataQSingleton * _playerManagerData
Pointer to the BattlePlayerManagerDataQSingleton.
Detailed Description
Internal helper struct for player operations and state management in BattlePlayerManager.
Has static helper methods for player operations.
Can be instantiated to handle specific player's data stored in BattlePlayerManagerDataQSingleton.
Constructor & Destructor Documentation
PlayerHandleInternal()
Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayerHandleInternal (BattlePlayerManagerDataQSingleton * playerManagerData, int playerIndex) inline
Constructor for PlayerHandleInternal.
Parameters
playerManagerData Pointer to BattlePlayerManagerDataQSingleton.
playerIndex Index of the player that you want the handle to.
References _playerManagerData, and Index.
Referenced by GetPlayerHandle(), and GetTeammateHandle().
Member Function Documentation
ConvertToPublic()
PlayerHandle Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.ConvertToPublic () inline
References _playerManagerData, Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandleFromInternal(), and Index.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer(), Battle.QSimulation.Player.BattlePlayerManager.MarkAbandoned(), and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
GetCharacterEntity()
EntityRef Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetCharacterEntity (int characterNumber)
Gets an EntityRef to a player's Character by characterNumber.
Parameters
characterNumber CharacterNumber of the player's character you want to get.
Returns
EntityRef to a player's Character.
References _playerManagerData.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
GetCharacterIndex()
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetCharacterIndex (int characterNumber) private
Calculates the index of player's character is in the BattlePlayerManagerDataQSingleton.
Referenced by SetSelectedCharacter().
GetCharacterOffset()
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetCharacterOffset () private
Calculates the index where player's characters start in the BattlePlayerManagerDataQSingleton.
References Index.
Referenced by SetCharacterEntities().
GetCharacterState()
BattlePlayerCharacterState Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetCharacterState (int characterNumber)
Sets player's SelectedCharacter and updates SelectedCharacterNumber based on characterNumber .
The SelectedCharacter is a EntityRef to the character that is currently in play.
Parameters
characterNumber CharacterNumber of the player's character you want to set.
References _playerManagerData.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
GetOutOfPlayPosition()
FPVector2 Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetOutOfPlayPosition (int characterNumber, BattleTeamNumber teamNumber) inline
Generates a position for the player's character that is out of play.
Each character of each player has a unique position that is used when the character is out of play.
Parameters
characterNumber CharacterNumber of the player's character that is moved out of play.
teamNumber TeamNumber of the player whose character that is moved out of play.
Returns
The generated position.
References Battle.QSimulation.Game.BattleGridManager.Columns, Battle.QSimulation.Game.BattleGridManager.GridColToWorldXPosition(), Battle.QSimulation.Game.BattleGridManager.GridRowToWorldYPosition(), Index, and Battle.QSimulation.Game.BattleGridManager.Rows.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), and Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer().
GetPlayerHandle()
PlayerHandleInternal Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerHandle (BattlePlayerManagerDataQSingleton * playerManagerData, BattlePlayerSlot slot) inline static
Retrieves PlayerHandle based on slot.
Parameters
playerManagerData Pointer reference to the player manager data.
slot The slot of the player.
Returns
A PlayerHandle for the given player.
References GetPlayerIndex(), and PlayerHandleInternal().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetPlayerHandle(), Battle.QSimulation.Player.BattlePlayerManager.RegisterPlayer(), and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
GetPlayerIndex() [1/2]
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerIndex (BattlePlayerManagerDataQSingleton * playerManagerData, PlayerRef playerRef) inline static
Retrieves player index from a PlayerRef.
Parameters
playerManagerData Pointer reference to the player manager data.
playerRef PlayerRef of the player.
Returns
The index of the given player.
References Quantum.Constants.BATTLE_PLAYER_SLOT_COUNT, PlayerRef, and Quantum.BattlePlayerManagerDataQSingleton.PlayerRefs.
GetPlayerIndex() [2/2]
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetPlayerIndex (BattlePlayerSlot slot) inline static
Retrieves player index based on slot.
Parameters
slot The slot of the player.
Returns
The index of the given player.
References Quantum.Slot1, Quantum.Slot2, Quantum.Slot3, and Quantum.Slot4.
Referenced by GetPlayerHandle(), Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetSlot(), and Battle.QSimulation.Player.BattlePlayerManager.MarkAbandoned().
GetSlot()
BattlePlayerSlot Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetSlot (int playerIndex) inline static
References Quantum.Spectator.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), and Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetSlot().
GetTeammateHandle()
PlayerHandleInternal Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetTeammateHandle (BattlePlayerManagerDataQSingleton * playerManagerData, BattlePlayerSlot slot) inline static
Retrieves PlayerHandle of the teammate of a player based on slot.
Parameters
playerManagerData Pointer reference to the player manager data.
slot The slot of the player.
Returns
A PlayerHandle for the given player's teammate.
References GetTeammatePlayerIndex(), and PlayerHandleInternal().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.PlayerHandle.GetTeammateHandle().
GetTeammatePlayerIndex()
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetTeammatePlayerIndex (BattlePlayerSlot slot) inline static
Retrieves the index of the teammate of a player based on slot.
Parameters
slot The slot of the player.
Returns
The index of the given player's teammate.
References Quantum.Slot1, Quantum.Slot2, Quantum.Slot3, and Quantum.Slot4.
Referenced by GetTeammateHandle().
GetTeamNumber()
BattleTeamNumber Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.GetTeamNumber (BattlePlayerSlot slot) inline static
Retrieves team number based on slot.
Parameters
slot The slot of the player.
Returns
The BattleTeamNumber of the given player.
References Quantum.NoTeam, Quantum.Slot1, Quantum.Slot2, Quantum.Slot3, and Quantum.Slot4.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers().
IsValidCharacterNumber()
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.IsValidCharacterNumber (int characterNumber) static
Checks if a given character number is valid.
Parameters
characterNumber The character number to verify.
Returns
True if the given character number is valid, false if it is not.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
SetAllPlayStates()
void Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetAllPlayStates (BattlePlayerManagerDataQSingleton * playerManagerData, BattlePlayerPlayState playerPlayState) inline static
Sets all players' play states to a given state.
Parameters
playerManagerData Pointer reference to the player manager data.
playerPlayState The state that all players will be set to.
References Quantum.Constants.BATTLE_PLAYER_SLOT_COUNT, and Quantum.BattlePlayerManagerDataQSingleton.PlayStates.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.Init().
SetCharacterEntities()
void Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetCharacterEntities (EntityRef[] entityRefArray) inline
Saves player's created character EntityRefs to BattlePlayerManagerDataQSingleton.
Parameters
entityRefArray The Character EntityRefs as an array.
References _playerManagerData, Quantum.Constants.BATTLE_PLAYER_CHARACTER_COUNT, and GetCharacterOffset().
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers().
SetCharacterState()
void Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetCharacterState (int characterNumber, BattlePlayerCharacterState state)
References _playerManagerData.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers().
SetSelectedCharacter()
void Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SetSelectedCharacter (int characterNumber) inline
References _playerManagerData, GetCharacterIndex(), and Index.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
UnsetSelectedCharacter()
void Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.UnsetSelectedCharacter () inline
Unsets player's SelectedCharacter and updates SelectedCharacterNumber.
The SelectedCharacter is a EntityRef to the character that is currently in play.
References _playerManagerData, and Index.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer().
Member Data Documentation
_playerManagerData
BattlePlayerManagerDataQSingleton* Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal._playerManagerData private
Pointer to the BattlePlayerManagerDataQSingleton.
Referenced by ConvertToPublic(), GetCharacterEntity(), GetCharacterState(), PlayerHandleInternal(), SetCharacterEntities(), SetCharacterState(), SetSelectedCharacter(), and UnsetSelectedCharacter().
Property Documentation
AllowCharacterSwapping
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.AllowCharacterSwapping get set
Index
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.Index get set
Referenced by ConvertToPublic(), GetCharacterOffset(), GetOutOfPlayPosition(), PlayerHandleInternal(), Battle.QSimulation.Player.BattlePlayerManager.RegisterPlayer(), SetSelectedCharacter(), and UnsetSelectedCharacter().
IsAbandoned
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.IsAbandoned get set
Gets and sets player's IsAbandoned state.
IsBot
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.IsBot get set
PlayerGiveUpState
bool Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayerGiveUpState get set
PlayerRef
PlayerRef Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayerRef get set
Gets/Sets player's PlayerRef.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), GetPlayerIndex(), and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
PlayState
BattlePlayerPlayState Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.PlayState get set
Gets/Sets player's PlayState.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer(), Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer(), and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
RespawnTimer
FrameTimer Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.RespawnTimer get set
SelectedCharacterEntity
EntityRef Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SelectedCharacterEntity get
Gets player's SelectedCharacterEntity.
The SelectedCharacterEntity is a EntityRef to the character that is currently in play.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer(), and Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
SelectedCharacterNumber
int Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SelectedCharacterNumber get
Gets player's SelectedCharacterNumber.
The SelectedCharacterNumber is the number of the character that is currently in play.
Referenced by Battle.QSimulation.Player.BattlePlayerManager.DespawnPlayer().
SelectedCharacterState
BattlePlayerCharacterState Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SelectedCharacterState get set
SpawnPosition
FPVector2 Battle.QSimulation.Player.BattlePlayerManager.PlayerHandleInternal.SpawnPosition get
Referenced by Battle.QSimulation.Player.BattlePlayerManager.SpawnPlayer().
The documentation for this struct was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Player/BattlePlayerManager.cs