Battle: Battle.QSimulation.Game.BattleParameters Struct Reference
Battle.QSimulation.Game.BattleParameters Struct Reference
Public Types
enum PlayerType { None = 0 , Player = 1 , Bot = 2 }
Static Public Member Functions
static PlayerType[] GetPlayerSlotTypes (Frame f)
static string[] GetPlayerSlotUserIDs (Frame f)
static string[] GetPlayerNames (Frame f)
static int GetPlayerCount (Frame f)
static BattleEmotionState GetProjectileInitialEmotion (Frame f)
Public Attributes
PlayerType[] PlayerSlotTypes
string[] PlayerSlotUserIDs
string[] PlayerNames
int PlayerCount
BattleEmotionState ProjectileInitialEmotion
Member Enumeration Documentation
PlayerType
enum Battle.QSimulation.Game.BattleParameters.PlayerType
Enumerator
None
Player
Bot
Member Function Documentation
GetPlayerCount()
int Battle.QSimulation.Game.BattleParameters.GetPlayerCount (Frame f) static
Referenced by Battle.QSimulation.Player.BattlePlayerManager.Init(), and Battle.QSimulation.Player.BattlePlayerManager.IsAllPlayersRegistered().
GetPlayerNames()
string[] Battle.QSimulation.Game.BattleParameters.GetPlayerNames (Frame f) static
Referenced by Battle.QSimulation.Game.BattleGameControlQSystem.Update().
GetPlayerSlotTypes()
PlayerType[] Battle.QSimulation.Game.BattleParameters.GetPlayerSlotTypes (Frame f) static
Referenced by Battle.QSimulation.Player.BattlePlayerManager.CreatePlayers(), Battle.QSimulation.Player.BattlePlayerManager.Init(), Battle.View.Game.BattleGameViewController.QEventOnViewWaitForPlayers(), and Battle.QSimulation.Player.BattlePlayerManager.RegisterPlayer().
GetPlayerSlotUserIDs()
string[] Battle.QSimulation.Game.BattleParameters.GetPlayerSlotUserIDs (Frame f) static
Referenced by Battle.QSimulation.Player.BattlePlayerManager.Init(), and Battle.QSimulation.Player.BattlePlayerManager.RegisterPlayer().
GetProjectileInitialEmotion()
BattleEmotionState Battle.QSimulation.Game.BattleParameters.GetProjectileInitialEmotion (Frame f) static
Referenced by Battle.QSimulation.Projectile.BattleProjectileQSystem.Launch().
Member Data Documentation
PlayerCount
int Battle.QSimulation.Game.BattleParameters.PlayerCount
PlayerNames
string [] Battle.QSimulation.Game.BattleParameters.PlayerNames
PlayerSlotTypes
PlayerType [] Battle.QSimulation.Game.BattleParameters.PlayerSlotTypes
PlayerSlotUserIDs
string [] Battle.QSimulation.Game.BattleParameters.PlayerSlotUserIDs
ProjectileInitialEmotion
BattleEmotionState Battle.QSimulation.Game.BattleParameters.ProjectileInitialEmotion
The documentation for this struct was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Battle/Scripts/Game/BattleQConfig.cs