Battle: Quantum.QString512 Struct Reference
Quantum.QString512 Struct Reference
Public Member Functions
QString512 (String str)
override System.String ToString ()
Int32 IQString. CompareOrdinal (byte *bytes, UInt16 byteCount)
Int32 CompareOrdinal (String str)
override Boolean Equals (Object obj)
Boolean Equals (QString512 str)
Boolean Equals< T > (ref T str)
Int32 CompareOrdinal< T > (ref T str)
override Int32 GetHashCode ()
Static Public Member Functions
static Boolean CanHold (String str)
static implicit operator QString512 (String str)
static implicit operator String (QString512 str)
static void Serialize (void *ptr, FrameSerializer serializer)
Public Attributes
UInt16 ByteCount
fixed Byte Bytes [510]
Static Public Attributes
const Int32 SIZE = 512
const Int32 ALIGNMENT = 4
const int MaxByteCount = 510
Properties
int Length [get]
Constructor & Destructor Documentation
QString512()
Quantum.QString512.QString512 (String str) inline
References MaxByteCount.
Referenced by Equals(), operator QString512(), operator String(), and Serialize().
Member Function Documentation
CanHold()
Boolean Quantum.QString512.CanHold (String str) inline static
References MaxByteCount.
CompareOrdinal() [1/2]
Int32 IQString. Quantum.QString512.CompareOrdinal (byte * bytes, UInt16 byteCount) inline
CompareOrdinal() [2/2]
Int32 Quantum.QString512.CompareOrdinal (String str) inline
CompareOrdinal< T >()
Int32 Quantum.QString512.CompareOrdinal< T > (ref T str) inline
Type Constraints
T : unmanaged
T : IQString
Equals() [1/2]
override Boolean Quantum.QString512.Equals (Object obj) inline
Equals() [2/2]
Boolean Quantum.QString512.Equals (QString512 str) inline
References ByteCount, Bytes, and QString512().
Equals< T >()
Boolean Quantum.QString512.Equals< T > (ref T str) inline
Type Constraints
T : unmanaged
T : IQString
GetHashCode()
override Int32 Quantum.QString512.GetHashCode () inline
References ByteCount, and Bytes.
operator QString512()
implicit Quantum.QString512.operator QString512 (String str) inline static
References QString512().
operator String()
implicit Quantum.QString512.operator String (QString512 str) inline static
References QString512(), and ToString().
Serialize()
void Quantum.QString512.Serialize (void * ptr, FrameSerializer serializer) inline static
References QString512().
ToString()
override System.String Quantum.QString512.ToString () inline
Referenced by operator String().
Member Data Documentation
ALIGNMENT
const Int32 Quantum.QString512.ALIGNMENT = 4 static
ByteCount
UInt16 Quantum.QString512.ByteCount
Referenced by Equals(), and GetHashCode().
Bytes
fixed Byte Quantum.QString512.Bytes[510]
Referenced by Equals(), and GetHashCode().
MaxByteCount
const int Quantum.QString512.MaxByteCount = 510 static
Referenced by CanHold(), and QString512().
SIZE
const Int32 Quantum.QString512.SIZE = 512 static
Referenced by Quantum.Statics.RegisterSimulationTypesGen().
Property Documentation
Length
int Quantum.QString512.Length get
The documentation for this struct was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Generated/Quantum.CodeGen.Core.cs