Battle: Quantum.PlayerManager.PlayerHandle Struct Reference
Quantum.PlayerManager.PlayerHandle Struct Reference
Public Member Functions
PlayerHandle (PlayerManagerData *playerManagerData, BattlePlayerSlot slot)
EntityRef GetCharacter (int characterNumber)
void SetCharacters (EntityRef[] entityRefArray)
void SetSelectedCharacter (int characterNumber)
void UnsetSelectedCharacter ()
FPVector2 GetOutOfPlayPosition (int characterNumber, BattleTeamNumber teamNumber)
Static Public Member Functions
static BattleTeamNumber GetTeamNumber (BattlePlayerSlot slot)
static int GetPlayerIndex (BattlePlayerSlot slot)
static int GetTeammatePlayerIndex (BattlePlayerSlot slot)
static PlayerPlayState GetPlayState (PlayerManagerData *playerManagerData, int playerIndex)
static void SetAllPlayStates (PlayerManagerData *playerManagerData, PlayerPlayState playerPlayState)
static bool IsValidCharacterNumber (int characterNumber)
static EntityRef GetSelectedCharacter (PlayerManagerData *playerManagerData, int playerIndex)
Properties
int Index [get, private set]
PlayerPlayState PlayState [get, set]
PlayerRef PlayerRef [get, set]
EntityRef SelectedCharacter [get]
int SelectedCharacterNumber [get]
FPVector2 SpawnPosition [get]
Private Member Functions
int GetCharacterOffset ()
int GetCharacterIndex (int characterNumber)
Private Attributes
PlayerManagerData * _playerManagerData
Constructor & Destructor Documentation
PlayerHandle()
Quantum.PlayerManager.PlayerHandle.PlayerHandle (PlayerManagerData * playerManagerData, BattlePlayerSlot slot) inline
References _playerManagerData, GetPlayerIndex(), and Index.
Member Function Documentation
GetCharacter()
EntityRef Quantum.PlayerManager.PlayerHandle.GetCharacter (int characterNumber)
References _playerManagerData.
Referenced by Quantum.PlayerManager.SpawnPlayer().
GetCharacterIndex()
int Quantum.PlayerManager.PlayerHandle.GetCharacterIndex (int characterNumber) private
Referenced by SetSelectedCharacter().
GetCharacterOffset()
int Quantum.PlayerManager.PlayerHandle.GetCharacterOffset () private
References Index.
Referenced by SetCharacters().
GetOutOfPlayPosition()
FPVector2 Quantum.PlayerManager.PlayerHandle.GetOutOfPlayPosition (int characterNumber, BattleTeamNumber teamNumber) inline
References Quantum.GridManager.Columns, Quantum.GridManager.GridColToWorldXPosition(), Quantum.GridManager.GridRowToWorldYPosition(), Index, and Quantum.GridManager.Rows.
Referenced by Quantum.PlayerManager.DespawnPlayer(), and Quantum.PlayerManager.InitPlayer().
GetPlayerIndex()
static int Quantum.PlayerManager.PlayerHandle.GetPlayerIndex (BattlePlayerSlot slot) inline static
References Quantum.Slot1, Quantum.Slot2, Quantum.Slot3, and Quantum.Slot4.
Referenced by Quantum.PlayerManager.GetPlayerEntity(), Quantum.PlayerManager.GetPlayerPlayState(), and PlayerHandle().
GetPlayState()
static PlayerPlayState Quantum.PlayerManager.PlayerHandle.GetPlayState (PlayerManagerData * playerManagerData, int playerIndex) static
Referenced by Quantum.PlayerManager.GetPlayerPlayState().
GetSelectedCharacter()
static EntityRef Quantum.PlayerManager.PlayerHandle.GetSelectedCharacter (PlayerManagerData * playerManagerData, int playerIndex) static
Referenced by Quantum.PlayerManager.GetPlayerEntity(), and Quantum.PlayerManager.GetTeammateEntity().
GetTeammatePlayerIndex()
static int Quantum.PlayerManager.PlayerHandle.GetTeammatePlayerIndex (BattlePlayerSlot slot) inline static
References Quantum.Slot1, Quantum.Slot2, Quantum.Slot3, and Quantum.Slot4.
Referenced by Quantum.PlayerManager.GetTeammateEntity().
GetTeamNumber()
static BattleTeamNumber Quantum.PlayerManager.PlayerHandle.GetTeamNumber (BattlePlayerSlot slot) inline static
References Quantum.NoTeam, Quantum.Slot1, Quantum.Slot2, Quantum.Slot3, and Quantum.Slot4.
Referenced by Quantum.PlayerManager.InitPlayer().
IsValidCharacterNumber()
static bool Quantum.PlayerManager.PlayerHandle.IsValidCharacterNumber (int characterNumber) static
Referenced by Quantum.PlayerManager.SpawnPlayer().
SetAllPlayStates()
static void Quantum.PlayerManager.PlayerHandle.SetAllPlayStates (PlayerManagerData * playerManagerData, PlayerPlayState playerPlayState) inline static
References Quantum.Constants.PLAYER_SLOT_COUNT, and Quantum.PlayerManagerData.PlayStates.
Referenced by Quantum.PlayerManager.Init().
SetCharacters()
void Quantum.PlayerManager.PlayerHandle.SetCharacters (EntityRef[] entityRefArray) inline
References _playerManagerData, GetCharacterOffset(), and Quantum.Constants.PLAYER_CHARACTER_COUNT.
Referenced by Quantum.PlayerManager.InitPlayer().
SetSelectedCharacter()
void Quantum.PlayerManager.PlayerHandle.SetSelectedCharacter (int characterNumber) inline
References _playerManagerData, GetCharacterIndex(), and Index.
Referenced by Quantum.PlayerManager.SpawnPlayer().
UnsetSelectedCharacter()
void Quantum.PlayerManager.PlayerHandle.UnsetSelectedCharacter () inline
References _playerManagerData, and Index.
Referenced by Quantum.PlayerManager.DespawnPlayer().
Member Data Documentation
_playerManagerData
PlayerManagerData* Quantum.PlayerManager.PlayerHandle._playerManagerData private
Referenced by GetCharacter(), PlayerHandle(), SetCharacters(), SetSelectedCharacter(), and UnsetSelectedCharacter().
Property Documentation
Index
int Quantum.PlayerManager.PlayerHandle.Index get private set
Referenced by GetCharacterOffset(), GetOutOfPlayPosition(), PlayerHandle(), SetSelectedCharacter(), and UnsetSelectedCharacter().
PlayerRef
PlayerRef Quantum.PlayerManager.PlayerHandle.PlayerRef get set
Referenced by Quantum.PlayerManager.SpawnPlayer().
PlayState
PlayerPlayState Quantum.PlayerManager.PlayerHandle.PlayState get set
Referenced by Quantum.PlayerManager.DespawnPlayer(), Quantum.PlayerManager.SpawnPlayer(), and Quantum.PlayerManager.SpawnPlayer().
SelectedCharacter
EntityRef Quantum.PlayerManager.PlayerHandle.SelectedCharacter get
Referenced by Quantum.PlayerManager.DespawnPlayer(), and Quantum.PlayerManager.SpawnPlayer().
SelectedCharacterNumber
int Quantum.PlayerManager.PlayerHandle.SelectedCharacterNumber get
Referenced by Quantum.PlayerManager.DespawnPlayer().
SpawnPosition
FPVector2 Quantum.PlayerManager.PlayerHandle.SpawnPosition get
Referenced by Quantum.PlayerManager.SpawnPlayer().
The documentation for this struct was generated from the following file:
Altzone/Assets/QuantumUser/Simulation/Scripts/Player/PlayerManager.cs