using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace MenuUi.Scripts.AvatarEditor
{
    public enum FeatureID 
    {
        Default ,
        None,
        ConfluenceGirlsOneHair,
        ConfluenceGirlsTwoHair ,
        ResearcherHair ,
        BodybuilderHair ,
        ComedianHair ,
        GrafitiArtistHair ,
        OvereaterHair ,
        PreacherHair ,
        ConfluenceGirlsOneEyes,
        ConfluenceGirlsTwoEyes ,
        ResearcherEyes ,
        BodybuilderEyes ,
        ComedianEyes  ,
        GrafitiArtistEyes  ,
        OvereaterEyes  ,
        PreacherEyes  ,
        ConfluenceGirlsOneNose,
        ConfluenceGirlsTwoNose ,
        ResearcherNose ,
        BodybuilderNose ,
        ComedianNose  ,
        GrafitiArtistNose  ,
        OvereaterNose  ,
        PreacherNose  ,
        ConfluenceGirlsOneMouth,
        ConfluenceGirlsTwoMouth ,
        ResearcherMouth ,
        BodybuilderMouth ,
        ComedianMouth  ,
        GrafitiArtistMouth  ,
        OvereaterMouth  ,
        PreacherMouth  ,
        ResearcherFacialHair ,
        ConfluenceGirlsOneBody,
        ConfluenceGirlsTwoBody ,
        ResearcherBody ,
        BodybuilderBody ,
        ComedianBody  ,
        GrafitiArtistBody  ,
        OvereaterBody  ,
        PreacherBody  ,
        ConfluenceGirlsOneHands,
        ConfluenceGirlsTwoHands ,
        ResearcherHands ,
        BodybuilderHands ,
        ComedianHands  ,
        GrafitiArtistHands  ,
        OvereaterHands  ,
        PreacherHands  ,
        ConfluenceGirlsOneFeet,
        ConfluenceGirlsTwoFeet ,
        ResearcherFeet ,
        BodybuilderFeet ,
        ComedianFeet  ,
        GrafitiArtistFeet  ,
        OvereaterFeet  ,
        PreacherFeet  ,
        BlankHeadOne,
        BlankHeadTwo,
        BlankHeadThree,
        BlankHeadFour,
    }

}